"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, BookOpenCheck, CheckCircle2, ClipboardCheck, Loader2, RefreshCw, Save, ShieldCheck } from "lucide-react";
import { nextStep, type CycleView, type EntryKind, type PracticeEntry } from "@/lib/learning-cycle/rules";
const panel = "glass min-w-0 rounded-2xl border border-white/10 p-5 sm:p-6";
const control = "w-full rounded-xl border border-white/15 bg-background/60 p-3 text-base text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-averna-cyan";
const button = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-2 text-sm font-semibold text-white hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-averna-cyan disabled:cursor-not-allowed disabled:opacity-50";
const outcomeLabel = { demonstrated: "Demonstrated in this response", developing: "Developing", not_yet: "Not yet demonstrated" };
export function CycleWorkspace({ initial }: { initial: CycleView }) {
  const [data, setData] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""); const flight = useRef(false);
  const [target, setTarget] = useState("global");
  async function request(command?: Record<string, unknown>) {
    if (flight.current) return false; flight.current = true; setTarget(command?.entryId ? String(command.entryId) : command?.action === "SUBMIT" || command?.action === "SAVE_DRAFT" ? "practice" : "global"); setBusy(true); setError(""); setNotice("");
    try { const response = await fetch(`/api/learning/feedback-cycle/${encodeURIComponent(data.sourceId)}`, { method: command ? "POST" : "GET", cache: "no-store", ...(command ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(command) } : {}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not save. Please retry."); if (!result.cycle) throw new Error("The response could not be refreshed. Keep your draft and retry."); setData(result.cycle); setNotice(command?.action === "SAVE_DRAFT" ? "Draft saved privately. Your teacher cannot see it until you submit." : command ? "Saved. Your original exam grade and XP are unchanged." : "Latest feedback loaded."); return true; } catch (e) { setError(e instanceof Error ? e.message : "Could not complete the request. Keep your draft and retry."); return false; } finally { flight.current = false; setBusy(false); }
  }
  const step = nextStep(data.entries); const resultHref = data.plan.skill === "WRITING" ? `/learning/writing/result/${data.sourceId}` : `/learning/speaking-test/result/${data.sourceId}`;
  const editableKind: EntryKind = step === "TRANSFER" ? "TRANSFER" : "REVISION";
  const showPractice = !!data.id && data.canWrite && (step === "REVISION" || step === "TRANSFER");
  const globalStatus = target === "global" || (target === "practice" && !showPractice);
  return <div className="space-y-6">
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div className="min-w-0"><p className="text-sm font-semibold text-averna-cyan">Feedback → practice → evidence</p><h1 className="mt-2 text-2xl font-bold text-white sm:text-3xl break-words">{data.plan.title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-gray-400">A focused learning cycle, not another exam. Original scores, homework grades and XP are preserved.</p></div>
      <button type="button" className={button} onClick={() => void request()} disabled={busy}><RefreshCw className="h-4 w-4" aria-hidden />Refresh feedback</button>
    </header>
    <nav aria-label="Practice cycle steps" className="grid grid-cols-1 gap-2 sm:grid-cols-3">{["1. Revise your response", "2. Apply it to a new task", "3. Keep the evidence"].map((label, i) => <div key={label} className={`rounded-xl border p-3 text-sm ${i === 0 && step.startsWith("REVISION") || i === 1 && step === "TRANSFER" || i === 2 && step === "COMPLETE" ? "border-averna-cyan/40 bg-averna-cyan/10 text-white" : "border-white/10 text-gray-400"}`}>{label}</div>)}</nav>
    {globalStatus && <RequestStatus error={error} notice={notice} />}
    <section className={panel} aria-labelledby="why-heading">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="why-heading" className="flex items-center gap-2 text-lg font-semibold text-white"><ShieldCheck className="h-5 w-5 text-averna-cyan" aria-hidden />Why this result?</h2><p className="mt-2 text-sm text-gray-400">{data.plan.baseline.source === "teacher" ? "Teacher-reviewed assessment" : data.plan.baseline.source === "heuristic" ? "Provisional text-metric estimate" : data.plan.baseline.source === "ai" ? "AI practice estimate" : "No rated assessment available"} · {data.plan.baseline.band === null ? "No band recorded" : `Recorded band ${data.plan.baseline.band.toFixed(1)}`}</p></div><Link href={resultHref} className={button}>Original result <ArrowRight className="h-4 w-4" aria-hidden /></Link></div>
      <p className="mt-3 text-sm leading-relaxed text-gray-400">This explains the saved criteria, not hidden reasoning or an official IELTS result. Snapshot {data.plan.baseline.capturedAt.slice(0, 10)}. The cycle freezes its starting feedback; the original result may later receive an updated assessment.</p>
      <dl className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(data.plan.baseline.criteria).map(([key, value]) => <div key={key} className="flex justify-between gap-4 rounded-xl border border-white/10 p-3"><dt className="text-sm text-gray-300">{({ taskAchievement: "Task Achievement / Response", coherenceCohesion: "Coherence & Cohesion", lexicalResource: "Lexical Resource", grammarAccuracy: "Grammar", fluency: "Fluency & Coherence", lexical: "Lexical Resource", grammar: "Grammar", pronunciation: "Pronunciation" } as Record<string, string>)[key] ?? key}</dt><dd className="shrink-0 text-sm font-semibold text-white">{value === null ? "Not rated" : value.toFixed(1)}</dd></div>)}</dl>
      {data.plan.baseline.comment && <details className="mt-4"><summary className="flex min-h-11 cursor-pointer items-center text-sm font-semibold text-averna-cyan">Read the recorded feedback</summary><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed text-gray-300">{data.plan.baseline.comment}</p></details>}
    </section>
    <div className="grid grid-cols-1 items-stretch gap-6 lg:grid-cols-2">
      <section className={panel}><h2 className="scroll-mt-20 text-lg font-semibold text-white">Your focus skills</h2><p className="mt-2 text-sm text-gray-400">Rated criteria guide the focus where available; otherwise these are general practice suggestions, not diagnosed weaknesses.</p><div className="mt-4 space-y-4">{data.plan.goals.map(g => <div key={g.key} className="rounded-xl border border-averna-cyan/20 bg-averna-cyan/5 p-4"><h3 className="font-semibold text-white">{g.label}</h3><p className="mt-2 text-sm leading-relaxed text-gray-400">{g.meaning}</p><p className="mt-3 text-sm leading-relaxed text-gray-200">{g.action}</p></div>)}</div>{data.plan.skill === "SPEAKING" && <p className="mt-4 text-sm leading-relaxed text-amber-200">This first release uses written speaking preparation. We cannot assess pronunciation or pacing without new audio.</p>}</section>
      <section className={panel}><h2 className="scroll-mt-20 text-lg font-semibold text-white">Original work</h2><p className="mt-2 text-sm text-gray-400">Kept unchanged so you can compare it with the revision.</p><details className="mt-3"><summary className="flex min-h-11 cursor-pointer items-center text-sm text-averna-cyan">Read the task and response</summary><p className="mt-3 whitespace-pre-wrap break-words text-sm text-gray-300">{data.plan.prompt || "Open the original result for the full task and any chart."}</p><p className="mt-4 whitespace-pre-wrap break-words rounded-xl border border-white/10 p-4 text-sm leading-relaxed text-gray-200">{data.plan.original}</p></details><p className="mt-4 text-sm text-gray-400">Charts and retained recordings remain on the original result, with their existing access and retention rules.</p></section>
    </div>
    {!data.id && data.canWrite && <section className={panel}><h2 className="scroll-mt-20 text-lg font-semibold text-white">Turn feedback into progress</h2><p className="mt-2 text-sm text-gray-400">Start with a private draft. Submitted work is kept as evidence and reviewed by your teacher or an administrator.</p><button type="button" className={`${button} mt-4 border-averna-cyan/40 bg-averna-cyan/10`} disabled={busy} onClick={() => void request({ action: "START" })}><BookOpenCheck className="h-5 w-5" aria-hidden />Start practice cycle</button></section>}
    {showPractice && <PracticeForm key={`${data.id}-${editableKind}`} kind={editableKind} data={data} busy={busy} request={request} status={target === "practice" ? {error,notice} : undefined} />}
    {(step === "WAIT_REVISION" || step === "WAIT_TRANSFER") && <section className={panel}><h2 className="scroll-mt-20 flex items-center gap-2 text-lg font-semibold text-white"><ClipboardCheck className="h-5 w-5 text-averna-cyan" aria-hidden />Awaiting teacher feedback</h2><p className="mt-2 text-sm text-gray-400">{data.isOwner ? (data.hasAssignedTeacher ? "Your teacher was notified. Refresh here after the review." : "Your work is saved. There is no assigned group teacher; ask the centre for an administrator review.") : "The learner has submitted this response. Review the focus skills using quotes from their work."} The next practice step unlocks after review, not after an automatic score.</p></section>}
    {data.entries.filter(e => e.status === "SUBMITTED").map(e => <Evidence key={e.id} entry={e} data={data} busy={busy} request={request} status={target === e.id ? {error,notice} : undefined} />)}
    {step === "COMPLETE" && <section className={`${panel} border-averna-neon/30`}><h2 className="scroll-mt-20 flex items-center gap-2 text-lg font-semibold text-white"><CheckCircle2 className="h-5 w-5 text-averna-neon" aria-hidden />Your evidence is ready</h2><p className="mt-2 text-sm leading-relaxed text-gray-400">Both responses have feedback. “Demonstrated” applies to this response only — one exercise does not prove permanent mastery or a higher IELTS band.</p>{data.isOwner && <Link href="/progress/portfolio" className={`${button} mt-4`}>Open private portfolio <ArrowRight className="h-4 w-4" aria-hidden /></Link>}</section>}
    {!data.canWrite && !data.canReview && <p className="text-sm text-gray-400">This work is read-only for your account.</p>}
    <p className="text-sm text-gray-400">Drafts are private to the learner. Submitted work is visible to authorised group teachers and administrators. There is no public sharing link.</p>
  </div>;
}
function PracticeForm({ kind, data, busy, request, status }: { status?: {error:string;notice:string}; kind: EntryKind; data: CycleView; busy: boolean; request: (b: Record<string, unknown>) => Promise<boolean> }) {
  const saved = data.entries.find(e => e.kind === kind); const [body, setBody] = useState(saved?.body ?? (kind === "REVISION" ? data.plan.original : "")); const [reflection, setReflection] = useState(saved?.reflection ?? ""); const [version, setVersion] = useState(saved?.version ?? 0);
  useEffect(() => { if (saved?.body === body && saved.reflection === reflection) setVersion(saved.version); }, [saved?.version, saved?.body, saved?.reflection, body, reflection]);
  const stale = !!saved && saved.version !== version;
  const dirty = body !== (saved?.body ?? (kind === "REVISION" ? data.plan.original : "")) || reflection !== (saved?.reflection ?? "");
  useEffect(() => { if (!dirty) return; const warn = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  return <section className={panel}><h2 className="scroll-mt-20 text-lg font-semibold text-white">{kind === "REVISION" ? "Revise your response" : "Apply the skills to a different task"}</h2><p className="mt-2 text-sm leading-relaxed text-gray-400">{kind === "REVISION" ? "Keep the same task, apply the focus skills, and explain your changes. For charts, keep the original result open." : data.plan.transfer.note}</p>{kind === "TRANSFER" && <p className="mt-4 rounded-xl border border-averna-purple/30 bg-averna-purple/5 p-4 text-base leading-relaxed text-white">{data.plan.transfer.prompt}</p>}
    {stale && <p role="alert" className="mt-4 text-sm text-amber-200">A newer draft is saved. Copy your local text before reloading this page; it will not overwrite the saved version.</p>}
    <form className="mt-5 space-y-4" onSubmit={e => { e.preventDefault(); void request({ action: "SUBMIT", kind, body, reflection, version }); }}><fieldset disabled={busy} className="space-y-4"><label className="block text-sm font-medium text-gray-300">{kind === "REVISION" ? "Your revised response" : "Your response to the new task"}<textarea className={`${control} mt-2 min-h-64`} value={body} onChange={e => setBody(e.target.value)} maxLength={20000} required /></label><label className="block text-sm font-medium text-gray-300">What did you change or apply?<textarea className={`${control} mt-2 min-h-24`} value={reflection} onChange={e => setReflection(e.target.value)} maxLength={1500} placeholder="Name one change and why it helps the reader." required /></label><p className="text-sm text-gray-400">Saving a draft is private. Submitting shares this version with authorised staff and locks it as evidence.</p>{status&&<RequestStatus {...status}/>}<div className="flex flex-wrap gap-3"><button type="button" className={button} disabled={!body.trim() || stale} onClick={() => void request({ action: "SAVE_DRAFT", kind, body, reflection, version })}><Save className="h-4 w-4" aria-hidden />Save draft</button><button type="submit" disabled={stale} className={`${button} border-averna-cyan/40 bg-averna-cyan/10`}>{busy ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : <ArrowRight className="h-4 w-4" aria-hidden />}Submit for feedback</button></div></fieldset></form>
  </section>;
}
function Evidence({ entry, data, busy, request, status }: { status?: {error:string;notice:string}; entry: PracticeEntry; data: CycleView; busy: boolean; request: (b: Record<string, unknown>) => Promise<boolean> }) {
  const [comment, setComment] = useState(""); const [outcomes, setOutcomes] = useState<Record<string, { outcome: string; quote: string }>>({});
  return <section className={panel}><h2 className="scroll-mt-20 text-lg font-semibold text-white">{entry.kind === "REVISION" ? "Revision evidence" : "New-task evidence"}</h2><p className="mt-2 text-sm text-gray-400">{entry.review ? `Reviewed by ${entry.review.reviewerName} · ${entry.review.createdAt.slice(0, 10)}` : "Submitted · awaiting review"}</p><details className="mt-3"><summary className="flex min-h-11 cursor-pointer items-center text-sm text-averna-cyan">Read submitted response and reflection</summary><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-relaxed text-gray-200">{entry.body}</p><p className="mt-4 whitespace-pre-wrap break-words border-t border-white/10 pt-4 text-sm text-gray-400">Reflection: {entry.reflection}</p></details>
    {entry.review && <div className="mt-4 space-y-3">{entry.review.outcomes.map(o => <div key={o.key} className="rounded-xl border border-white/10 p-4"><h3 className="text-sm font-semibold text-white">{data.plan.goals.find(g => g.key === o.key)?.label} · {outcomeLabel[o.outcome]}</h3><blockquote className="mt-2 whitespace-pre-wrap break-words text-sm text-gray-300">“{o.quote}”</blockquote></div>)}<p className="whitespace-pre-wrap break-words text-sm leading-relaxed text-gray-200">{entry.review.comment}</p></div>}
    {status&&<RequestStatus {...status}/>}
    {data.canReview && !entry.review && <form className="mt-5 space-y-4" onSubmit={e => { e.preventDefault(); void request({ action: "REVIEW", entryId: entry.id, comment, outcomes: data.plan.goals.map(g => ({ key: g.key, ...outcomes[g.key] })) }); }}><fieldset disabled={busy} className="space-y-4"><legend className="mb-3 text-base font-semibold text-white">Review focus skills — not an IELTS re-band</legend>{data.plan.goals.map(g => <div key={g.key} className="grid gap-3 rounded-xl border border-white/10 p-4 sm:grid-cols-2"><label className="text-sm text-gray-300">{g.label}<select className={`${control} mt-2`} value={outcomes[g.key]?.outcome ?? ""} required onChange={e => setOutcomes({ ...outcomes, [g.key]: { quote: outcomes[g.key]?.quote ?? "", outcome: e.target.value } })}><option value="">Choose observation</option>{Object.entries(outcomeLabel).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="text-sm text-gray-300">Quote evidence from this response<textarea className={`${control} mt-2 min-h-24`} value={outcomes[g.key]?.quote ?? ""} maxLength={500} minLength={10} required onChange={e => setOutcomes({ ...outcomes, [g.key]: { outcome: outcomes[g.key]?.outcome ?? "", quote: e.target.value } })} /></label></div>)}<label className="block text-sm text-gray-300">Feedback and next action<textarea className={`${control} mt-2 min-h-24`} value={comment} maxLength={2000} minLength={10} required onChange={e => setComment(e.target.value)} /></label><p className="text-sm text-gray-400">Evidence must be quoted from the submitted response. This review is retained; it does not change exam bands or XP.</p><button type="submit" className={`${button} border-averna-cyan/40 bg-averna-cyan/10`}>Save practice feedback</button></fieldset></form>}
  </section>;
}

function RequestStatus({error,notice}:{error:string;notice:string}) {
  return <>{error&&<div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}{notice&&<p role="status" className="rounded-xl border border-averna-neon/30 p-4 text-sm text-averna-neon">{notice}</p>}</>;
}
