"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, ArrowRight, FileText, Headphones, Clock3 } from "lucide-react";
import { CASES, DEBATES, EPISODES, RESCUES, type Episode, type DetectiveCase } from "@/lib/adventures/catalog";
import { canAdvance, emptySession, sessionSchema } from "@/lib/adventures/rules";
import { useOwnedState } from "./use-owned-state";
import { LocalNotice, ReadAloud, ResetButton, ResponseBox } from "./primitives";

export function Series({ owner }: { owner: string }) {
  const [episodeId, setEpisodeId] = useState(EPISODES[0].id);
  const episode = EPISODES.find(item => item.id === episodeId) || EPISODES[0];
  return <><div className="adv-tabs" aria-label="Choose a chapter">{EPISODES.map(item => <button type="button" className="adv-button adv-secondary" aria-pressed={item.id === episode.id} key={item.id} onClick={() => setEpisodeId(item.id)}>{item.title}</button>)}</div><SeriesChapter key={`${owner}:${episode.id}`} owner={owner} episode={episode} /></>;
}
function SeriesChapter({ owner, episode }: { owner: string; episode: Episode }) {
  const { value, update, loaded, warning } = useOwnedState(owner, `series:${episode.id}`, emptySession, sessionSchema);
  const scene = episode.scenes[value.step] || episode.scenes[0];
  const finished = scene.choices.length === 0;
  function advance(next: string) {
    if (!canAdvance(value.draft)) return;
    const step = episode.scenes.findIndex(item => item.id === next);
    if (step < 0) return;
    update({ ...value, activity: episode.id, step, responses: [...value.responses, value.draft], draft: "", complete: episode.scenes[step].choices.length === 0 });
  }
  return <div className="adv-stack"><section className="adv-card"><p className="adv-kicker">Guided story · your choices change the next scene</p><h2>{episode.title}</h2><p className="adv-muted">{episode.setting}</p><div className="adv-dialogue"><p className="adv-kicker">{scene.speaker}</p><p>{scene.line}</p></div>{finished ? <><h3><CheckCircle2 size={20} /> A chapter worth remembering</h3><p>{scene.task}</p><p className="adv-note">You practised {value.responses.length} replies. No automatic language grade was calculated.</p><details className="adv-details"><summary>Your replies</summary>{value.responses.map((text, i) => <p key={i} className="adv-answer"><b>Reply {i + 1}</b><br />{text}</p>)}</details></> : <><h3>{scene.task}</h3><details className="adv-details"><summary>A little help</summary><p>{scene.tip}</p></details><ResponseBox value={value.draft} onChange={draft => update({ ...value, draft })} disabled={!loaded} /><p className="adv-note">Write or dictate at least six words, then choose what happens next. The story does not assess the meaning of your reply.</p><div className="adv-actions">{scene.choices.map(choice => <button type="button" key={choice.next} className="adv-button adv-primary" disabled={!loaded || !canAdvance(value.draft)} onClick={() => advance(choice.next)}>{choice.label}<ArrowRight size={18} /></button>)}</div></>}<ResetButton reset={() => update(emptySession())} /></section><LocalNotice warning={warning} /></div>;
}

export function Detective({ owner }: { owner: string }) {
  const [caseId, setCaseId] = useState(CASES[0].id); const file = CASES.find(item => item.id === caseId) || CASES[0];
  return <><div className="adv-tabs" aria-label="Choose a case">{CASES.map(item => <button key={item.id} type="button" className="adv-button adv-secondary" aria-pressed={item.id === file.id} onClick={() => setCaseId(item.id)}>{item.title}</button>)}</div><CaseFile key={`${owner}:${file.id}`} owner={owner} file={file} /></>;
}
function CaseFile({ owner, file }: { owner: string; file: DetectiveCase }) {
  const { value, update, loaded, warning } = useOwnedState(owner, `detective:${file.id}`, emptySession, sessionSchema);
  const allOpened = file.clues.every(clue => value.responses.includes(clue.id));
  return <div className="adv-stack"><section className="adv-card"><p className="adv-kicker">Case file · {value.responses.length}/{file.clues.length} clues opened</p><h2>{file.title}</h2><p className="adv-muted">{file.brief}</p><div className="adv-stack">{file.clues.map(clue => <details key={clue.id} className="adv-evidence" onToggle={event => { if (event.currentTarget.open && loaded && !value.responses.includes(clue.id)) update({ ...value, responses: [...new Set([...value.responses, clue.id])] }); }}><summary>{clue.type === "audio" ? <Headphones size={20} /> : <FileText size={20} />}{clue.title}<span className="adv-tag">{clue.type}</span></summary>{clue.type === "audio" ? <><p className="adv-note">Prepared voice-note text, read by your browser. You can use the transcript if audio is unavailable.</p><ReadAloud text={clue.text} /><details className="adv-details"><summary>Show transcript</summary><p>{clue.text}</p></details></> : <p>{clue.text}</p>}</details>)}</div><fieldset className="adv-options"><legend>What is your conclusion?</legend>{file.options.map((option, index) => <label key={option}><input type="radio" name={`case-${file.id}`} checked={value.choice === index} disabled={value.complete || !loaded} onChange={() => update({ ...value, choice: index })} /><span>{option}</span></label>)}</fieldset><ResponseBox label="Explain your evidence" value={value.draft} disabled={!loaded || value.complete} onChange={draft => update({ ...value, draft })} />{value.complete ? <div className="adv-feedback" role="status"><h3>{value.choice === file.answer ? "Your conclusion matches the evidence" : "Revisit the connection between the clues"}</h3><p>{file.explanation}</p><p className="adv-note">The answer key checks your selected conclusion, not the quality of your written explanation.</p></div> : <><p className="adv-note">Open every clue and write at least six words about the evidence.</p><button type="button" className="adv-button adv-primary" disabled={!loaded || !allOpened || value.choice < 0 || !canAdvance(value.draft)} onClick={() => update({ ...value, complete: true })}>Check my conclusion <ArrowRight size={18} /></button></>}<ResetButton reset={() => update(emptySession())} /></section><LocalNotice warning={warning} /></div>;
}

export function Debate({ owner }: { owner: string }) {
  const [topicId, setTopicId] = useState<string>(DEBATES[0].id); const [side, setSide] = useState<"for" | "against">("for"); const topic = DEBATES.find(item => item.id === topicId) || DEBATES[0];
  return <><div className="adv-card adv-selector"><label htmlFor="debate-topic">Choose a motion</label><select id="debate-topic" value={topic.id} onChange={e => setTopicId(e.target.value)}>{DEBATES.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><div className="adv-tabs" aria-label="Choose your position">{(["for", "against"] as const).map(position => <button key={position} type="button" className="adv-button adv-secondary" aria-pressed={position === side} onClick={() => setSide(position)}>Argue {position}</button>)}</div></div><DebateRounds key={`${owner}:${topic.id}:${side}`} owner={owner} topic={topic} side={side} switchSide={() => setSide(side === "for" ? "against" : "for")} /></>;
}
function DebateRounds({ owner, topic, side, switchSide }: { owner: string; topic: typeof DEBATES[number]; side: "for" | "against"; switchSide: () => void }) {
  const { value, update, loaded, warning } = useOwnedState(owner, `debate:${topic.id}:${side}`, emptySession, sessionSchema);
  const step = Math.min(value.step, 2); const rounds = topic[side];
  return <div className="adv-stack"><section className="adv-card"><p className="adv-kicker">Guided opponent · prepared challenges, not live AI</p><h2>{topic.title}</h2>{value.complete ? <><h3>Now try the other side</h3><p>Look for the strongest argument you would need to answer, not the easiest one.</p><div className="adv-stack">{value.responses.map((response, i) => <article className="adv-answer" key={i}><h3>Round {i + 1}</h3><p className="adv-muted">{rounds[i]}</p><p>{response}</p></article>)}</div><fieldset className="adv-options"><legend>Reflect on your argument</legend>{["I made a clear claim", "I used a specific example", "I answered a counterargument"].map(text => <label key={text}><input type="checkbox" /><span>{text}</span></label>)}</fieldset><button type="button" className="adv-button adv-primary" onClick={switchSide}>Switch sides <ArrowRight size={18} /></button></> : <><div className="adv-progress" aria-label={`Round ${step + 1} of 3`}>{[0, 1, 2].map(index => <span key={index} data-active={index <= step}>Round {index + 1}</span>)}</div><div className="adv-dialogue"><p className="adv-kicker">{step === 0 ? `Opening · argue ${side}` : "Your challenger asks"}</p><p>{rounds[step]}</p><ReadAloud text={rounds[step]} /></div><p className="adv-note">{topic.example}</p><ResponseBox value={value.draft} onChange={draft => update({ ...value, draft })} disabled={!loaded} /><button type="button" className="adv-button adv-primary" disabled={!loaded || !canAdvance(value.draft)} onClick={() => update({ ...value, responses: [...value.responses, value.draft], step: step + 1, draft: "", complete: step === 2 })}>{step === 2 ? "Review my argument" : "Next challenge"}<ArrowRight size={18} /></button></>}<ResetButton reset={() => update(emptySession())} /></section><LocalNotice warning={warning} /></div>;
}

export function Rescue({ owner }: { owner: string }) {
  const [scenarioId, setScenarioId] = useState<string>(RESCUES[0].id); const scenario = RESCUES.find(item => item.id === scenarioId) || RESCUES[0];
  return <><div className="adv-tabs" aria-label="Choose a situation">{RESCUES.map(item => <button key={item.id} type="button" className="adv-button adv-secondary" aria-pressed={item.id === scenario.id} onClick={() => setScenarioId(item.id)}>{item.title}</button>)}</div><RescueRounds key={`${owner}:${scenario.id}`} owner={owner} scenario={scenario} /></>;
}
function RescueRounds({ owner, scenario }: { owner: string; scenario: typeof RESCUES[number] }) {
  const { value, update, loaded, warning } = useOwnedState(owner, `rescue:${scenario.id}`, emptySession, sessionSchema);
  const [timed, setTimed] = useState(false); const [seconds, setSeconds] = useState(45);
  useEffect(() => { setSeconds(45); }, [value.step]);
  useEffect(() => {
    if (!timed || value.complete || seconds <= 0) return;
    const interval = setInterval(() => setSeconds(previous => Math.max(0, previous - 1)), 1000);
    return () => clearInterval(interval);
  }, [timed, value.complete, seconds]);
  useEffect(() => { const pause = () => { if (document.hidden) setTimed(false); }; document.addEventListener("visibilitychange", pause); return () => document.removeEventListener("visibilitychange", pause); }, []);
  const step = Math.min(value.step, 2); const usedForbidden = new RegExp(`\\b(${scenario.forbidden})s?\\b`, "i").test(value.draft);
  return <div className="adv-stack"><section className="adv-card"><p className="adv-kicker">Three replies · no penalty for taking your time</p><h2>{scenario.title}</h2><p className="adv-callout">{scenario.constraint}</p>{value.complete ? <><h3>You worked through the situation</h3>{value.responses.map((response, i) => <article className="adv-answer" key={i}><h3>Reply {i + 1}</h3><p>{response}</p></article>)}<p className="adv-note">Reflect: did your final reply make the next action clear? No automatic judgement of politeness or accuracy was made.</p></> : <><div className="adv-actions"><button type="button" className="adv-button adv-secondary" aria-pressed={timed} onClick={() => { if (!timed && seconds === 0) setSeconds(45); setTimed(!timed); }}><Clock3 size={18} />{timed ? "Pause timer" : "Use optional timer"}</button><span className="adv-tag">{timed ? `${seconds}s` : "No timer pressure"}</span></div>{seconds === 0 && <p role="status" className="adv-note">Time is up, but your response is safe. Continue when you are ready.</p>}<div className="adv-dialogue"><p className="adv-kicker">Turn {step + 1} of 3</p><p>{scenario.rounds[step]}</p></div><details className="adv-details"><summary>Useful phrases</summary><p>{scenario.useful}</p></details><ResponseBox value={value.draft} onChange={draft => update({ ...value, draft })} disabled={!loaded} />{usedForbidden && <p className="adv-note" role="status">The response includes a restricted word. Try describing it another way; you can still continue.</p>}<button type="button" className="adv-button adv-primary" disabled={!loaded || !canAdvance(value.draft)} onClick={() => update({ ...value, responses: [...value.responses, value.draft], step: step + 1, draft: "", complete: step === 2 })}>{step === 2 ? "Reflect on my replies" : "Reveal the twist"}<ArrowRight size={18} /></button></>}<ResetButton reset={() => { setTimed(false); setSeconds(45); update(emptySession()); }} /></section><LocalNotice warning={warning} /></div>;
}
