"use client";
import Link from "next/link";
import { useRef, useState } from "react";
import { ArrowRight, BookOpenCheck, ShieldCheck } from "lucide-react";
import type { CalibrationView } from "@/lib/teacher-tools/calibration";
import { criteria, criterionNames } from "@/lib/teacher-tools/rules";
import { button, control, panel, Status, useDirtyWarning, useTool } from "./shared";
type Values = Record<string, string>;
const emptyScores = () => Object.fromEntries(criteria.map(key => [key, ""]));
const numeric = (values: Values) => Object.fromEntries(criteria.map(key => [key, values[key] === "" ? null : Number(values[key])]));
function ScoreFields({ values, setValues }: { values: Values; setValues: (values: Values) => void }) { return <div className="grid gap-4 sm:grid-cols-2">{criteria.map(key => <label key={key} className="block text-sm text-gray-300">{criterionNames[key]}<select className={`${control} mt-2`} value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })} required><option value="">Choose a criterion band</option>{Array.from({ length: 19 }, (_, i) => i / 2).map(n => <option key={n} value={n}>{n.toFixed(1)}</option>)}</select></label>)}</div>; }
export function Calibration({ initial }: { initial: CalibrationView }) {
  const tool = useTool(initial, `/api/calibration?${new URLSearchParams({ page: String(initial.page), ...(initial.selected ? { reference: initial.selected.id } : {}) })}`); const v = tool.view;
  if (tool.unavailable) return <section className={panel}><h1 className="text-2xl font-bold text-white">Calibration unavailable</h1><Status error={tool.error} notice="" /><button className={`${button} mt-4`} disabled={tool.busy} onClick={() => void tool.request()}>Retry access</button></section>;
  return <div className="space-y-6"><header><p className="flex items-center gap-2 text-sm font-semibold text-averna-cyan"><ShieldCheck className="h-5 w-5" aria-hidden />Private professional practice</p><h1 className="mt-3 text-3xl font-bold text-white">Assessment calibration</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-gray-400">Assess a centre-agreed Writing reference before seeing its criteria. Compare reasoning, not teacher rankings. This does not certify IELTS examiner accuracy or alter learner grades.</p></header>
    {tool.target === "GLOBAL" && <Status error={tool.error} notice={tool.notice} />}
    <section className={panel}><h2 className="text-xl font-semibold text-white">Reference library</h2>{v.items.length === 0 ? <div className="mt-4 space-y-3"><BookOpenCheck className="h-8 w-8 text-averna-cyan" aria-hidden /><p className="text-gray-200">No centre-agreed references yet.</p><p className="text-sm text-gray-400">An administrator must publish anonymised or synthetic examples with agreed criterion scores and reasoning. There are no invented “official” benchmarks.</p></div> : <ul className="mt-4 grid gap-3 sm:grid-cols-2">{v.items.map(item => <li key={item.id}><Link href={`/teacher/calibration?reference=${item.id}&page=${v.page}`} aria-current={v.selected?.id === item.id ? "page" : undefined} className={`block min-h-11 rounded-xl border p-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-averna-cyan ${v.selected?.id === item.id ? "border-averna-cyan/50 bg-averna-cyan/5" : "border-white/15"}`}><span className="break-words font-medium text-white">{item.title}</span><span className="mt-2 block text-sm text-gray-400">Writing {item.module === "TASK1" ? "Task 1" : "Task 2"} · {item.completed ? "Comparison available" : "Blind practice"}</span></Link></li>)}</ul>}<div className="mt-4 flex flex-wrap gap-3">{v.page > 1 && <Link className={button} href={`/teacher/calibration?page=${v.page - 1}`}>Previous</Link>}{v.hasMore && <Link className={button} href={`/teacher/calibration?page=${v.page + 1}`}>Next references</Link>}</div></section>
    {v.selected && <section className={panel}><h2 className="break-words text-2xl font-semibold text-white">{v.selected.title}</h2><p className="mt-2 text-sm text-gray-400">Centre reference, not an official IELTS benchmark. Writing only in this release; Speaking needs properly reviewed audio.</p><div className="mt-5 rounded-xl border border-white/15 p-4"><h3 className="font-semibold text-white">Task</h3><p className="mt-3 whitespace-pre-wrap break-words text-gray-300">{v.selected.prompt}</p></div><div className="mt-4 rounded-xl border border-white/15 p-4"><h3 className="font-semibold text-white">Reference response</h3><p className="mt-3 max-w-3xl whitespace-pre-wrap break-words text-gray-200">{v.selected.body}</p></div>
      {v.selected.own && v.selected.reference ? <>{tool.target === "RATE" && <Status error={tool.error} notice={tool.notice} />}<h3 className="mt-6 text-xl font-semibold text-white">Compare criteria and discuss</h3><p className="mt-2 text-sm text-gray-400">Signed difference = your criterion band minus the centre reference. Differences invite discussion; no overall “teacher score” is calculated.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{v.selected.reference.comparison.map(row => <div key={row.key} className="rounded-xl border border-white/15 p-4"><h4 className="font-medium text-white">{row.label}</h4><dl className="mt-4 grid grid-cols-3 gap-3 text-sm"><div><dt className="text-gray-400">Yours</dt><dd className="mt-1 text-lg font-semibold text-white">{row.own.toFixed(1)}</dd></div><div><dt className="text-gray-400">Reference</dt><dd className="mt-1 text-lg font-semibold text-white">{row.reference.toFixed(1)}</dd></div><div><dt className="text-gray-400">Difference</dt><dd className="mt-1 text-lg font-semibold text-white">{row.difference > 0 ? "+" : ""}{row.difference.toFixed(1)}</dd></div></dl></div>)}</div><div className="mt-5 space-y-4"><div><h4 className="font-semibold text-white">Your quoted evidence</h4><p className="mt-2 whitespace-pre-wrap break-words text-gray-300">“{v.selected.own.quote}”</p></div><div><h4 className="font-semibold text-white">Your reasoning</h4><p className="mt-2 whitespace-pre-wrap break-words text-gray-300">{v.selected.own.rationale}</p></div><div><h4 className="font-semibold text-white">Centre-agreed rationale</h4><p className="mt-2 whitespace-pre-wrap break-words text-gray-300">{v.selected.reference.rationale}</p></div></div><p className="mt-5 text-sm text-gray-400">Your first assessment is retained privately to avoid hindsight changes. No other staff member’s ratings are shown.</p></> : v.selected.canRate ? <BlindRating key={v.selected.id} selected={v.selected} busy={tool.busy} request={tool.request} error={tool.target === "RATE" ? tool.error : ""} notice={tool.target === "RATE" ? tool.notice : ""} /> : <p className="mt-5 rounded-xl border border-white/15 p-4 text-gray-300">You authored this reference. Choose one published by another administrator for blind practice.</p>}
    </section>}
    {v.admin && <PublishReference busy={tool.busy} request={tool.request} error={tool.target === "CREATE_REFERENCE" ? tool.error : ""} notice={tool.target === "CREATE_REFERENCE" ? tool.notice : ""} />}
  </div>;
}
function BlindRating({ selected, busy, request, error, notice }: { selected: NonNullable<CalibrationView["selected"]>; busy: boolean; request: (cmd?: Record<string, unknown>) => Promise<boolean>; error: string; notice: string }) {
  const [values, setValues] = useState<Values>(emptyScores), [quote, setQuote] = useState(""), [rationale, setRationale] = useState(""); useDirtyWarning(!!quote || !!rationale || Object.values(values).some(Boolean));
  return <form className="mt-6 space-y-4" onSubmit={e => { e.preventDefault(); void request({ action: "RATE", referenceId: selected.id, scores: numeric(values), quote, rationale }); }}><fieldset disabled={busy} className="space-y-5"><legend className="mb-4 text-xl font-semibold text-white">Commit your independent assessment</legend><ScoreFields values={values} setValues={setValues} /><label className="block text-sm text-gray-300">Quote evidence from this response<textarea className={`${control} mt-2 min-h-24`} value={quote} onChange={e => setQuote(e.target.value)} required minLength={10} maxLength={500} /></label><label className="block text-sm text-gray-300">Explain your criterion judgments<textarea className={`${control} mt-2 min-h-32`} value={rationale} onChange={e => setRationale(e.target.value)} required minLength={20} maxLength={2000} /></label><p className="text-sm text-gray-400">Saving locks your first assessment, then reveals the comparison. This is private staff practice, not a learner review.</p><Status error={error} notice={notice} /><button type="submit" className={button}>{busy ? "Saving…" : "Save & compare"}<ArrowRight className="h-4 w-4" aria-hidden /></button></fieldset></form>;
}
function PublishReference({ busy, request, error, notice }: { busy: boolean; request: (cmd?: Record<string, unknown>) => Promise<boolean>; error: string; notice: string }) {
  const [values, setValues] = useState<Values>(emptyScores), [title, setTitle] = useState(""), [module, setModule] = useState("TASK2"), [prompt, setPrompt] = useState(""), [body, setBody] = useState(""), [rationale, setRationale] = useState(""), [confirmed, setConfirmed] = useState(false); const operation = useRef<string>(); useDirtyWarning(!!title || !!prompt || !!body || !!rationale || Object.values(values).some(Boolean));
  return <section className={panel}><h2 className="text-xl font-semibold text-white">Publish a centre-agreed reference</h2><p className="mt-2 text-sm text-gray-400">Administrator only. Use synthetic or properly anonymised material. Agree each criterion and its rationale with your academic lead first. Published references are immutable in this release.</p><form className="mt-5 space-y-4" onSubmit={async e => { e.preventDefault(); operation.current ??= crypto.randomUUID(); if (await request({ action: "CREATE_REFERENCE", operationId: operation.current, title, module, prompt, body, scores: numeric(values), rationale, confirmed })) { operation.current = undefined; setTitle(""); setPrompt(""); setBody(""); setRationale(""); setValues(emptyScores()); setConfirmed(false); } }}><fieldset disabled={busy} className="space-y-4"><label className="block text-sm text-gray-300">Reference title<input className={`${control} mt-2`} value={title} onChange={e => setTitle(e.target.value)} required minLength={3} maxLength={120} /></label><label className="block text-sm text-gray-300">Writing task<select className={`${control} mt-2`} value={module} onChange={e => setModule(e.target.value)}><option value="TASK1">Task 1 · include all source data in the task</option><option value="TASK2">Task 2</option></select></label><label className="block text-sm text-gray-300">Complete task and source data<textarea className={`${control} mt-2 min-h-24`} value={prompt} onChange={e => setPrompt(e.target.value)} required minLength={20} maxLength={3000} /></label><label className="block text-sm text-gray-300">Anonymised / synthetic response<textarea className={`${control} mt-2 min-h-48`} value={body} onChange={e => setBody(e.target.value)} required minLength={100} maxLength={20000} /></label><ScoreFields values={values} setValues={setValues} /><label className="block text-sm text-gray-300">Agreed reasoning for all four criteria<textarea className={`${control} mt-2 min-h-32`} value={rationale} onChange={e => setRationale(e.target.value)} required minLength={30} maxLength={4000} /></label><label className="flex min-h-11 items-start gap-3 text-sm text-gray-300"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} required className="mt-1 h-4 w-4 shrink-0" />I confirm the criteria are agreed by the centre and this material contains no identifying learner information.</label><Status error={error} notice={notice} /><button type="submit" className={button}>Publish reference</button></fieldset></form></section>;
}
