"use client";
import { useRef, useState } from "react";
import { ArrowRight, CheckCircle2, Lightbulb, MessageSquare, RefreshCw, Users } from "lucide-react";
import { signalNames, type SignalKind } from "@/lib/teacher-tools/rules";
import type { ClassroomView } from "@/lib/teacher-tools/classroom";
import { button, control, panel, Status, useDirtyWarning, useTool } from "./shared";
const signalIcons = { UNDERSTOOD: CheckCircle2, EXAMPLE: Lightbulb, QUESTION: MessageSquare };
export function Classroom({ initial }: { initial: ClassroomView }) {
  const { view, busy, error, notice, unavailable, request, target } = useTool(initial, `/api/classroom?group=${encodeURIComponent(initial.groupId)}`, true);
  const [topic, setTopic] = useState(""), [confirmClose, setConfirmClose] = useState(false), [filter, setFilter] = useState("all"); const operation = useRef<string>();
  const start = async () => { operation.current ??= crypto.randomUUID(); if (await request({ action: "START", groupId: view.groupId, topic, operationId: operation.current })) { operation.current = undefined; setTopic(""); } };
  useDirtyWarning(topic.trim().length > 0);
  const command = (action: string, extra: Record<string, unknown> = {}) => request({ action, groupId: view.groupId, sessionId: view.session?.id, ...extra });
  if (unavailable) return <section className={panel}><h2 className="text-xl font-semibold text-white">Classroom unavailable</h2><Status error={error} notice="" /><button className={`${button} mt-4`} disabled={busy} onClick={() => void request()}>Retry access</button></section>;
  const open = view.session?.status === "OPEN"; const noSignal = view.rosterCount - Object.values(view.counts).reduce((a, b) => a + b, 0);
  return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-averna-cyan">{view.staff ? "Live classroom · staff view" : "Your live lesson"}</p><h1 className="mt-2 break-words text-3xl font-bold text-white">{view.groupName}</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed text-gray-400">Signals help your teacher adjust the lesson. Short checks are practice, not marks, XP or attendance.</p></div><button className={button} disabled={busy} onClick={() => void request()}><RefreshCw className="h-4 w-4" aria-hidden />{busy ? "Updating…" : "Refresh"}</button></header>
    <p className="text-sm text-gray-400">Updates about every 8 seconds while this page is visible. Last snapshot {new Date(view.capturedAt).toLocaleTimeString()}. This is not a connection or presence tracker.</p>{["GLOBAL", "START", "CLOSE"].includes(target) && <Status error={error} notice={notice} />}
    {!open && <section className={panel}><h2 className="text-xl font-semibold text-white">{view.session ? "Lesson closed" : "No lesson is open"}</h2><p className="mt-2 text-sm text-gray-400">{view.staff ? "Start a lesson for this group. Learners join from their Class page; no public room code is needed." : "Wait for your teacher to start a lesson, then refresh. Only your assigned group can participate."}</p>{view.staff && <form className="mt-5 space-y-4" onSubmit={e => { e.preventDefault(); void start(); }}><fieldset disabled={busy} className="space-y-4"><label className="block text-sm text-gray-300">Lesson topic<input className={`${control} mt-2`} value={topic} onChange={e => setTopic(e.target.value)} required minLength={3} maxLength={160} placeholder="e.g. Clear topic sentences" /></label><button className={`${button} bg-averna-cyan/10`} type="submit">Start lesson <ArrowRight className="h-4 w-4" aria-hidden /></button></fieldset></form>}</section>}
    {view.session && <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="break-words text-xl font-semibold text-white">{view.session.topic}</h2><span className="rounded-lg border border-white/20 px-3 py-2 text-sm text-gray-300">{open ? "Open for participation" : "Read-only · closed"}</span></div>{view.staff && open && <div className="mt-4">{confirmClose ? <div className="space-y-3 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4"><p className="text-sm text-gray-200">Close this lesson and its current check? Learners can no longer send signals or answers.</p><div className="flex flex-wrap gap-3"><button className={button} disabled={busy} onClick={async () => { if (await command("CLOSE")) setConfirmClose(false); }}>Confirm close</button><button className={button} disabled={busy} onClick={() => setConfirmClose(false)}>Keep open</button></div></div> : <button className={button} disabled={busy} onClick={() => setConfirmClose(true)}>End lesson</button>}</div>}</section>}
    {!view.staff && view.session && <Signals view={view} busy={busy} command={command} status={target === "SIGNAL" ? { error, notice } : undefined} />}
    {view.staff && view.session && <><section className={panel}><h2 className="flex items-center gap-2 text-xl font-semibold text-white"><Users className="h-5 w-5 text-averna-cyan" aria-hidden />Group pulse</h2><p className="mt-2 text-sm text-gray-400">Latest signal per learner in this lesson. No signal is not a judgment about understanding.</p><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{Object.entries(signalNames).map(([key, label]) => <div key={key} className="rounded-xl border border-white/15 p-4"><p className="text-2xl font-bold text-white">{view.counts[key as SignalKind]}</p><p className="mt-2 text-sm text-gray-300">{label}</p></div>)}<div className="rounded-xl border border-white/15 p-4"><p className="text-2xl font-bold text-white">{noSignal}</p><p className="mt-2 text-sm text-gray-300">No signal yet</p></div></div></section>
      <section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold text-white">Learner signals</h2><label className="text-sm text-gray-300">Show<select className={`${control} mt-2`} value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All learners</option><option value="QUESTION">Questions</option><option value="EXAMPLE">Need an example</option></select></label></div><p className="mt-3 text-sm text-gray-400">Named signals are visible only to authorised staff. They are not anonymous or automatically sent to parents.</p><ul className="mt-5 space-y-3">{view.signals.filter(s => filter === "all" || s.kind === filter).map(s => <li key={s.studentId} className="rounded-xl border border-white/15 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="break-words font-medium text-white">{s.name}</p><span className="text-sm text-gray-300">{s.kind ? signalNames[s.kind] : "No signal yet"}</span></div>{s.question && <p className="mt-3 whitespace-pre-wrap break-words text-gray-200">{s.question}</p>}{view.poll && <p className="mt-3 text-sm text-gray-400">Current check: {s.answered ? "Answered" : "Not answered"}</p>}</li>)}</ul>{view.signals.filter(s => filter === "all" || s.kind === filter).length === 0 && <p className="mt-5 text-gray-400">No learners match this view.</p>}</section></>}
    {view.poll && <Check key={view.poll.id} view={view} busy={busy} command={command} status={["ANSWER", "CLOSE_POLL"].includes(target) ? { error, notice } : undefined} />}
    {view.staff && view.session && <PublishCheck blocked={!open || view.poll?.status === "OPEN"} busy={busy} command={command} status={target === "PUBLISH_POLL" ? { error, notice } : undefined} />}
    {!view.canWrite && <p role="status" className="rounded-xl border border-amber-400/30 p-4 text-sm text-amber-200">Participation is read-only for this account. Contact the centre if you need help.</p>}
  </div>;
}
function Signals({ view, busy, command, status }: { status?: { error: string; notice: string }; view: ClassroomView; busy: boolean; command: (action: string, extra?: Record<string, unknown>) => Promise<boolean> }) {
  const initialLesson = useRef(view.session?.id);
  const [kind, setKind] = useState<SignalKind>(view.ownSignal?.kind ?? "UNDERSTOOD"), [question, setQuestion] = useState(view.ownSignal?.question ?? ""), [sending, setSending] = useState(false); useDirtyWarning(question !== (view.ownSignal?.question ?? ""));
  return <section className={panel}><h2 className="text-xl font-semibold text-white">How is the lesson going?</h2><p className="mt-2 text-sm text-gray-400">Your name and question are visible to your teacher, not to other learners.</p>{initialLesson.current !== view.session?.id && <p className="mt-3 text-sm text-amber-200">The lesson changed. Your unsent question is kept; check the new topic before sending.</p>}<form className="mt-5 space-y-4" onSubmit={async e => { e.preventDefault(); setSending(true); await command("SIGNAL", { kind, question, version: view.ownSignal?.version ?? 0 }); setSending(false); }}><fieldset className="space-y-4" disabled={busy || !view.canWrite || view.session?.status !== "OPEN"}><legend className="sr-only">Choose your signal</legend><div className="grid gap-3 sm:grid-cols-3">{Object.entries(signalNames).map(([key, label]) => { const Icon = signalIcons[key as SignalKind]; return <button type="button" key={key} aria-pressed={kind === key} onClick={() => setKind(key as SignalKind)} className={`${button} ${kind === key ? "border-averna-cyan/50 bg-averna-cyan/10" : ""}`}><Icon className="h-5 w-5 shrink-0" aria-hidden />{label}</button>; })}</div>{kind === "QUESTION" && <label className="block text-sm text-gray-300">Your question<textarea className={`${control} mt-2 min-h-24`} value={question} onChange={e => setQuestion(e.target.value)} required minLength={3} maxLength={500} /></label>}{status && <Status {...status} />}<button className={button} type="submit">{sending ? "Sending…" : "Send signal"}</button></fieldset></form>{view.ownSignal && <p className="mt-4 text-sm text-averna-cyan">Saved signal: {signalNames[view.ownSignal.kind]}</p>}</section>;
}
function Check({ view, busy, command, status }: { status?: { error: string; notice: string }; view: ClassroomView; busy: boolean; command: (action: string, extra?: Record<string, unknown>) => Promise<boolean> }) {
  const p = view.poll!; const [option, setOption] = useState<number | null>(null); const open = p.status === "OPEN" && view.session?.status === "OPEN";
  return <section className={panel}><h2 className="text-xl font-semibold text-white">Quick understanding check</h2><p className="mt-3 whitespace-pre-wrap break-words text-lg text-white">{p.prompt}</p><p className="mt-2 text-sm text-gray-400">One saved answer per check. The explanation is revealed to learners when the teacher closes it.</p><form className="mt-5 space-y-4" onSubmit={e => { e.preventDefault(); if (option !== null) void command("ANSWER", { pollId: p.id, option }); }}><fieldset disabled={busy || view.staff || !open || !view.canWrite || p.ownAnswer !== null} className="space-y-3"><legend className="sr-only">Answer options</legend>{p.options.map((label, i) => <label key={i} className="flex min-h-11 items-start gap-3 rounded-xl border border-white/20 p-4 text-gray-200"><input type="radio" name={`poll-${p.id}`} required checked={(p.ownAnswer ?? option) === i} onChange={() => setOption(i)} className="mt-1 h-4 w-4 shrink-0" /><span className="break-words">{label}{(view.staff || !open) && <span className="mt-2 block text-sm text-gray-400">{p.answers[i] ?? 0} answers {p.correct === i ? "· Correct option" : ""}</span>}</span></label>)}{status && <Status {...status} />} {!view.staff && open && p.ownAnswer === null && <button type="submit" className={button}>Save answer</button>}</fieldset></form>{p.ownAnswer !== null && <p className="mt-4 text-sm text-averna-cyan">Your answer is saved.</p>}{view.staff && <p className="mt-4 text-sm text-gray-400">{p.responseCount} / {view.rosterCount} current group learners answered.</p>}{view.staff && open && <button className={`${button} mt-4`} disabled={busy} onClick={() => void command("CLOSE_POLL", { pollId: p.id })}>Close check & reveal explanation</button>}{p.explanation && <div className="mt-5 rounded-xl border border-averna-cyan/30 bg-averna-cyan/5 p-4"><p className="font-medium text-white">{view.staff && open ? "Teacher-only explanation" : "Discuss the answer"}</p><p className="mt-2 whitespace-pre-wrap break-words text-gray-300">{p.explanation}</p></div>}</section>;
}
function PublishCheck({ busy, command, status, blocked }: { blocked: boolean; status?: { error: string; notice: string }; busy: boolean; command: (action: string, extra?: Record<string, unknown>) => Promise<boolean> }) {
  const [prompt, setPrompt] = useState(""), [options, setOptions] = useState(["", ""]), [correct, setCorrect] = useState(0), [explanation, setExplanation] = useState(""); const operation = useRef<string>(); useDirtyWarning(!!prompt.trim() || options.some(v => !!v.trim()) || !!explanation.trim());
  return <section className={panel}><h2 className="text-xl font-semibold text-white">Prepare a short check</h2><p className="mt-2 text-sm text-gray-400">Teacher-authored, 2–4 choices. No automatic grade or AI request.</p>{blocked && <p className="mt-3 text-sm text-amber-200">Close the current check, or start a new lesson, before publishing. Any unsent draft stays in this tab.</p>}<form className="mt-5 space-y-4" onSubmit={async e => { e.preventDefault(); operation.current ??= crypto.randomUUID(); if (await command("PUBLISH_POLL", { prompt, options, correct, explanation, operationId: operation.current })) { operation.current = undefined; setPrompt(""); setOptions(["", ""]); setCorrect(0); setExplanation(""); } }}><fieldset disabled={busy || blocked} className="space-y-4"><label className="block text-sm text-gray-300">Question<textarea className={`${control} mt-2`} value={prompt} onChange={e => setPrompt(e.target.value)} required minLength={5} maxLength={600} /></label>{options.map((option, i) => <label key={i} className="block text-sm text-gray-300">Option {i + 1}<input className={`${control} mt-2`} value={option} onChange={e => setOptions(options.map((v, j) => j === i ? e.target.value : v))} required maxLength={200} /></label>)}<div className="flex flex-wrap gap-3">{options.length < 4 && <button type="button" className={button} onClick={() => setOptions([...options, ""])}>Add option</button>}{options.length > 2 && <button type="button" className={button} onClick={() => { setOptions(options.slice(0, -1)); setCorrect(0); }}>Remove last option</button>}</div><label className="block text-sm text-gray-300">Correct option<select className={`${control} mt-2`} value={correct} onChange={e => setCorrect(Number(e.target.value))}>{options.map((_, i) => <option key={i} value={i}>Option {i + 1}</option>)}</select></label><label className="block text-sm text-gray-300">Explanation for discussion<textarea className={`${control} mt-2 min-h-24`} value={explanation} onChange={e => setExplanation(e.target.value)} required minLength={10} maxLength={1200} /></label>{status && <Status {...status} />}<button type="submit" className={button}>Publish check</button></fieldset></form></section>;
}
