import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { ConfirmedAction } from "@/components/admin/confirmed-action";
afterEach(cleanup);
function setup(action = vi.fn().mockResolvedValue(undefined)) { render(<ConfirmedAction action={action} fields={{id:"r",action:"remove"}} title="Remove gift?" description="Existing requests are kept." />);return action; }
describe("confirmed destructive action", () => {
  it("requires explicit confirmation; cancelling never calls the server",async()=>{const action=setup();fireEvent.click(screen.getByRole("button",{name:"Oʻchirish"}));const dialog=screen.getByRole("dialog",{name:"Remove gift?"});expect(within(dialog).getByText("Existing requests are kept.")).toBeTruthy();fireEvent.click(within(dialog).getByRole("button",{name:"Bekor qilish"}));expect(action).not.toHaveBeenCalled();await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());});
  it("submits the exact ID and action and closes only after success",async()=>{const action=setup();fireEvent.click(screen.getByRole("button",{name:"Oʻchirish"}));fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Oʻchirish"}));await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());expect(action.mock.calls[0][0].get("id")).toBe("r");expect(action.mock.calls[0][0].get("action")).toBe("remove");});
  it("guards rapid duplicate submits and cannot close while pending",async()=>{let resolve:()=>void=()=>{};const action=setup(vi.fn(()=>new Promise<void>(r=>{resolve=r})));fireEvent.click(screen.getByRole("button",{name:"Oʻchirish"}));const dialog=screen.getByRole("dialog");const form=dialog.querySelector("form")!;fireEvent.submit(form);fireEvent.submit(form);expect(action).toHaveBeenCalledTimes(1);expect((within(dialog).getByRole("button",{name:"Bekor qilish"}) as HTMLButtonElement).disabled).toBe(true);resolve();await waitFor(()=>expect(screen.queryByRole("dialog")).toBeNull());});
  it("shows retry feedback without exposing server errors",async()=>{const action=setup(vi.fn().mockRejectedValue(new Error("private database detail")));fireEvent.click(screen.getByRole("button",{name:"Oʻchirish"}));fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Oʻchirish"}));expect(await screen.findByRole("alert")).toBeTruthy();expect(screen.queryByText("private database detail")).toBeNull();expect((within(screen.getByRole("dialog")).getByRole("button",{name:"Oʻchirish"}) as HTMLButtonElement).disabled).toBe(false);});
});
