import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,beforeEach,describe,expect,it,vi } from "vitest";
import { formatUzs } from "@/lib/finance/rules";
import { webcrypto } from "node:crypto";
import { FinanceCenter } from "@/components/admin/finance/finance-center";
import { financeFixture } from "./fixtures/finance";
const response=(body:unknown,status=200)=>({ok:status<400,json:async()=>body});
describe("finance admin workspace",()=>{
 beforeEach(()=>{sessionStorage.clear();Object.defineProperty(globalThis,"crypto",{value:webcrypto,configurable:true});HTMLElement.prototype.scrollIntoView=vi.fn();vi.stubGlobal("fetch",vi.fn().mockResolvedValue(response(financeFixture())))});
 afterEach(()=>{cleanup();vi.unstubAllGlobals()});
 it("separates cash balance, salary liability and result",()=>{render(<FinanceCenter initial={financeFixture()}/>);expect(screen.getAllByText(/1[\s,]350[\s,]000 UZS/)[0]).toBeTruthy();expect(screen.getByText(/120[\s,]000 UZS/)).toBeTruthy();expect(screen.getByRole("navigation",{name:"Moliyaviy boʻlimlar"})).toBeTruthy()});
 it("does not present unknown month balances as zero",()=>{const data=financeFixture();data.period=null;render(<FinanceCenter initial={data}/>);expect(screen.queryByText(/1[\s,]350[\s,]000 UZS/)).toBeNull();expect(screen.getAllByText("— UZS").length).toBeGreaterThan(3);expect((screen.getByRole("button",{name:/Kurs toʻlovini yozish/}) as HTMLButtonElement).disabled).toBe(true)});
 it("blocks monetary form submission on a closed period",()=>{const data=financeFixture();data.period!.status="CLOSED";render(<FinanceCenter initial={data}/>);fireEvent.click(screen.getByRole("button",{name:"Ish haqi"}));expect((screen.getByRole("button",{name:/Avansni yozish/}) as HTMLButtonElement).disabled).toBe(true);expect((screen.getByRole("button",{name:/Ish haqini yozish/}) as HTMLButtonElement).disabled).toBe(true)});
 it("shows payroll debt and center share in mobile-friendly cards",()=>{const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Ish haqi"}));expect(container.querySelector(".finance-mobile-cards")?.textContent).toContain(`${formatUzs("230000")} UZS`);expect(container.querySelector(".finance-mobile-cards")?.textContent).toContain(`${formatUzs("170000")} UZS`)});
 it("searches learners and applies invoice-debt filtering",()=>{render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Toʻlovlar va qarzlar"}));fireEvent.click(screen.getByRole("checkbox",{name:"Faqat qarzi bor"}));expect(screen.queryByRole("checkbox",{name:"Learner A uchun hisob tanlash"})).toBeNull();expect(screen.getByRole("checkbox",{name:"Learner B uchun hisob tanlash"})).toBeTruthy();fireEvent.change(screen.getByRole("textbox",{name:"Oʻquvchini qidirish"}),{target:{value:"absent"}});expect(screen.queryByRole("checkbox",{name:"Learner B uchun hisob tanlash"})).toBeNull()});
 it("preserves entered fields and reuses a private retry key after failure",async()=>{
 const fetchMock=vi.mocked(fetch);fetchMock.mockResolvedValue(response({error:"Synthetic service unavailable"},503) as Response);
 const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Xarajatlar"}));const form=container.querySelector("form")!;const amount=form.querySelector('input[name="amount"]') as HTMLInputElement;const description=form.querySelector('input[name="description"]') as HTMLInputElement;
 fireEvent.change(amount,{target:{value:"123456"}});fireEvent.change(description,{target:{value:"Private test memo"}});fireEvent.submit(form);
 await screen.findByText("Synthetic service unavailable");expect(amount.value).toBe("123456");expect(description.value).toBe("Private test memo");
 const storageKey=sessionStorage.key(0)!;expect(storageKey).toMatch(/^averna:finance:admin-test:[a-f0-9]{64}$/);expect(sessionStorage.getItem(storageKey)).not.toContain("Private test memo");
 const first=fetchMock.mock.calls[0][1]!.headers as Record<string,string>;fireEvent.submit(form);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));expect((fetchMock.mock.calls[1][1]!.headers as Record<string,string>)["Idempotency-Key"]).toBe(first["Idempotency-Key"]);
 });
 it("embeds as a section with shared cards, six finance tabs and no duplicate page chrome",()=>{const {container}=render(<FinanceCenter initial={financeFixture()} embedded/>);expect(container.querySelector("main")).toBeNull();expect(container.querySelector("section.finance-shell-embedded")).toBeTruthy();expect(container.querySelectorAll(".finance-box.glass").length).toBeGreaterThan(2);expect(container.querySelectorAll("nav button")).toHaveLength(6);expect(screen.queryByText("Admin Dashboard")).toBeNull();expect(screen.queryByRole("button",{name:"Lidlar"})).toBeNull();expect(screen.getByRole("heading",{name:"Moliya va nazorat",level:2})).toBeTruthy()});
 it("shows intake without a cash workspace or month controls",()=>{const {container}=render(<FinanceCenter initial={financeFixture()} embedded view="leads"/>);expect(container.querySelector("main")).toBeNull();expect(screen.queryByRole("navigation",{name:"Moliyaviy boʻlimlar"})).toBeNull();expect(screen.queryByLabelText("Hisobot oyi")).toBeNull();expect(screen.getByText("Prospect A")).toBeTruthy();expect(screen.getByRole("button",{name:"Lidni saqlash"})).toBeTruthy()});
 it("starts a payment from an invoice and focuses the editable remaining amount",()=>{const {container}=render(<FinanceCenter initial={financeFixture()} embedded/>);fireEvent.click(screen.getByRole("button",{name:"Toʻlovlar va qarzlar"}));fireEvent.click(screen.getByRole("button",{name:"Toʻlov qabul qilish"}));const form=container.querySelector(".finance-payment-target form")!;expect((form.querySelector('select[name="invoiceId"]') as HTMLSelectElement).value).toBe("invoice-B");expect((form.querySelector('input[name="amount"]') as HTMLInputElement).value).toBe("500000");expect(document.activeElement).toBe(form.querySelector('input[name="amount"]'));expect(HTMLElement.prototype.scrollIntoView).toHaveBeenCalled()});
 it("selects only learners without a bill for the selected month",()=>{const data=financeFixture();data.learners.push({...data.learners[0],id:"learner-C",fullName:"Learner C"});render(<FinanceCenter initial={data}/>);fireEvent.click(screen.getByRole("button",{name:"Toʻlovlar va qarzlar"}));expect((screen.getByRole("checkbox",{name:"Learner A uchun hisob tanlash"}) as HTMLInputElement).disabled).toBe(true);fireEvent.click(screen.getByRole("button",{name:"Hisobi yoʻqlarni tanlash"}));expect((screen.getByRole("checkbox",{name:"Learner C uchun hisob tanlash"}) as HTMLInputElement).checked).toBe(true);expect(screen.getByRole("button",{name:"1 ta hisob chiqarish"})).toBeTruthy()});
 it("clears a committed cash form only after a successful report refresh",async()=>{const fetchMock=vi.mocked(fetch);fetchMock.mockResolvedValueOnce(response({ok:true}) as Response).mockResolvedValueOnce(response(financeFixture()) as Response);const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Xarajatlar"}));const form=container.querySelector("form")!;const amount=form.querySelector('input[name="amount"]') as HTMLInputElement;const desc=form.querySelector('input[name="description"]') as HTMLInputElement;fireEvent.change(amount,{target:{value:"123"}});fireEvent.change(desc,{target:{value:"Synthetic receipt"}});fireEvent.submit(form);await screen.findByText("Saqlandi. Hisobot va jurnal yangilandi.");expect(amount.value).toBe("");expect(desc.value).toBe("");expect(sessionStorage.length).toBe(0)});
 it("retains form and retry key when a committed write cannot refresh its report",async()=>{const fetchMock=vi.mocked(fetch);fetchMock.mockResolvedValueOnce(response({ok:true}) as Response).mockResolvedValueOnce(response({error:"Synthetic refresh failure"},503) as Response);const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Xarajatlar"}));const form=container.querySelector("form")!;const amount=form.querySelector('input[name="amount"]') as HTMLInputElement;fireEvent.change(amount,{target:{value:"123"}});fireEvent.submit(form);await screen.findByText("Synthetic refresh failure");expect(amount.value).toBe("123");expect(sessionStorage.length).toBe(1)});
 it("guards rapid duplicate submit and locks fields and tab changes while pending",async()=>{let finish:(r:Response)=>void=()=>{};const fetchMock=vi.mocked(fetch);fetchMock.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}));const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Xarajatlar"}));const form=container.querySelector("form")!;fireEvent.change(form.querySelector('input[name="amount"]')!,{target:{value:"123"}});fireEvent.submit(form);fireEvent.submit(form);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(1));expect((form.querySelector("fieldset") as HTMLFieldSetElement).disabled).toBe(true);expect((screen.getByRole("button",{name:"Jurnal"}) as HTMLButtonElement).disabled).toBe(true);finish(response({error:"Synthetic duplicate guard"},503) as Response);await screen.findByText("Synthetic duplicate guard");expect((form.querySelector("fieldset") as HTMLFieldSetElement).disabled).toBe(false)});

 it("offers an exact monthly payment shortcut on the mobile learner card",()=>{const {container}=render(<FinanceCenter initial={financeFixture()}/>);fireEvent.click(screen.getByRole("button",{name:"Toʻlovlar va qarzlar"}));const card=container.querySelector(".finance-mobile-cards")!;const button=Array.from(card.querySelectorAll("button")).find(b=>b.textContent==="2026-10 uchun toʻlov")!;fireEvent.click(button);expect((container.querySelector('.finance-payment-target select[name="invoiceId"]') as HTMLSelectElement).value).toBe("invoice-B")});

});
