import { beforeEach,describe,expect,it,vi } from "vitest";
const m=vi.hoisted(()=>({prior:vi.fn(),transaction:vi.fn(),lock:vi.fn(),period:vi.fn(),req:vi.fn(),audit:vi.fn(),entry:vi.fn(),entryFind:vi.fn(),invoice:vi.fn(),aggregate:vi.fn(),staff:vi.fn(),periodUpdate:vi.fn(),periodEntries:vi.fn(),accrual:vi.fn()}));
vi.mock("@/lib/db",()=>({db:{financeRequest:{findUnique:m.prior},$transaction:m.transaction}}));
import { financeMutate } from "@/lib/finance/service";
const actor={id:"admin-a",name:"Admin",role:"ADMIN"};const key="idempotency-key-00001";
const post={action:"POST_ENTRY",month:"2026-10",kind:"TUITION",amount:"100000",channel:"CASH",date:"2026-10-01",description:"Receipt",invoiceId:"invoice-a"};
describe("finance transaction safeguards",()=>{
 beforeEach(()=>{vi.resetAllMocks();m.prior.mockResolvedValue(null);m.period.mockResolvedValue({id:"period-a",month:"2026-10",status:"OPEN",opening:{CASH:"0"}});m.staff.mockResolvedValue({id:"staff-a",active:true});m.aggregate.mockResolvedValue({_sum:{amount:"0"}});m.invoice.mockResolvedValue({id:"invoice-a",staffId:"staff-a",amount:"500000",shareBps:6600,period:{month:"2026-10"}});m.periodEntries.mockResolvedValue([]);m.accrual.mockResolvedValue({_sum:{amount:"0"}});m.transaction.mockImplementation(async fn=>fn({$queryRaw:m.lock,financeRequest:{create:m.req},financePeriod:{findUnique:m.period,update:m.periodUpdate},financeInvoice:{findUnique:m.invoice},financeEntry:{findUnique:m.entryFind,create:m.entry,aggregate:m.aggregate,findMany:m.periodEntries},financeStaff:{findUnique:m.staff},financeAccrual:{aggregate:m.accrual},auditLog:{create:m.audit}}))});
 it("rejects students before any financial query",async()=>{await expect(financeMutate({id:"s",role:"STUDENT"},post,key)).rejects.toMatchObject({status:403});expect(m.prior).not.toHaveBeenCalled()});
 it("rejects closed periods before invoice reads or money writes",async()=>{m.period.mockResolvedValue({id:"p",status:"CLOSED"});await expect(financeMutate(actor,post,key)).rejects.toMatchObject({status:409});expect(m.entry).not.toHaveBeenCalled();expect(m.invoice).not.toHaveBeenCalled()});
 it("locks the period and invoice and snapshots the already-agreed commission",async()=>{await financeMutate(actor,post,key);expect(m.entry.mock.calls[0][0].data).toMatchObject({amount:"100000",earned:"66000",invoiceId:"invoice-a",staffId:"staff-a",actorId:"admin-a"});expect(m.lock.mock.invocationCallOrder[0]).toBeLessThan(m.invoice.mock.invocationCallOrder[0]);expect(m.audit).toHaveBeenCalledOnce()});
 it("prevents overpayment of an invoice",async()=>{m.aggregate.mockResolvedValue({_sum:{amount:"450000"}});await expect(financeMutate(actor,post,key)).rejects.toThrow("qolgan qarzdan oshdi");expect(m.entry).not.toHaveBeenCalled()});
 it("places audit and monetary writes in one transaction, so an audit failure is not swallowed",async()=>{m.audit.mockRejectedValue(new Error("audit unavailable"));await expect(financeMutate(actor,post,key)).rejects.toThrow("audit unavailable");expect(m.transaction).toHaveBeenCalledOnce()});
 it("rejects reuse of an idempotency key for changed data",async()=>{m.prior.mockResolvedValue({payloadHash:"different",result:{ok:true}});await expect(financeMutate(actor,post,key)).rejects.toMatchObject({status:409});expect(m.transaction).not.toHaveBeenCalled()});
 it("returns a committed duplicate without another transaction",async()=>{await financeMutate(actor,post,key);const saved=m.req.mock.calls[0][0].data;m.prior.mockResolvedValue(saved);expect(await financeMutate(actor,post,key)).toEqual({ok:true,message:"Saqlandi."});expect(m.transaction).toHaveBeenCalledOnce()});
 it("rejects future receipts",async()=>{await expect(financeMutate(actor,{...post,month:"2099-10",date:"2099-10-01"},key)).rejects.toThrow("kelajak");expect(m.entry).not.toHaveBeenCalled()});
 it("closes an open period with a stored accounting snapshot under the row lock",async()=>{await financeMutate(actor,{action:"CLOSE_PERIOD",month:"2026-10",confirmation:"YOPISH"},key);expect(m.periodUpdate.mock.calls[0][0].data).toMatchObject({status:"CLOSED",closingSnapshot:{income:"0",balance:"0"}});expect(m.audit).toHaveBeenCalledOnce()});
 it("requires an explicit close confirmation",async()=>{await expect(financeMutate(actor,{action:"CLOSE_PERIOD",month:"2026-10",confirmation:"yes"},key)).rejects.toThrow();expect(m.transaction).not.toHaveBeenCalled()});
 it("rejects a future-period invoice paid in an earlier month",async()=>{m.invoice.mockResolvedValue({id:"invoice-a",staffId:"staff-a",amount:"500000",shareBps:6600,period:{month:"2026-11"}});await expect(financeMutate(actor,post,key)).rejects.toThrow("Kelajak oyi");expect(m.entry).not.toHaveBeenCalled()});
 it("bounds salary payments by earned obligations but allows an explicit advance",async()=>{await expect(financeMutate(actor,{...post,kind:"SALARY",invoiceId:undefined,staffId:"staff-a"},key)).rejects.toThrow("qoldiqdan oshdi");await financeMutate(actor,{...post,kind:"ADVANCE",invoiceId:undefined,staffId:"staff-a"},key);expect(m.entry.mock.calls[0][0].data).toMatchObject({amount:"-100000",earned:"0"})});
 it("rejects refunds dated before their original receipt",async()=>{m.entryFind.mockResolvedValue({id:"receipt-a",kind:"TUITION",amount:"500000",earned:"330000",period:{month:"2026-10"},occurredAt:new Date("2026-10-02T07:00:00Z"),invoice:{shareBps:6600},refunds:[],reversal:null});await expect(financeMutate(actor,{...post,kind:"REFUND",invoiceId:undefined,refundOfId:"receipt-a"},key)).rejects.toThrow("asl toʻlovdan oldin");expect(m.entry).not.toHaveBeenCalled()});
 it("posts exact inverse commission for a final refund in a later open period",async()=>{m.entryFind.mockResolvedValue({id:"receipt-a",kind:"TUITION",amount:"100000",earned:"66000",period:{month:"2026-09"},occurredAt:new Date("2026-09-02T07:00:00Z"),invoiceId:"invoice-a",staffId:"staff-a",invoice:{shareBps:6600},refunds:[],reversal:null});await financeMutate(actor,{...post,kind:"REFUND",invoiceId:undefined,refundOfId:"receipt-a"},key);expect(m.entry.mock.calls[0][0].data).toMatchObject({amount:"-100000",earned:"-66000",refundOfId:"receipt-a"})});
 it("rejects reversal of a refund when subsequent receipts would create overpayment",async()=>{m.entryFind.mockResolvedValue({id:"refund-a",periodId:"period-a",kind:"REFUND",amount:"-100000",earned:"-66000",invoiceId:"invoice-a",staffId:"staff-a",refunds:[],reversal:null});m.aggregate.mockResolvedValue({_sum:{amount:"500000"}});await expect(financeMutate(actor,{action:"REVERSE_ENTRY",month:"2026-10",id:"refund-a",reason:"Correct duplicate refund"},key)).rejects.toThrow("ortiqcha toʻlov");expect(m.entry).not.toHaveBeenCalled()});

});
