import { beforeEach, describe, expect, it, vi } from "vitest";
const m=vi.hoisted(()=>({raw:vi.fn(),tx:vi.fn(),session:vi.fn(),sessionUpdate:vi.fn(),sessionCreate:vi.fn(),sessionFirst:vi.fn(),student:vi.fn(),group:vi.fn(),participant:vi.fn(),participantFirst:vi.fn(),participants:vi.fn(),count:vi.fn(),participantCreate:vi.fn(),participantUpdate:vi.fn(),participantMany:vi.fn(),attemptFirst:vi.fn(),attemptCreate:vi.fn(),attemptUpdate:vi.fn(),attemptMany:vi.fn(),testCreate:vi.fn(),reviewCreate:vi.fn(),view:vi.fn(),audio:vi.fn(),reading:vi.fn(),writing:vi.fn()}));
function database(){return ({$queryRaw:m.raw,$transaction:m.tx,user:{findUnique:vi.fn()},teacher:{findUnique:vi.fn()},group:{findUnique:m.group},mockSession:{findUnique:m.session,findFirst:m.sessionFirst,create:m.sessionCreate,update:m.sessionUpdate},student:{findUnique:m.student},mockParticipant:{findUnique:m.participant,findFirst:m.participantFirst,findMany:m.participants,count:m.count,create:m.participantCreate,update:m.participantUpdate,updateMany:m.participantMany},mockAttempt:{findFirst:m.attemptFirst,create:m.attemptCreate,update:m.attemptUpdate,updateMany:m.attemptMany},iELTSTest:{create:m.testCreate},testReview:{create:m.reviewCreate}});}
vi.mock("@/lib/db",()=>({db:database()}));vi.mock("@/lib/ielts/mock",()=>({getMockView:m.view,resultsOf:(r:unknown)=>r||{}}));vi.mock("@/lib/ielts/catalog",()=>({listListeningExams:async()=>[],listReadingExams:async()=>[],listWritingTasks:m.writing,getListeningExam:vi.fn(),getWritingTask:vi.fn()}));vi.mock("@/lib/ielts/mock-library",()=>({mockListeningLibrary:m.audio,mockReadingLibrary:m.reading}));vi.mock("@/lib/ielts/audio/client",()=>({listeningClientContent:vi.fn()}));
import { controlSession, joinSession, saveReview } from "@/lib/group-mock/service";
const pool={listening:[{id:"l",milliseconds:126000}],reading:["r"],task1:["w1"],task2:["w2"]};let session:any,student:any,p:any;let roles:Record<string,string>;
beforeEach(()=>{vi.resetAllMocks();roles={teacher:"TEACHER",learner:"STUDENT"};session={id:"s",teacherId:"t",groupId:"g",teacher:{userId:"teacher",user:{role:"TEACHER"}},group:{teacherId:"t"},state:"lobby",version:0,distribution:"unique",pool};student={id:"student",userId:"learner",groupId:"g",blacklisted:false,user:{role:"STUDENT"}};p={id:"p",sessionId:"s",studentId:"student",attemptId:"a",ordinal:0,ready:true,version:0,publishedAt:null,student,work:{task1:{essay:"First essay",prompt:"Task one"},task2:{essay:"Second essay",prompt:"Task two"}},attempt:{status:"active",sectionStartedAt:null,papers:{listening:"l",reading:"r",task1:"w1",task2:"w2"},results:{LISTENING:{band:6},READING:{band:7}}}};m.raw.mockImplementation(async(strings:any,id:string)=>String(strings[0]).includes('SELECT "role"')?[{role:roles[id]}]:[]);m.tx.mockImplementation(async fn=>fn(database()));m.session.mockImplementation(async()=>session);m.student.mockImplementation(async()=>student);m.group.mockResolvedValue({id:"g",teacherId:"t",teacher:{userId:"teacher"}});m.participants.mockImplementation(async()=>[p]);m.participantFirst.mockImplementation(async()=>p);m.participant.mockResolvedValue(null);m.count.mockResolvedValue(0);m.attemptFirst.mockResolvedValue(null);m.attemptCreate.mockResolvedValue({id:"a"});m.participantUpdate.mockImplementation(async({data}:any)=>{Object.assign(p,data);return p;});m.sessionUpdate.mockImplementation(async({data}:any)=>{Object.assign(session,data);return session;});m.testCreate.mockImplementation(async()=>({id:`test-${m.testCreate.mock.calls.length}`}));m.audio.mockResolvedValue(new Map([["l",{parts:[{audio:{durationMs:6000}}]}]]));m.reading.mockResolvedValue(new Set(["r"]));m.writing.mockImplementation(async(task:string)=>[{id:task==="task1"?"w1":"w2"}]);});
const w={taskAchievement:6,coherenceCohesion:6,lexicalResource:6,grammarAccuracy:6};const s={fluency:7,lexical:7,grammar:7,pronunciation:7};const review={participantId:"p",version:0,task1:w,task2:w,speaking:s,speakingConducted:true,comment:"Manual assessment",publish:true};
describe("session ownership and lifecycle",()=>{
 it("rejects a different teacher and revoked role before updates",async()=>{roles.other="TEACHER";await expect(controlSession("other","s","start",0)).rejects.toMatchObject({status:403});roles.teacher="ADMIN";await expect(controlSession("teacher","s","start",0)).rejects.toMatchObject({status:403});expect(m.attemptUpdate).not.toHaveBeenCalled();});
 it("denies transfers/blacklist and new joins after start",async()=>{student.groupId="other";await expect(joinSession("learner","12345678")).rejects.toMatchObject({status:403});student.groupId="g";student.blacklisted=true;await expect(joinSession("learner","12345678")).rejects.toMatchObject({status:403});student.blacklisted=false;session.state="running";await expect(joinSession("learner","12345678")).rejects.toMatchObject({status:409});expect(m.attemptCreate).not.toHaveBeenCalled();});
 it("returns an existing join idempotently without drawing new papers",async()=>{m.participant.mockResolvedValue(p);session.state="running";expect(await joinSession("learner","12345678")).toEqual({sessionId:"s",attemptId:"a"});expect(m.attemptCreate).not.toHaveBeenCalled();});
 it("refuses an existing active independent attempt and exhausted uniqueness",async()=>{m.attemptFirst.mockResolvedValueOnce({id:"personal"});await expect(joinSession("learner","12345678")).rejects.toMatchObject({status:409});m.count.mockResolvedValueOnce(1);await expect(joinSession("learner","12345678")).rejects.toMatchObject({status:422});expect(m.participantCreate).not.toHaveBeenCalled();});
 it("requires all ready and a matching command version",async()=>{p.ready=false;await expect(controlSession("teacher","s","start",0)).rejects.toMatchObject({status:409});p.ready=true;await expect(controlSession("teacher","s","start",1)).rejects.toMatchObject({status:409});expect(m.attemptUpdate).not.toHaveBeenCalled();});
 it("sets one future start with each recording's existing duration",async()=>{const now=Date.now();await controlSession("teacher","s","start",0);const d=m.attemptUpdate.mock.calls[0][0].data;expect(d.sectionStartedAt.getTime()).toBeGreaterThanOrEqual(now+15000);expect(d.sectionDeadline-d.sectionStartedAt).toBe(126000);expect(m.raw.mock.calls.some(c=>String(c[0][0]).includes('"mock_sessions"'))).toBe(true);expect(m.raw.mock.calls.some(c=>String(c[0][0]).includes('"students"'))).toBe(true);});
 it("collection cannot extend an expired section and cancel preserves completed attempts",async()=>{session.state="running";await controlSession("teacher","s","end",0);expect(m.attemptMany.mock.calls[0][0].where.sectionDeadline.gt).toBeInstanceOf(Date);session.state="running";session.version=0;await controlSession("teacher","s","cancel",0);expect(m.attemptMany.mock.calls[1][0].where.status).toBe("active");});
 it("saves private partial rubrics without creating grades",async()=>{session.state="review";p.attempt.status="finished";await saveReview("teacher","s",{...review,publish:false,task1:{},speaking:{},speakingConducted:false});expect(m.testCreate).not.toHaveBeenCalled();expect(m.participantUpdate.mock.calls[0][0].data.review.speakingConducted).toBe(false);});
 it("publishes exactly two Writing and one in-person Speaking test, never fake recordings",async()=>{session.state="review";p.attempt.status="finished";await saveReview("teacher","s",review);expect(m.testCreate).toHaveBeenCalledTimes(3);expect(m.reviewCreate).toHaveBeenCalledTimes(3);expect(m.testCreate.mock.calls[2][0].data.answers).toMatchObject({inputMode:"in-person",teacherConducted:true});expect(m.testCreate.mock.calls[2][0].data.answers.recorded).toBeUndefined();expect(m.attemptUpdate.mock.calls[0][0].data.papers.groupPublished).toBe(true);await expect(saveReview("teacher","s",review)).rejects.toMatchObject({status:409});expect(m.testCreate).toHaveBeenCalledTimes(3);});
 it("rejects stale review versions, uncollected work and access transfers",async()=>{session.state="review";p.version=1;await expect(saveReview("teacher","s",review)).rejects.toMatchObject({status:409});p.version=0;await expect(saveReview("teacher","s",review)).rejects.toMatchObject({status:409});student.groupId="other";await expect(saveReview("teacher","s",review)).rejects.toMatchObject({status:403});expect(m.testCreate).not.toHaveBeenCalled();});
});
