import { beforeEach, describe, expect, it, vi } from "vitest";
const m=vi.hoisted(()=>({find:vi.fn(),update:vi.fn(),create:vi.fn(),first:vi.fn(),list:vi.fn(),objective:vi.fn(),writing:vi.fn(),speaking:vi.fn(),listening:vi.fn(),reading:vi.fn(),content:vi.fn(),audio:vi.fn(),group:vi.fn(),commit:vi.fn()}));
vi.mock("@/lib/db",()=>({db:{mockAttempt:{findFirst:m.find,updateMany:m.update,create:m.create,findMany:m.list},iELTSTest:{findMany:vi.fn().mockResolvedValue([])}}}));
vi.mock("@/lib/ielts/catalog",()=>({getListeningExam:m.listening,getReadingExam:m.reading,getSpeakingSet:vi.fn(),getWritingTask:vi.fn(),listListeningExams:vi.fn().mockResolvedValue([]),listReadingExams:vi.fn().mockResolvedValue([]),listWritingTasks:vi.fn().mockResolvedValue([]),listSpeakingSets:vi.fn().mockResolvedValue([])}));
vi.mock("@/lib/ielts/audio/client",()=>({listeningClientContent:m.content}));
vi.mock("@/lib/ielts/mock-library",()=>({recordingMinutes:()=>3,isFullObjective:()=>true,mockListeningLibrary:vi.fn().mockResolvedValue(new Map()),mockReadingLibrary:vi.fn().mockResolvedValue(new Set())}));
vi.mock("@/lib/ielts/submit",()=>({submitObjectiveExam:m.objective,submitWritingExam:m.writing,submitSpeakingTest:m.speaking,examPrompt:(x:unknown)=>x}));
vi.mock("@/lib/speaking/recording",()=>({hasRecordedSpeech:vi.fn().mockResolvedValue(false)}));
vi.mock("@/lib/group-mock/service",()=>({groupAttemptState:m.group,commitManualWork:m.commit}));
import { beginSection, saveMockDraft, submitMockSection, paperLockedByMock, listMockAttempts } from "@/lib/ielts/mock";
const papers={mode:"cd-v1",listening:"l",reading:"r",task1:"w1",task2:"w2",speaking:""};
let row:any;
beforeEach(()=>{vi.resetAllMocks();row={id:"a",studentId:"s",status:"active",papers,current:0,sectionStartedAt:new Date(Date.now()-1000),sectionDeadline:new Date(Date.now()+100000),draft:{answers:{"1":"A"},__mock:{revision:1}},results:{},updatedAt:new Date(),startedAt:new Date()};m.find.mockImplementation(async({where}:any)=>where.studentId==="s"?{...row}:null);m.update.mockImplementation(async({where,data}:any)=>{if(where.current!==undefined && where.current!==row.current)return {count:0};row={...row,...data,updatedAt:new Date()};return {count:1};});m.listening.mockResolvedValue({id:"l",parts:[]});m.reading.mockResolvedValue({id:"r",parts:[]});m.content.mockResolvedValue({parts:[]});m.objective.mockResolvedValue({band:7,testId:"t",correct:30,total:40,answered:40,xpAwarded:10});});

describe("teacher-led engine does not run Writing AI",()=>{
 beforeEach(()=>{row.papers={...papers,groupSessionId:"session"};row.current=2;row.draft={essays:{task1:"Saved first essay",task2:"Saved second essay"},__mock:{revision:1}};row.results={LISTENING:{band:7},READING:{band:6}};m.group.mockResolvedValue({state:"running",startAt:Date.now()-10000});m.commit.mockImplementation(async(_id,_work,where,data)=>m.update({where,data}));});
 it("commits both essays with a pending result, no AI/test IDs/XP/overall",async()=>{const work={essays:{task1:"Collected first essay",task2:"Collected second essay"}};expect(await submitMockSection({studentId:"s",userId:"u",attemptId:"a",section:2,payload:work,revision:1})).toMatchObject({ok:true,done:true});expect(m.commit).toHaveBeenCalledOnce();expect(m.commit.mock.calls[0][1]).toEqual(work);expect(row.results.WRITING).toMatchObject({pendingReview:true,testIds:[],xp:0});expect(row.status).toBe("finished");expect(row.overall).toBeNull();expect(m.writing).not.toHaveBeenCalled();expect(m.speaking).not.toHaveBeenCalled();});
 it("deadline collection uses the last account essays, never late device edits",async()=>{row.sectionDeadline=new Date(Date.now()-6000);await submitMockSection({studentId:"s",userId:"u",attemptId:"a",section:2,payload:{essays:{task1:"Too late",task2:""}},revision:1});expect(m.commit.mock.calls[0][1].essays.task1).toBe("Saved first essay");expect(m.writing).not.toHaveBeenCalled();});
 it("rejects a stale draft and teacher's future start",async()=>{expect(await submitMockSection({studentId:"s",userId:"u",attemptId:"a",section:2,payload:{essays:{task1:"",task2:""}},revision:0})).toMatchObject({ok:false,status:409});m.group.mockResolvedValue({state:"running",startAt:Date.now()+15000});expect(await saveMockDraft("s","a",2,{essays:{task1:"",task2:""}},1)).toEqual({ok:false});expect(m.commit).not.toHaveBeenCalled();expect(m.writing).not.toHaveBeenCalled();});
 it("hides pending Writing as unrated, retains published Speaking and overall",async()=>{m.list.mockResolvedValue([{...row,status:"finished",results:{LISTENING:{band:7},WRITING:{band:0,pendingReview:true}},overall:0}]);const [pending]=await listMockAttempts("s");expect(pending.bands.WRITING).toBeUndefined();expect(pending.overall).toBeNull();expect(pending.groupPublished).toBe(false);m.list.mockResolvedValue([{...row,status:"finished",papers:{...row.papers,groupPublished:true},results:{WRITING:{band:7},SPEAKING:{band:7}},overall:7}]);const [published]=await listMockAttempts("s");expect(published.sections).toContain("SPEAKING");expect(published.overall).toBe(7);});
});
