import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { CycleWorkspace } from "@/components/learning-cycle/workspace";
import { cycleFixture, practiceRevision } from "./fixtures/learning-cycle";
const response = (cycle: unknown, status = 200, error?: string) => ({ ok: status < 400, json: async () => error ? { error } : { cycle } });
describe("accessible formative practice workspace", () => {
  beforeEach(() => vi.stubGlobal("fetch", vi.fn())); afterEach(() => { cleanup(); vi.unstubAllGlobals() });
  it("explains the provenance and does not promise a certified band increase", () => { render(<CycleWorkspace initial={cycleFixture()} />); expect(screen.getByText(/AI practice estimate/)).toBeTruthy(); expect(screen.getByText(/not hidden reasoning/)).toBeTruthy(); expect(screen.getByRole("navigation", { name: "Practice cycle steps" })).toBeTruthy(); expect(screen.getByRole("link", { name: /Original result/ }).getAttribute("href")).toBe("/learning/writing/result/test-12345") });
  it("keeps a response and reflection after a failed save", async () => { vi.mocked(fetch).mockResolvedValue(response(null, 503, "Synthetic save failure") as Response); render(<CycleWorkspace initial={cycleFixture()} />); const body = screen.getByRole("textbox", { name: "Your revised response" }); fireEvent.change(body, { target: { value: practiceRevision } }); fireEvent.change(screen.getByRole("textbox", { name: "What did you change or apply?" }), { target: { value: "I added a clear example." } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); expect(await screen.findByRole("alert")).toBeTruthy(); expect((body as HTMLTextAreaElement).value).toBe(practiceRevision); expect((screen.getByRole("textbox", { name: "What did you change or apply?" }) as HTMLTextAreaElement).value).toBe("I added a clear example.") });
  it("saves a draft and uses its returned version on submission", async () => { const data = cycleFixture(); const reflection = "I added a clear example."; const draft = { id: "draft-r", kind: "REVISION" as const, status: "DRAFT" as const, body: practiceRevision, reflection, version: 1, createdAt: "2026-10-10", updatedAt: "2026-10-10", review: null }; vi.mocked(fetch).mockResolvedValueOnce(response({ ...data, entries: [draft] }) as Response).mockResolvedValueOnce(response(cycleFixture("waiting")) as Response); const { container } = render(<CycleWorkspace initial={data} />); fireEvent.change(screen.getByRole("textbox", { name: "Your revised response" }), { target: { value: practiceRevision } }); fireEvent.change(screen.getByRole("textbox", { name: "What did you change or apply?" }), { target: { value: reflection } }); fireEvent.click(screen.getByRole("button", { name: "Save draft" })); await screen.findByText(/Draft saved privately/); await waitFor(() => expect((screen.getByRole("button", { name: "Submit for feedback" }) as HTMLButtonElement).disabled).toBe(false)); fireEvent.submit(container.querySelector("form")!); await screen.findByText("Awaiting teacher feedback"); expect(JSON.parse(vi.mocked(fetch).mock.calls[1][1]!.body as string).version).toBe(1) });
  it("guards duplicate submission and locks fields while pending", async () => { let finish: (value: Response) => void = () => { }; vi.mocked(fetch).mockImplementationOnce(() => new Promise(resolve => { finish = resolve })); const { container } = render(<CycleWorkspace initial={cycleFixture()} />); fireEvent.change(screen.getByRole("textbox", { name: "Your revised response" }), { target: { value: practiceRevision } }); fireEvent.submit(container.querySelector("form")!); fireEvent.submit(container.querySelector("form")!); expect(fetch).toHaveBeenCalledTimes(1); expect((container.querySelector("fieldset") as HTMLFieldSetElement).disabled).toBe(true); finish(response(null, 503, "Synthetic failure") as Response); await screen.findByRole("alert") });
  it("does not silently overwrite a newer server draft when refreshing", async () => { const data = cycleFixture(); vi.mocked(fetch).mockResolvedValue(response({ ...data, entries: [{ id: "r", kind: "REVISION", status: "DRAFT", body: "A newer draft from another tab.", reflection: "New notes", version: 2, createdAt: "2026-10-10", updatedAt: "2026-10-10", review: null }] }) as Response); render(<CycleWorkspace initial={data} />); fireEvent.click(screen.getByRole("button", { name: "Refresh feedback" })); expect(await screen.findByText(/A newer draft is saved/)).toBeTruthy(); expect((screen.getByRole("button", { name: "Submit for feedback" }) as HTMLButtonElement).disabled).toBe(true); expect((screen.getByRole("textbox", { name: "Your revised response" }) as HTMLTextAreaElement).value).toBe(data.plan.original) });
  it("unlocks a distinct authored task only after revision feedback", () => { render(<CycleWorkspace initial={cycleFixture("transfer")} />); expect(screen.getByRole("textbox", { name: "Your response to the new task" })).toBeTruthy(); expect(screen.getByText(cycleFixture("transfer").plan.transfer.prompt)).toBeTruthy(); expect(screen.queryByRole("textbox", { name: "Your revised response" })).toBeNull() });
  it("staff reviews quoted evidence, not a replacement numeric band", () => { render(<CycleWorkspace initial={cycleFixture("staff")} />); expect(screen.getByText("Review focus skills — not an IELTS re-band")).toBeTruthy(); expect(screen.getAllByRole("combobox")).toHaveLength(2); expect(screen.queryByRole("spinbutton")).toBeNull(); expect(screen.queryByRole("button", { name: "Save draft" })).toBeNull() });
  it("completed evidence remains private and is not described as permanent mastery", () => { render(<CycleWorkspace initial={cycleFixture("complete")} />); expect(screen.getByText(/one exercise does not prove permanent mastery/)).toBeTruthy(); expect(screen.getByRole("link", { name: /Open private portfolio/ })).toBeTruthy(); expect(screen.getByText(/There is no public sharing link/)).toBeTruthy() });
});
