import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { MockDraftQueue } from "@/components/exam/mock-draft-queue";
const response = (data: unknown, status=200) => new Response(JSON.stringify(data), {status});
beforeEach(() => { localStorage.clear(); vi.useFakeTimers(); });
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
describe("mock autosave queue", () => {
 it("persists before sending, coalesces and checks confirmation", async () => { const fetch = vi.fn().mockResolvedValue(response({ok:true,revision:1})); vi.stubGlobal("fetch",fetch); const q = new MockDraftQueue("a",0,true,null); q.queue({answers:{"1":"A"}}); q.queue({answers:{"1":"B"}}); expect(JSON.parse(localStorage.getItem(q.key)!).draft.answers["1"]).toBe("B"); await q.send(); expect(fetch).toHaveBeenCalledOnce(); expect(q.status).toBe("saved"); expect(q.revision).toBe(1); q.close(); });
 it("urgent flush NEVER overlaps an in-flight save", async () => { let resolve!: (r: Response)=>void; const fetch = vi.fn().mockImplementationOnce(()=>new Promise<Response>(r=>{resolve=r;})).mockResolvedValue(response({ok:true,revision:2})); vi.stubGlobal("fetch",fetch); const q=new MockDraftQueue("a",1,true,null); q.queue({answers:{"1":"A"}}); const first=q.send(); q.queue({answers:{"1":"B"}}); const urgent=q.send(true); expect(fetch).toHaveBeenCalledOnce(); resolve(response({ok:true,revision:1})); await first; await urgent; expect(fetch).toHaveBeenCalledTimes(2); expect(JSON.parse(fetch.mock.calls[1][1].body).revision).toBe(1); q.close(); });
 it.each([401,429,503])("keeps device copy on HTTP %s and retries", async status => { const fetch=vi.fn().mockResolvedValueOnce(response({error:"failed"},status)).mockResolvedValue(response({ok:true,revision:1})); vi.stubGlobal("fetch",fetch); const q=new MockDraftQueue("a",2,true,null); q.queue({essays:{task1:"work",task2:""}}); await q.send(); expect(q.status).toBe("offline"); expect(q.pending).toEqual(q.latest); await q.send(); expect(q.status).toBe("saved"); q.close(); });
 it("restores unacknowledged local work even with nonempty server answers", () => { const first=new MockDraftQueue("a",0,true,{answers:{"1":"server"},__mock:{revision:3}}); first.queue({answers:{"1":"new local"}}); first.pause(); const restored=new MockDraftQueue("a",0,true,{answers:{"1":"server"},__mock:{revision:3}}); expect(restored.latest).toEqual({answers:{"1":"new local"}}); expect(restored.conflict).toBe(false); restored.close(); });
 it("never silently overwrites a different server revision", () => { localStorage.setItem("averna-mock-draft:a:0",JSON.stringify({revision:2,draft:{answers:{"1":"local"}}})); const q=new MockDraftQueue("a",0,true,{answers:{"1":"remote"},__mock:{revision:3}}); expect(q.conflict).toBe(true); expect(q.latest).toEqual({answers:{"1":"local"}}); q.close(); });
 it("stops retries on conflict until explicit device choice", async () => { const fetch=vi.fn().mockResolvedValue(response({ok:false,conflict:true,revision:5},409)); vi.stubGlobal("fetch",fetch); const q=new MockDraftQueue("a",0,true,null); q.queue({answers:{"1":"A"}}); await q.send(); await q.send(); expect(fetch).toHaveBeenCalledOnce(); expect(q.status).toBe("conflict"); q.keepDevice(); expect(q.conflict).toBe(false); expect(q.revision).toBe(5); q.close(); });
});
