import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { Classroom } from "@/components/teacher-tools/classroom";
import { Calibration } from "@/components/teacher-tools/calibration";
import { classroomFixture, calibrationFixture } from "./fixtures/teacher-tools";
const response = (view: unknown, status = 200, error?: string) => ({ ok: status < 400, status, json: async () => error ? { error } : { view } } as Response);
beforeEach(() => vi.stubGlobal("fetch", vi.fn())); afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.useRealTimers(); });
describe("Teacher tools accessible UI", () => {
  it("unlocks controls after a request timeout without dropping typed input", async () => {
    vi.useFakeTimers(); vi.mocked(fetch).mockImplementation((_url, options) => new Promise((_resolve, reject) => options?.signal?.addEventListener("abort", () => reject(new DOMException("Aborted", "AbortError")))));
    const { container } = render(<Classroom initial={classroomFixture()} />);
    fireEvent.click(screen.getByRole("button", { name: "I have a question" })); fireEvent.change(screen.getByRole("textbox", { name: "Your question" }), { target: { value: "Keep this question during a timeout." } }); fireEvent.submit(container.querySelector("form")!);
    await act(async () => { await vi.advanceTimersByTimeAsync(12001); });
    expect(screen.getByRole("alert").textContent).toContain("timed out"); expect((screen.getByRole("textbox", { name: "Your question" }) as HTMLTextAreaElement).value).toBe("Keep this question during a timeout."); expect((container.querySelector("fieldset") as HTMLFieldSetElement).disabled).toBe(false);
  });
  it("student never sees other learner names or answer key before close", () => { render(<Classroom initial={classroomFixture()} />); expect(screen.queryByText("QA Learner One")).toBeNull(); expect(screen.queryByText(/Correct option/)).toBeNull(); expect(screen.getByText(/not to other learners/)).toBeTruthy(); });
  it("questions remain typed after a failed request", async () => { vi.mocked(fetch).mockResolvedValue(response(null, 503, "Synthetic signal failure")); const { container } = render(<Classroom initial={classroomFixture()} />); fireEvent.click(screen.getByRole("button", { name: "I have a question" })); fireEvent.change(screen.getByRole("textbox", { name: "Your question" }), { target: { value: "Can you explain the connection?" } }); fireEvent.submit(container.querySelector("form")!); expect(await screen.findByRole("alert")).toBeTruthy(); expect((screen.getByRole("textbox", { name: "Your question" }) as HTMLTextAreaElement).value).toBe("Can you explain the connection?"); });
  it("prevents duplicate in-flight signal writes", async () => { let finish: (v: Response) => void = () => { }; vi.mocked(fetch).mockImplementation(() => new Promise(resolve => { finish = resolve; })); const { container } = render(<Classroom initial={classroomFixture()} />); fireEvent.submit(container.querySelector("form")!); fireEvent.submit(container.querySelector("form")!); expect(fetch).toHaveBeenCalledTimes(1); finish(response(classroomFixture())); await screen.findByText(/Saved. No grades/); });
  it("shows named teacher signals without student ranking", () => { render(<Classroom initial={classroomFixture("staff")} />); expect(screen.getByText("QA Learner One")).toBeTruthy(); expect(screen.getByText("How can I connect this example to the main idea?")).toBeTruthy(); expect(screen.getByText(/No signal is not a judgment/)).toBeTruthy(); });
  it("requires explicit end-lesson confirmation", () => { render(<Classroom initial={classroomFixture("staff")} />); fireEvent.click(screen.getByRole("button", { name: "End lesson" })); expect(screen.getByRole("button", { name: "Confirm close" })).toBeTruthy(); expect(fetch).not.toHaveBeenCalled(); });
  it("reveals discussion explanation only for closed check", () => { render(<Classroom initial={classroomFixture("closed")} />); expect(screen.getByText("Discuss the answer")).toBeTruthy(); expect(screen.queryByRole("button", { name: "Save answer" })).toBeNull(); });
  it("removes stale roster when access is revoked", async () => { vi.mocked(fetch).mockResolvedValue(response(null, 404, "Classroom no longer available")); render(<Classroom initial={classroomFixture("staff")} />); fireEvent.click(screen.getByRole("button", { name: "Refresh" })); await screen.findByText("Classroom unavailable"); expect(screen.queryByText("QA Learner One")).toBeNull(); });
  it("keeps an unsent question when teacher opens a new lesson", async () => { const old = classroomFixture(); const newer = { ...old, session: { ...old.session!, id: "new-lesson", topic: "New topic" } }; vi.mocked(fetch).mockResolvedValue(response(newer)); render(<Classroom initial={old} />); fireEvent.click(screen.getByRole("button", { name: "I have a question" })); fireEvent.change(screen.getByRole("textbox", { name: "Your question" }), { target: { value: "Please keep this unsent question." } }); fireEvent.click(screen.getByRole("button", { name: "Refresh" })); await screen.findByText(/The lesson changed/); expect((screen.getByRole("textbox", { name: "Your question" }) as HTMLTextAreaElement).value).toBe("Please keep this unsent question."); });
  it("does not expose reference scores before commitment", () => { render(<Calibration initial={calibrationFixture()} />); expect(screen.queryByText("Centre-agreed rationale")).toBeNull(); expect(screen.getByRole("button", { name: /Save & compare/ })).toBeTruthy(); expect(screen.getAllByRole("combobox")).toHaveLength(4); });
  it("keeps independent reasoning on API failure", async () => { vi.mocked(fetch).mockResolvedValue(response(null, 503, "Synthetic assessment failure")); const { container } = render(<Calibration initial={calibrationFixture()} />); const input = screen.getByRole("textbox", { name: "Explain your criterion judgments" }); fireEvent.change(input, { target: { value: "The example supports the main idea but its connection needs work." } }); fireEvent.submit(container.querySelector("form")!); expect(await screen.findByRole("alert")).toBeTruthy(); expect((input as HTMLTextAreaElement).value).toContain("connection needs work"); });
  it("uses signed differences without public ranking", () => { render(<Calibration initial={calibrationFixture("comparison")} />); expect(screen.getByText("+0.5")).toBeTruthy(); expect(screen.getByText("-0.5")).toBeTruthy(); expect(screen.getByText(/No other staff member’s ratings/)).toBeTruthy(); expect(screen.queryByRole("button", { name: /Save & compare/ })).toBeNull(); });
  it("empty library explains author approval rather than invented scores", () => { render(<Calibration initial={calibrationFixture("empty")} />); expect(screen.getByText("No centre-agreed references yet.")).toBeTruthy(); expect(screen.queryByRole("textbox")).toBeNull(); });
  it("only admin fixture has publication controls", () => { render(<Calibration initial={calibrationFixture("admin")} />); expect(screen.getByRole("checkbox")).toBeTruthy(); expect(screen.getByRole("button", { name: "Publish reference" })).toBeTruthy(); });
});
