export const ADVENTURES = [
  { slug: "series", title: "A new chapter", kind: "Interactive series", description: "Your first week abroad. Your words and choices move the story.", skill: "Speaking + Writing", minutes: "5–8 min", icon: "film" },
  { slug: "detective", title: "English Detective", kind: "Evidence room", description: "Read the clues, listen closely, and explain what really happened.", skill: "Reading + Listening", minutes: "5–7 min", icon: "search" },
  { slug: "debate", title: "Debate Arena", kind: "Take a position", description: "Make a claim, face a challenge, then argue the other side.", skill: "Speaking + Reasoning", minutes: "4–6 min", icon: "messages" },
  { slug: "rescue", title: "Save the situation", kind: "Three replies", description: "A surprise, a constraint, and a chance to make yourself understood.", skill: "Practical English", minutes: "3–5 min", icon: "life" },
  { slug: "builder", title: "Question Workshop", kind: "Become the author", description: "Build a mini reading challenge. Preview it before sharing for teacher review.", skill: "Reading + Writing", minutes: "8–12 min", icon: "pencil" },
  { slug: "capsules", title: "Voice time capsule", kind: "Then and now", description: "Keep a real recording. Return to the same question and hear your journey.", skill: "Speaking + Reflection", minutes: "1–2 min", icon: "mic" },
] as const;
export type AdventureSlug = typeof ADVENTURES[number]["slug"];
export const adventure = (slug: string) => ADVENTURES.find(item => item.slug === slug);
export interface Scene { id: string; speaker: string; line: string; task: string; tip: string; choices: { label: string; next: string }[]; }
export interface Episode { id: string; title: string; setting: string; scenes: Scene[]; }
export const EPISODES: Episode[] = [
  { id: "arrival", title: "01 · A suitcase, a fresh start", setting: "You have landed in Bristol for your first term. Your suitcase has not.", scenes: [
    { id: "start", speaker: "Maya · airport desk", line: "I'm sorry your bag isn't here. What does it look like, and where are you staying?", task: "Describe your suitcase and explain when you need it.", tip: "A useful description includes colour, size and one distinctive detail.", choices: [{ label: "Arrange delivery to your room", next: "delivery" }, { label: "Collect it at the airport", next: "collect" }] },
    { id: "delivery", speaker: "Maya", line: "We can deliver tomorrow, but reception closes at six. How could we make sure someone receives it?", task: "Suggest a solution and politely confirm the arrangement.", tip: "Could you…? Would it be possible to…?", choices: [{ label: "Ask your new flatmate for help", next: "flatmate" }] },
    { id: "collect", speaker: "Maya", line: "The bag should arrive at ten tomorrow. You'll need your passport and this reference number.", task: "Confirm what to bring and ask how to get back to the airport.", tip: "Check details rather than assuming: Just to confirm…", choices: [{ label: "Plan the trip with your flatmate", next: "flatmate" }] },
    { id: "flatmate", speaker: "Noah · your flatmate", line: "Welcome! That sounds like a difficult first day. What brings you here, and how can I help?", task: "Introduce yourself, explain your plans and ask for one specific favour.", tip: "Connect your explanation to a concrete request.", choices: [{ label: "Finish this chapter", next: "end" }] },
    { id: "end", speaker: "Chapter complete", line: "You have a plan for your suitcase and a new person to turn to. Tomorrow is orientation day.", task: "Reflect: which phrase would you use again?", tip: "This is guided practice, not an assessed exam.", choices: [] },
  ] },
  { id: "orientation", title: "02 · The wrong building", setting: "Orientation starts in twenty minutes. The map and your invitation disagree.", scenes: [
    { id: "start", speaker: "Leah · student guide", line: "The library is on the left. Are you looking for the language-centre welcome session or the general tour?", task: "Explain which event you need and ask for clear directions.", tip: "Mention the event name and your starting point.", choices: [{ label: "Follow the invitation", next: "invite" }, { label: "Check with the language centre", next: "check" }] },
    { id: "invite", speaker: "Reception", line: "That room number belongs to last year's building. The session has moved across campus.", task: "Explain the outdated information without blaming anyone, then ask for the quickest route.", tip: "I may have an older invitation…", choices: [{ label: "Send a message that you may be late", next: "welcome" }] },
    { id: "check", speaker: "Language-centre assistant", line: "You're right to check. We're in Room 204 today. Would you like directions or a meeting point?", task: "Choose what would help you most and confirm the time.", tip: "Repeat the essential details in your own words.", choices: [{ label: "Head to the welcome session", next: "welcome" }] },
    { id: "welcome", speaker: "Dr Patel", line: "Glad you found us. Tell your partner one thing you hope to learn and one question you have about the course.", task: "Introduce your learning goal and ask a useful question.", tip: "Keep the goal specific enough that you can act on it.", choices: [{ label: "Finish this chapter", next: "end" }] },
    { id: "end", speaker: "Chapter complete", line: "You checked your information, found the room and started a conversation.", task: "Reflect: how did you clarify the misunderstanding?", tip: "Try the other route next time.", choices: [] },
  ] },
];
export interface DetectiveCase { id: string; title: string; brief: string; clues: { id: string; type: "letter" | "audio" | "notice"; title: string; text: string }[]; options: string[]; answer: number; explanation: string; }
export const CASES: DetectiveCase[] = [
  { id: "parcel", title: "The parcel that wasn't missing", brief: "A student says a parcel disappeared. Find where it is and explain the apparent contradiction.", clues: [
    { id: "receipt", type: "letter", title: "Delivery receipt · 14:10", text: "Parcel A17 was delivered to the north reception desk. The recipient was not present, so an authorised staff member signed for it." },
    { id: "message", type: "audio", title: "Caretaker's voice note", text: "I collected the deliveries before the desk closed. Anything arriving after two is in the storage cupboard next to the north desk, not in the usual parcel lockers." },
    { id: "notice", type: "notice", title: "Notice by the lockers", text: "Parcel lockers are unavailable today due to maintenance. Please ask north reception for deliveries. Bring your student card and tracking reference." },
  ], options: ["The driver never delivered it", "It is in the cupboard by north reception", "Another student took it"], answer: 1, explanation: "The receipt confirms delivery after 14:00. The voice note says those parcels were moved to the cupboard; the notice explains why the lockers were empty." },
  { id: "meeting", title: "Two times, one meeting", brief: "Three messages seem to give different meeting times. Work out when to arrive and which message supersedes the others.", clues: [
    { id: "email", type: "letter", title: "Invitation · Monday", text: "The film-club meeting is on Thursday at 18:30 in Room 12. Please arrive ten minutes early to set up." },
    { id: "update", type: "audio", title: "Organiser's update · Wednesday", text: "Room 12 is being repaired. We've moved the meeting to Room 8 and delayed the start by half an hour. The ten-minute setup rule is unchanged." },
    { id: "poster", type: "notice", title: "Old poster", text: "Film club: Thursday, 18:30, Room 12. Printed last Friday. Check the organiser's latest message for changes." },
  ], options: ["18:20 in Room 12", "19:00 in Room 8", "18:50 in Room 8"], answer: 2, explanation: "The latest update moves the start from 18:30 to 19:00 and changes the room to 8. Arriving ten minutes early means 18:50." },
];
export const DEBATES = [
  { id: "homework", title: "Should homework be optional?", for: ["Students can choose practice that meets their own needs.", "Some students need structure. How would your approach support them?", "Who might be disadvantaged by optional homework, and what would you change?"], against: ["Regular homework gives everyone a shared practice routine.", "Students have different responsibilities. How would you avoid overloading them?", "What would convince you to make an exception?"], example: "Consider a learner who works after class. Explain a practical policy, not just a slogan." },
  { id: "phones", title: "Should phones be allowed in class?", for: ["Phones can provide quick access to dictionaries and learning tools.", "How would you keep notifications from distracting the class?", "How would you support a learner who does not own a phone?"], against: ["Removing phones may make it easier to concentrate.", "What if a phone is a student's only way to access an assigned resource?", "Could a limited-use rule work better than a complete ban?"], example: "Give a concrete classroom example and explain who benefits or loses." },
  { id: "cities", title: "Should city centres be car-free?", for: ["Fewer cars could make streets safer and cleaner.", "How would people with limited mobility get to essential services?", "Which exception would you allow, and why?"], against: ["Some residents and businesses depend on car access.", "How would you address air quality and pedestrian safety instead?", "What evidence would make you reconsider your position?"], example: "Distinguish residents, delivery drivers and visitors; their needs may differ." },
] as const;
export const RESCUES = [
  { id: "airport", title: "The wrong destination", constraint: "Explain without using the word ‘ticket’.", forbidden: "ticket", rounds: ["The agent thinks you're travelling tomorrow, but your flight is today. Clarify the misunderstanding politely.", "The agent asks for proof, and your phone battery is nearly empty. Explain another way to check your booking.", "The flight leaves soon. Ask for one specific action and confirm what you should do next."], useful: "I think there may have been a misunderstanding… / Could you check…? / Just to confirm…" },
  { id: "invite", title: "A kind but clear no", constraint: "Decline without using the word ‘busy’.", forbidden: "busy", rounds: ["A classmate invites you to an event you cannot attend. Decline kindly without inventing an excuse.", "They insist it will only take an hour. Restate your boundary without sounding angry.", "Suggest a realistic alternative while making it clear you are not attending this event."], useful: "Thank you for thinking of me… / I won't be able to… / How about…?" },
  { id: "explain", title: "Explain it simply", constraint: "Explain a cloud backup without using the words ‘cloud’ or ‘server’.", forbidden: "cloud|server", rounds: ["A relative asks how their photos can survive losing their phone. Explain using a familiar comparison.", "They worry that deleting a photo on the phone deletes every copy. Explain why settings and the service's rules matter.", "Give one practical action they can take to check that a backup really exists."], useful: "Imagine a second copy… / It depends on… / You can check by…" },
] as const;
export const CAPSULE_PROMPTS = [
  { id: "home", text: "Describe a place where you feel at home. What makes it special?" },
  { id: "skill", text: "Describe a skill you want to learn and how you would start." },
  { id: "change", text: "Describe a change that made your life better. Why did it matter?" },
] as const;
