export const classroomEnabled = () => process.env.LIVE_CLASSROOM === "on";
export const calibrationEnabled = () => process.env.TEACHER_CALIBRATION === "on";
export class ToolError extends Error { constructor(message: string, public status = 400) { super(message); } }
export const criteria = ["taskAchievement", "coherenceCohesion", "lexicalResource", "grammarAccuracy"] as const;
export const criterionNames: Record<string, string> = { taskAchievement: "Task Achievement / Response", coherenceCohesion: "Coherence & Cohesion", lexicalResource: "Lexical Resource", grammarAccuracy: "Grammatical Range & Accuracy" };
export type Scores = Record<typeof criteria[number], number>;
export const signalNames = { UNDERSTOOD: "I understand", EXAMPLE: "I need an example", QUESTION: "I have a question" } as const;
export type SignalKind = keyof typeof signalNames;
export function object(raw: unknown): Record<string, unknown> { if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new ToolError("Send a valid command."); return raw as Record<string, unknown>; }
export function text(value: unknown, label: string, min: number, max: number): string { if (typeof value !== "string") throw new ToolError(`${label} is required.`); const result = value.trim(); if (result.length < min || result.length > max) throw new ToolError(`${label} must be ${min}–${max} characters.`); return result; }
export function identifier(value: unknown): string { if (typeof value !== "string" || !/^[a-zA-Z0-9_-]{3,100}$/.test(value)) throw new ToolError("Choose a valid record."); return value; }
export function scores(raw: unknown): Scores { const input = object(raw); return Object.fromEntries(criteria.map(key => { const n = input[key]; if (typeof n !== "number" || !Number.isFinite(n) || n < 0 || n > 9 || n * 2 % 1 !== 0) throw new ToolError("Choose all four criteria in half-band steps from 0 to 9."); return [key, n]; })) as Scores; }
export function poll(raw: unknown) { const p = object(raw); if (!Array.isArray(p.options) || p.options.length < 2 || p.options.length > 4) throw new ToolError("Add 2–4 answer options."); const options = p.options.map(v => text(v, "Option", 1, 200)); if (new Set(options.map(s => s.toLowerCase())).size !== options.length) throw new ToolError("Answer options must be different."); const correct = p.correct; if (!Number.isInteger(correct) || Number(correct) < 0 || Number(correct) >= options.length) throw new ToolError("Choose the correct option."); return { prompt: text(p.prompt, "Question", 5, 600), options, correct: Number(correct), explanation: text(p.explanation, "Explanation", 10, 1200) }; }
export function reference(raw: unknown) { const p = object(raw); if (p.module !== "TASK1" && p.module !== "TASK2") throw new ToolError("Choose Writing Task 1 or Task 2."); if (p.confirmed !== true) throw new ToolError("Confirm the reference is agreed and contains no identifying learner data."); const body = text(p.body, "Reference response", 100, 20000); const rationale = text(p.rationale, "Criteria rationale", 30, 4000); return { title: text(p.title, "Reference title", 3, 120), module: p.module, prompt: text(p.prompt, "Task", 20, 3000), body, scores: scores(p.scores), rationale }; }
export function rating(raw: unknown, body: string) { const p = object(raw); const quote = text(p.quote, "Evidence quote", 10, 500); if (!body.includes(quote)) throw new ToolError("Quote an exact passage from the reference response."); return { scores: scores(p.scores), quote, rationale: text(p.rationale, "Your reasoning", 20, 2000) }; }
export function comparison(own: Scores, reference: Scores) { return criteria.map(key => ({ key, label: criterionNames[key], own: own[key], reference: reference[key], difference: own[key] - reference[key] })); }
