/** Actual components + real browser MediaRecorder/IndexedDB; synthetic accounts, no providers/production. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const {build}=require('esbuild');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.OUT_DIR||'/data/averna-adventures-entry-screens');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'averna-adventures-'));fs.mkdirSync(out,{recursive:true});let browser,server;const report=[];
try{
 const stub=`import React from 'react';export default function Link({href,children,prefetch,scroll,...props}){return <a href={href} {...props}>{children}</a>;}export function usePathname(){return '/studio/adventures';}`;
 await build({entryPoints:[path.join(root,'tests/fixtures/adventures.tsx')],bundle:true,jsx:'automatic',format:'iife',platform:'browser',outfile:path.join(temp,'app.js'),tsconfig:path.join(root,'tsconfig.json'),alias:{'@':root,react:path.join(root,'node_modules/react'),'react-dom':path.join(root,'node_modules/react-dom')},plugins:[{name:'qa-next',setup(b){b.onResolve({filter:/^next\/(navigation|link)$/},()=>({path:'stub',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:stub,loader:'tsx',resolveDir:root}));}}]});
 execFileSync(process.execPath,[path.join(root,'node_modules/tailwindcss/lib/cli.js'),'-i',path.join(root,'app/globals.css'),'-o',path.join(temp,'globals.css'),'--minify'],{cwd:root,stdio:'pipe'});
 const html='<!doctype html><html class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/globals.css" rel="stylesheet"><link href="/app.css" rel="stylesheet"><script>if(new URLSearchParams(location.search).get("theme")==="light")document.documentElement.className="light";</script></head><body><div id="root"></div><script src="/app.js"></script></body></html>';
 server=http.createServer((req,res)=>{const p=new URL(req.url,'http://127.0.0.1').pathname;const file=['/app.js','/app.css','/globals.css'].includes(p)?p.slice(1):null;res.setHeader('Content-Type',file?.endsWith('.css')?'text/css':file?'application/javascript':'text/html');res.end(file?fs.readFileSync(path.join(temp,file)):html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/local/bin/chromium',headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 
 async function audit(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow');const small=await page.locator('.adventure-space button:visible,.adventure-space summary:visible,.adventure-space a.adv-button:visible').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height<43.5).map(n=>n.textContent));assert.deepEqual(small,[],name+' touch targets');}
 async function shot(page,name){await audit(page,name);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
 // Every route checked at both phone widths and desktop in both themes. Screenshots select distinct layouts/states.
 for(const mode of ['entry'])for(const theme of ['dark','light'])for(const width of [320,390,1440]){
 const context=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce',isMobile:width<768,hasTouch:width<768,permissions:['microphone']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/?mode=${mode}&theme=${theme}&sharing=${mode==='teacher'?'on':'off'}`);await page.waitForTimeout(150);await audit(page,`${mode}-${theme}-${width}`);assert.deepEqual(errors,[]);
 if(true)await shot(page,`${mode}-${theme}-${width}`);
 assert.equal(await page.getByRole("link",{name:"Explore Adventures"}).getAttribute("href"),"/studio/adventures");
 if(width===390 && theme==="dark"){await page.getByRole("link",{name:"Explore Adventures"}).click();await page.waitForURL("**/studio/adventures");await page.locator(".adv-hub-card").first().waitFor();assert.equal(await page.locator(".adv-hub-card").count(),6);}
 report.push({mode,theme,width,noOverflow:true,noRuntimeErrors:true});await context.close();}
 console.log('PASS: dashboard Adventures entry at 320/390/1440 in both themes; no overflow or runtime exceptions. Screenshots require individual inspection.');
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
