/** Actual components + real browser MediaRecorder/IndexedDB; synthetic accounts, no providers/production. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const {build}=require('esbuild');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.OUT_DIR||'/data/averna-adventures-screens');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'averna-adventures-'));fs.mkdirSync(out,{recursive:true});let browser,server;const report=[];
try{
 const stub=`import React from 'react';export default function Link({href,children,prefetch,scroll,...props}){return <a href={href} {...props}>{children}</a>;}export function usePathname(){return '/studio/adventures';}`;
 await build({entryPoints:[path.join(root,'tests/fixtures/adventures.tsx')],bundle:true,jsx:'automatic',format:'iife',platform:'browser',outfile:path.join(temp,'app.js'),tsconfig:path.join(root,'tsconfig.json'),alias:{'@':root,react:path.join(root,'node_modules/react'),'react-dom':path.join(root,'node_modules/react-dom')},plugins:[{name:'qa-next',setup(b){b.onResolve({filter:/^next\/(navigation|link)$/},()=>({path:'stub',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:stub,loader:'tsx',resolveDir:root}));}}]});
 execFileSync(process.execPath,[path.join(root,'node_modules/tailwindcss/lib/cli.js'),'-i',path.join(root,'app/globals.css'),'-o',path.join(temp,'globals.css'),'--minify'],{cwd:root,stdio:'pipe'});
 const html='<!doctype html><html class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/globals.css" rel="stylesheet"><link href="/app.css" rel="stylesheet"><script>if(new URLSearchParams(location.search).get("theme")==="light")document.documentElement.className="light";</script></head><body><div id="root"></div><script src="/app.js"></script></body></html>';
 server=http.createServer((req,res)=>{const p=new URL(req.url,'http://127.0.0.1').pathname;const file=['/app.js','/app.css','/globals.css'].includes(p)?p.slice(1):null;res.setHeader('Content-Type',file?.endsWith('.css')?'text/css':file?'application/javascript':'text/html');res.end(file?fs.readFileSync(path.join(temp,file)):html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/local/bin/chromium',headless:true,args:['--no-sandbox','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 const reply='I would like to explain my situation and ask for your help.';
 async function audit(page,name){assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,name+' overflow');const small=await page.locator('.adventure-space button:visible,.adventure-space summary:visible').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height<43.5).map(n=>n.textContent));assert.deepEqual(small,[],name+' touch targets');}
 async function shot(page,name){await audit(page,name);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
 // Every route checked at both phone widths and desktop in both themes. Screenshots select distinct layouts/states.
 for(const mode of ['hub','series','detective','debate','rescue','builder','capsules','teacher'])for(const theme of ['dark','light'])for(const width of [320,390,1440]){
 const context=await browser.newContext({viewport:{width,height:844},reducedMotion:'reduce',isMobile:width<768,hasTouch:width<768,permissions:['microphone']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`${base}/?mode=${mode}&theme=${theme}&sharing=${mode==='teacher'?'on':'off'}`);await page.waitForTimeout(150);await audit(page,`${mode}-${theme}-${width}`);assert.deepEqual(errors,[]);
 if(width===(theme==='dark'?390:320) || width===1440 && theme==='light' && ['hub','builder','capsules','teacher'].includes(mode))await shot(page,`${mode}-${theme}-${width}`);
 report.push({mode,theme,width,noOverflow:true,noRuntimeErrors:true});await context.close();}
 async function open(mode,extra=''){const context=await browser.newContext({viewport:{width:390,height:844},permissions:['microphone'],reducedMotion:'reduce'});const page=await context.newPage();await page.goto(`${base}/?mode=${mode}${extra}`);return {context,page};}
 {const {context,page}=await open('series');await page.getByLabel('Your response').fill(reply);await page.getByRole('button',{name:/Collect it at the airport/}).click();await page.getByLabel('Your response').fill(reply);await page.locator('.adv-actions .adv-primary').first().click();await page.getByLabel('Your response').fill(reply);await page.locator('.adv-actions .adv-primary').first().click();await page.getByText('A chapter worth remembering').waitFor();await page.getByText('Your replies',{exact:true}).click();await shot(page,'series-complete');await page.reload();await page.getByText('A chapter worth remembering').waitFor();await page.evaluate(()=>window.__setOwner('synthetic-bob'));await page.getByLabel('Your response').waitFor();assert.equal(await page.getByLabel('Your response').inputValue(),'');await context.close();}
 {const {context,page}=await open('detective');for(const d of await page.locator('details.adv-evidence > summary').all())await d.click();await page.getByText('Show transcript',{exact:true}).click();await page.getByLabel('It is in the cupboard by north reception').check();await page.getByLabel('Explain your evidence').fill(reply);await page.getByRole('button',{name:'Check my conclusion'}).click();await page.getByText('Your conclusion matches the evidence').waitFor();await shot(page,'detective-complete');await context.close();}
 for(const mode of ['debate','rescue']){const {context,page}=await open(mode);for(let i=0;i<3;i++){await page.getByLabel('Your response').fill(reply);await page.getByRole('button',{name:mode==='debate'?(i===2?'Review my argument':'Next challenge'):(i===2?'Reflect on my replies':'Reveal the twist')}).click();}await shot(page,mode+'-complete');await context.close();}
 {const {context,page}=await open('builder','&sharing=on&theme=light');const payload=await page.evaluate(()=>window.__qaPayload);await page.getByLabel('Workshop title').fill(payload.title);await page.getByLabel('Your passage').fill(payload.passage);await page.getByLabel('Question text').fill(payload.questions[0].prompt);for(let i=0;i<4;i++)await page.getByLabel('Option '+String.fromCharCode(65+i),{exact:true}).fill(payload.questions[0].options[i]);await page.getByLabel('Correct option').selectOption('2');await page.getByLabel('Why is this answer correct?').fill(payload.questions[0].explanation);await page.getByLabel('I wrote this passage',{exact:false}).check();await page.getByRole('button',{name:'Preview my challenge'}).click();await page.getByLabel('At nine',{exact:true}).check();await page.getByRole('button',{name:'Check against the answer key'}).click();await page.getByRole('button',{name:'Send for teacher review'}).click();await page.getByText(/Submitted for your class teacher/).waitFor();await shot(page,'builder-preview');assert.equal((await page.evaluate(()=>window.__mutations)).length,1);await context.close();}
 {const {context,page}=await open('teacher','&sharing=on&theme=light');const approve=page.getByRole('button',{name:'Approve for class'});assert.equal(await approve.isDisabled(),true);await page.getByText('Inspect passage, questions and key',{exact:true}).click();await shot(page,'teacher-inspect');await page.getByLabel('I checked the passage',{exact:false}).check();await approve.click();await page.getByText('approved · revision 2').waitFor();await shot(page,'teacher-approved');const writes=await page.evaluate(()=>window.__mutations);assert.equal(writes.length,1);assert.equal(writes[0].body.version,1);await context.close();}
 {const {context,page}=await open('capsules');await page.getByRole('button',{name:'Record up to 2 minutes'}).click();await page.getByText(/Recording ·/).waitFor();await page.waitForTimeout(1250);await page.getByRole('button',{name:'Stop and preview'}).click();await page.getByText(/Unsaved preview ·/).waitFor();assert.equal(await page.getByRole('button',{name:'Save capsule on this device'}).isDisabled(),true);await shot(page,'capsules-unsaved');await page.getByLabel('A note to your future self').fill('Synthetic recording today');await page.getByLabel('Save this audio on this device',{exact:false}).check();await page.getByRole('button',{name:'Save capsule on this device'}).click();await page.getByText(/1\/8 saved recordings/).waitFor();await page.reload();await page.getByText(/1\/8 saved recordings/).waitFor();await page.getByRole('button',{name:'Record up to 2 minutes'}).click();await page.getByText(/Recording ·/).waitFor();await page.waitForTimeout(1200);await page.getByRole('button',{name:'Stop and preview'}).click();await page.getByText(/Unsaved preview ·/).waitFor();await page.getByLabel('Save this audio on this device',{exact:false}).check();await page.getByRole('button',{name:'Save capsule on this device'}).click();await page.getByText(/2\/8 saved recordings/).waitFor();const clips=await page.evaluate(async()=>{const items=await window.__audioStore.listCapsules('synthetic-alice');return items.map(i=>({id:i.id,size:i.audio.size,type:i.audio.type}));});assert.equal(clips.length,2);assert.ok(clips.every(c=>c.size>0&&c.type.startsWith('audio/')));await page.getByLabel('Earlier recording').selectOption(clips[1].id);await page.getByLabel('Later recording').selectOption(clips[0].id);assert.equal(await page.locator('audio').count(),4);await page.locator('audio').first().evaluate(async audio=>{await audio.play();await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Audio did not play to completion')),6000);audio.onended=()=>{clearTimeout(timer);resolve();};audio.onerror=()=>{clearTimeout(timer);reject(new Error('Audio decode failed'));};});});await shot(page,'capsules-compare');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export audio'}).first().click();assert.match((await download).suggestedFilename(),/\.webm$/);await page.getByRole('button',{name:'Delete recording',exact:true}).first().click();await page.getByRole('button',{name:'Delete permanently',exact:true}).click();await page.getByText(/1\/8 saved recordings/).waitFor();await page.evaluate(()=>window.__setOwner('synthetic-bob'));await page.getByText(/0\/8 saved recordings/).waitFor();await page.evaluate(()=>window.__setOwner('synthetic-alice'));await page.getByText(/1\/8 saved recordings/).waitFor();
 const capacity=await page.evaluate(async()=>{const store=window.__audioStore;const first=(await store.listCapsules('synthetic-alice'))[0];for(let i=1;i<8;i++)await store.saveCapsule('synthetic-alice',{...first,id:'synthetic-'+i});try{await store.saveCapsule('synthetic-alice',{...first,id:'overflow'});return false;}catch{return (await store.listCapsules('synthetic-alice')).length===8;}});assert.equal(capacity,true);await context.close();}
 {const {context,page}=await open('capsules');await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await page.getByRole('button',{name:'Record up to 2 minutes'}).click();await page.getByText(/Microphone permission was denied/).waitFor();assert.equal(await page.locator('audio').count(),0);await context.close();}
 {const {context,page}=await open('capsules');await page.evaluate(()=>{const get=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async opts=>{const stream=await get(opts);window.__qaTracks=stream.getTracks();return stream;};});await page.getByRole('button',{name:'Record up to 2 minutes'}).click();await page.getByText(/Recording ·/).waitFor();await page.evaluate(()=>window.__setOwner('synthetic-bob'));await page.getByText(/0\/8 saved recordings/).waitFor();assert.equal(await page.evaluate(()=>window.__qaTracks.every(t=>t.readyState==='ended')),true);assert.equal(await page.locator('audio').count(),0);await context.close();}
 {const {context,page}=await open('rescue');await page.evaluate(()=>{Storage.prototype.setItem=()=>{throw new Error('Synthetic quota');};});await page.getByLabel('Your response').fill(reply);await page.getByText(/Device storage is full/).waitFor();assert.equal(await page.getByLabel('Your response').inputValue(),reply);await context.close();}
 {const {context,page}=await open('builder','&sharing=on&state=offline');await page.getByText('My submissions',{exact:true}).waitFor();await page.getByText('Class sharing request failed. Your device draft is unchanged.').first().waitFor();await context.close();}
 fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({layouts:report,flows:['branch completion/reload/owner','all detective clues/transcript/key','debate three rounds','rescue three twists','builder author-preview-submit','explicit teacher approval','real MediaRecorder/IndexedDB/reload/compare/export/delete/owner/8-limit','microphone denial','owner-change stops actual microphone tracks','device quota keeps typed work','offline class lists fail safely']},null,2));console.log('PASS: 48 responsive route/theme/size checks + 11 interactive flows. Actual Chromium MediaRecorder and IndexedDB, synthetic content only. Screenshots require individual inspection.');
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
