/** Actual exam components with synthetic papers, mocked transport and real WAV playback. No account/provider/DB. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict');const {execFileSync}=require('node:child_process');const {build}=require('esbuild');const {chromium}=require('playwright');const root=path.resolve(__dirname,'..');
(async()=>{let browser,server;const temp=fs.mkdtempSync(path.join(os.tmpdir(),'averna-group-'));const out=path.resolve(process.env.OUT_DIR||'/data/averna-group-screens');fs.mkdirSync(out,{recursive:true});try{
const stub=`import React from 'react'; export default function Link({href,children,prefetch,...props}) {return <a href={href} {...props}>{children}</a>;} export function redirect(p){throw new Error('Unexpected fixture redirect '+p);} export function useRouter(){return {refresh:()=>window.__refresh?.(),push:p=>{window.__navigation=p},replace:p=>{window.__navigation=p}};}`;
await build({entryPoints:[path.join(root,'tests/fixtures/group-mock.tsx')],bundle:true,jsx:'automatic',format:'iife',platform:'browser',outfile:path.join(temp,'app.js'),tsconfig:path.join(root,'tsconfig.json'),alias:{'@':root,react:path.join(root,'node_modules/react'),'react-dom':path.join(root,'node_modules/react-dom')},plugins:[{name:'qa-next',setup(b){b.onResolve({filter:/^next\/(navigation|link)$/},()=>({path:'stub',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},()=>({contents:stub,loader:'tsx',resolveDir:root}));}}]});
execFileSync(process.execPath,[path.join(root,'node_modules/tailwindcss/lib/cli.js'),'-i',path.join(root,'app/globals.css'),'-o',path.join(temp,'app.css'),'--minify'],{cwd:root,stdio:'pipe'});
const html='<!doctype html><html class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link href="/app.css" rel="stylesheet"><script>localStorage.setItem("averna_theme",new URLSearchParams(location.search).get("theme")||"dark");</script></head><body><div id="root"></div><script src="/app.js"></script></body></html>';
const wav=Buffer.alloc(44+16000*2*6);wav.write('RIFF',0);wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(16000,24);wav.writeUInt32LE(32000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(wav.length-44,40);for(let i=0;i<16000*6;i++)wav.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*440/16000)*4000),44+i*2);
server=http.createServer((req,res)=>{const p=new URL(req.url,'http://x').pathname;if(p==='/tone.wav'){res.setHeader('Content-Type','audio/wav');res.setHeader('Content-Length',wav.length);res.end(wav);return;}const file=p==='/app.js'?'app.js':p==='/app.css'?'app.css':null;res.setHeader('Content-Type',file?.endsWith('css')?'text/css':file?'application/javascript':'text/html');res.end(file?fs.readFileSync(path.join(temp,file)):html);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
browser=await chromium.launch({executablePath:execFileSync('which',['chromium'],{encoding:'utf8'}).trim(),headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});const results=[];
for(const [kind,width,theme] of [['list',1440,'light'],['teacher',390,'dark'],['student',390,'light'],['review',1440,'dark'],['review',390,'light'],['join',320,'dark']]){
 const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce',isMobile:width<768,hasTouch:width<768});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.goto(`${base}/?kind=${kind}&theme=${theme}`);await page.waitForTimeout(700);
 if(kind==='list'){await page.getByLabel('Your class').selectOption('g');await page.getByLabel('Session title').fill('Saturday Academic Mock');assert.equal(await page.getByRole('button',{name:'Open lobby'}).isEnabled(),true);await page.getByLabel('Paper distribution').selectOption('balanced');assert.match(await page.locator('main').innerText(),/explicitly permits repeats/);}
 if(kind==='teacher'){await page.getByRole('button',{name:'Start everyone · 15s countdown'}).click();await page.getByRole('button',{name:'Collect and end session'}).waitFor();const w=await page.evaluate(()=>window.__writes);assert.equal(w[0].input.action,'start');assert.equal(w[0].input.version,0);}
 if(kind==='student'){assert.equal(await page.getByRole('button',{name:'Confirm ready'}).isDisabled(),true);assert.equal(await page.getByRole('checkbox').isDisabled(),true);await page.getByRole('button',{name:'Play headphone check'}).click();await page.waitForTimeout(350);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Confirm ready'}).click();await page.getByRole('button',{name:'Ready — waiting for teacher'}).waitFor();}
 if(kind==='review'){await page.getByRole('button',{name:'Review',exact:true}).first().click();await page.getByRole('heading',{name:'Review · Dilnoza Karimova'}).waitFor();assert.equal(await page.getByRole('button',{name:'Publish result to student'}).isDisabled(),true);assert.equal(await page.getByRole('img',{name:'Bar chart'}).count(),1);
 if(width===1440){await page.getByRole('button',{name:'Save private review draft'}).click();const d=await page.evaluate(()=>window.__writes[0].input);assert.equal(d.publish,false);assert.deepEqual(d.task1,{});await page.getByRole('button',{name:'Review',exact:true}).first().click();await page.getByRole('heading',{name:'Review · Dilnoza Karimova'}).waitFor();}
 for(const input of await page.locator('input[type=number]').all())await input.fill('7');await page.getByRole('checkbox').check();await page.getByLabel('Teacher feedback').fill('Strong ideas. Improve comparison and paragraph development.');await page.evaluate(()=>window.__conflict=true);await page.getByRole('button',{name:'Save private review draft'}).click();await page.getByRole('alert').filter({hasText:'Another review saved first'}).waitFor();assert.equal(await page.locator('input[type=number]').first().inputValue(),'7');assert.equal(await page.getByRole('button',{name:'Publish result to student'}).isEnabled(),true);
 }
 if(kind==='join'){await page.getByLabel('Teacher’s session code').fill('ABC12345');await page.getByRole('button',{name:'Join session'}).click();await page.getByRole('alert').waitFor();}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),kind+' overflow');assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,`${kind}-${width}-${theme}.png`),fullPage:true});
 if(kind==='review'){await page.getByRole('button',{name:'Publish result to student'}).click();await page.getByText('Published',{exact:true}).waitFor();const last=await page.evaluate(()=>window.__writes.at(-1).input);assert.equal(last.publish,true);assert.equal(last.speaking.pronunciation,7);assert.equal(last.speakingConducted,true);}
 results.push({kind,width,theme});await context.close();}
console.log(JSON.stringify({passed:results.length,cases:results},null,2));}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
