/**
 * Averna's preset avatars — self-hosted SVGs in public/avatars/, generated by
 * scripts/generate-avatars.mjs (re-run it to tweak the designs).
 *
 * The old gallery used DiceBear URLs. Those are retired: any stored DiceBear
 * URL is shown as one of the new presets instead (stable per seed, so a user
 * keeps "their" character), until they pick a new avatar themselves.
 */

export type AvatarGroup = { key: "students" | "aurora"; label: string; items: string[] };

const range = (prefix: string, n: number) =>
  Array.from({ length: n }, (_, i) => `/avatars/${prefix}-${String(i + 1).padStart(2, "0")}.svg`);

export const STUDENT_AVATARS = range("student", 24);
export const AURORA_AVATARS = range("aurora", 12);

export const AVATAR_GROUPS: AvatarGroup[] = [
  { key: "students", label: "Students", items: STUDENT_AVATARS },
  { key: "aurora", label: "Aurora", items: AURORA_AVATARS },
];

export const PRESET_AVATARS = [...STUDENT_AVATARS, ...AURORA_AVATARS];

/** Only our own preset paths are accepted as non-URL avatars. */
export const PRESET_AVATAR_RE = /^\/avatars\/(student|aurora)-\d{2}\.svg$/;

function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * The image URL to actually render for a stored avatar value.
 * - null/empty → null (callers show initials)
 * - retired DiceBear URL → a new student preset, chosen by its seed
 * - anything else (preset path, uploaded data URL, OAuth photo) → unchanged
 */
export function avatarSrc(image?: string | null): string | null {
  if (!image) return null;
  if (image.includes("api.dicebear.com")) {
    const seed = /[?&]seed=([^&]+)/.exec(image)?.[1] ?? image;
    return STUDENT_AVATARS[hash(decodeURIComponent(seed)) % STUDENT_AVATARS.length];
  }
  return image;
}
