export interface Flashcard {
  word: string;
  meaning: string;
  example: string;
  uz: string;
}

export interface Deck {
  id: string;
  name: string;
  emoji: string;
  band: string;
  cards: Flashcard[];
}

export const DECKS: Deck[] = [
  {
    id: "education",
    name: "Education",
    emoji: "🎓",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Curriculum", meaning: "The subjects that make up a course of study.", example: "The school updated its curriculum to include coding.", uz: "oʻquv dasturi" },
      { word: "Tuition", meaning: "Teaching, or the money paid for teaching.", example: "Tuition fees have risen sharply in recent years.", uz: "oʻqish toʻlovi / dars berish" },
      { word: "Scholarship", meaning: "Financial award given to a student.", example: "She won a full scholarship to study in London.", uz: "stipendiya" },
      { word: "Assessment", meaning: "Formal evaluation of a student's ability.", example: "Continuous assessment reduces exam stress.", uz: "baholash" },
      { word: "Discipline", meaning: "A branch of knowledge; also self-control.", example: "Engineering is a demanding academic discipline.", uz: "fan sohasi / intizom" },
      { word: "Literacy", meaning: "The ability to read and write.", example: "Adult literacy rates have improved worldwide.", uz: "savodxonlik" },
      { word: "Mentor", meaning: "An experienced person who advises another.", example: "Her mentor guided her through her first job.", uz: "murabbiy / ustoz" },
      { word: "Vocational", meaning: "Relating to a specific occupation or trade.", example: "He chose a vocational course in electronics.", uz: "kasb-hunarga oid" },
      { word: "Enroll", meaning: "To officially register on a course.", example: "Over 500 students enrolled in the new program.", uz: "roʻyxatga olinmoq / qabul qilinmoq" },
      { word: "Undergraduate", meaning: "A university student before a first degree.", example: "As an undergraduate, she studied psychology.", uz: "bakalavr talabasi" },
      { word: "Postgraduate", meaning: "A student studying after a first degree.", example: "Postgraduate research often requires funding.", uz: "magistratura talabasi" },
      { word: "Compulsory", meaning: "Required by law or rule.", example: "Attendance at the lecture is compulsory.", uz: "majburiy" },
      { word: "Extracurricular", meaning: "Outside the regular course of study.", example: "Chess is a popular extracurricular activity.", uz: "darsdan tashqari" },
      { word: "Faculty", meaning: "A department in a university; also the teaching staff.", example: "She teaches in the Faculty of Arts.", uz: "fakultet / professor-oʻqituvchilar" },
      { word: "Thesis", meaning: "A long essay for a university degree.", example: "He is writing his master's thesis on AI.", uz: "dissertatsiya / ilmiy ish" },
      { word: "Plagiarism", meaning: "Copying someone else's work as your own.", example: "The university has strict rules against plagiarism.", uz: "koʻchirmakashlik / plagiat" },
      { word: "Lecture", meaning: "An educational talk to an audience.", example: "The professor gave a lecture on climate change.", uz: "maʼruza" },
      { word: "Seminar", meaning: "A small teaching group for discussion.", example: "The seminar focused on essay writing.", uz: "seminar" },
      { word: "Peer", meaning: "A person of the same age or status.", example: "Students learn a lot from their peers.", uz: "tengdosh / hamkasb" },
      { word: "Rigorous", meaning: "Extremely thorough and demanding.", example: "The course has a rigorous examination system.", uz: "qatʼiy / puxta" },
      { word: "Comprehensive", meaning: "Complete; covering everything.", example: "The report gives a comprehensive overview.", uz: "keng qamrovli / toʻliq" },
      { word: "Intellect", meaning: "The ability to think and understand.", example: "His intellect impressed all his teachers.", uz: "aql-idrok" },
      { word: "Aptitude", meaning: "A natural ability for something.", example: "She has an aptitude for languages.", uz: "qobiliyat / iqtidor" },
      { word: "Fluency", meaning: "The ability to speak a language easily.", example: "Reading daily improves your fluency.", uz: "ravonlik" },
      { word: "Retention", meaning: "The ability to remember information.", example: "Sleep helps with memory retention.", uz: "eslab qolish qobiliyati" },
      { word: "Cognitive", meaning: "Relating to thinking and understanding.", example: "Puzzles improve cognitive skills in children.", uz: "kognitiv / fikrlashga oid" },
      { word: "Pedagogy", meaning: "The method and practice of teaching.", example: "Modern pedagogy focuses on the learner.", uz: "pedagogika" },
      { word: "Alumni", meaning: "Former students of a school or university.", example: "The alumni network is very supportive.", uz: "bitiruvchilar" },
      { word: "Dissertation", meaning: "A long piece of writing for a higher degree.", example: "Her dissertation was praised by the examiners.", uz: "dissertatsiya" },
      { word: "Autonomy", meaning: "The freedom to act independently.", example: "Universities value academic autonomy.", uz: "mustaqillik" },
    ],
  },
  {
    id: "environment",
    name: "Environment",
    emoji: "🌍",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Sustainable", meaning: "Able to continue without damaging the environment.", example: "We need sustainable energy sources.", uz: "barqaror / ekologik toza" },
      { word: "Emissions", meaning: "Gases sent out into the air.", example: "Cars produce harmful emissions.", uz: "chiqindi gazlar" },
      { word: "Conservation", meaning: "The protection of nature.", example: "Wildlife conservation is essential.", uz: "muhofaza qilish" },
      { word: "Renewable", meaning: "Naturally replaced, like sun or wind.", example: "Renewable energy is becoming cheaper.", uz: "qayta tiklanuvchi" },
      { word: "Pollution", meaning: "Harmful substances in the environment.", example: "Air pollution affects millions of people.", uz: "ifloslanish" },
      { word: "Deforestation", meaning: "Cutting down large areas of forest.", example: "Deforestation threatens many species.", uz: "oʻrmonlar kesilishi" },
      { word: "Habitat", meaning: "The natural home of an animal or plant.", example: "Pandas are losing their habitat.", uz: "yashash muhiti" },
      { word: "Biodiversity", meaning: "The variety of life in an area.", example: "Rainforests have rich biodiversity.", uz: "biologik xilma-xillik" },
      { word: "Ecosystem", meaning: "A community of living things and their environment.", example: "Coral reefs form a fragile ecosystem.", uz: "ekotizim" },
      { word: "Endangered", meaning: "At risk of dying out completely.", example: "Tigers are an endangered species.", uz: "yoʻqolib ketish arafasida" },
      { word: "Extinction", meaning: "When a species dies out completely.", example: "Climate change is speeding up extinction.", uz: "yoʻq boʻlish" },
      { word: "Greenhouse gas", meaning: "A gas that traps heat in the atmosphere.", example: "CO₂ is the main greenhouse gas.", uz: "issiqxona gazi" },
      { word: "Carbon footprint", meaning: "The total CO₂ a person or activity produces.", example: "Cycling reduces your carbon footprint.", uz: "karbon izi" },
      { word: "Ecological", meaning: "Relating to nature and the environment.", example: "Plastic waste is an ecological disaster.", uz: "ekologik" },
      { word: "Contamination", meaning: "Making something dirty or poisonous.", example: "The river suffered oil contamination.", uz: "ifloslanish / zaharlanish" },
      { word: "Erosion", meaning: "The gradual wearing away of soil or rock.", example: "Trees prevent soil erosion on hillsides.", uz: "yemirilish / eroziya" },
      { word: "Fossil fuels", meaning: "Fuels like coal, oil and gas.", example: "Fossil fuels are the largest source of emissions.", uz: "qazilma yoqilgʻi" },
      { word: "Global warming", meaning: "The gradual rise in Earth's temperature.", example: "Global warming melts polar ice.", uz: "global isish" },
      { word: "Recycle", meaning: "To process waste for reuse.", example: "It's easy to recycle paper and plastic.", uz: "qayta ishlash" },
      { word: "Landfill", meaning: "A place where waste is buried.", example: "Landfills release methane gas.", uz: "chiqindilar poligoni" },
      { word: "Wildlife", meaning: "Wild animals and plants.", example: "The park protects local wildlife.", uz: "yovvoyi tabiat" },
      { word: "Preserve", meaning: "To protect from damage or loss.", example: "We must preserve ancient forests.", uz: "asrash / saqlash" },
      { word: "Depletion", meaning: "Reduction to almost nothing.", example: "Ozone depletion causes health risks.", uz: "kamayib ketish" },
      { word: "Pesticide", meaning: "Chemicals used to kill insects on crops.", example: "Pesticides can harm bees.", uz: "pestitsid / zaharli modda" },
      { word: "Organic", meaning: "Grown without synthetic chemicals.", example: "Organic farming avoids pesticides.", uz: "organik / kimyoviy moddasiz" },
      { word: "Drought", meaning: "A long period without rain.", example: "Drought has damaged this year's harvest.", uz: "qurgʻoqchilik" },
      { word: "Flood", meaning: "A large flow of water over dry land.", example: "The flood destroyed hundreds of homes.", uz: "toshqin" },
      { word: "Solar power", meaning: "Energy from the sun.", example: "Solar power now heats many homes.", uz: "quyosh energiyasi" },
      { word: "Wind farm", meaning: "A group of wind turbines making electricity.", example: "The wind farm powers 20,000 homes.", uz: "shamol elektr stansiyasi" },
      { word: "Emission-free", meaning: "Producing no polluting gases.", example: "Electric cars aim to be emission-free.", uz: "chiqindisiz" },
    ],
  },
  {
    id: "technology",
    name: "Technology",
    emoji: "💻",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Innovation", meaning: "A new method, idea, or product.", example: "The company is known for innovation.", uz: "yangilik / innovatsiya" },
      { word: "Automation", meaning: "Using machines to do work.", example: "Automation has changed manufacturing.", uz: "avtomatlashtirish" },
      { word: "Digital", meaning: "Relating to computer technology.", example: "We live in a digital age.", uz: "raqamli" },
      { word: "Device", meaning: "A piece of equipment for a purpose.", example: "Mobile devices are everywhere.", uz: "qurilma" },
      { word: "Efficient", meaning: "Working well without waste.", example: "The new system is far more efficient.", uz: "samarali" },
      { word: "Network", meaning: "A group of connected computers or people.", example: "The social network has millions of users.", uz: "tarmoq" },
      { word: "Cutting-edge", meaning: "The most advanced; latest.", example: "They use cutting-edge technology.", uz: "eng ilgʻor" },
      { word: "Obsolete", meaning: "No longer used; out of date.", example: "Fax machines are now obsolete.", uz: "eskirgan" },
      { word: "Artificial intelligence", meaning: "Machines that can think like humans.", example: "Artificial intelligence powers voice assistants.", uz: "sunʼiy intellekt" },
      { word: "Algorithm", meaning: "A set of steps a computer follows.", example: "Search algorithms deliver results in milliseconds.", uz: "algoritm" },
      { word: "Data", meaning: "Information stored by a computer.", example: "Companies collect huge amounts of data.", uz: "maʼlumot" },
      { word: "Software", meaning: "Programs that run on a computer.", example: "This software is free to download.", uz: "dasturiy taʼminot" },
      { word: "Hardware", meaning: "The physical parts of a computer.", example: "The hardware includes the screen and keyboard.", uz: "apparat qismi" },
      { word: "Cloud", meaning: "Online storage over the internet.", example: "All my files are saved in the cloud.", uz: "bulut xotira" },
      { word: "Cybersecurity", meaning: "Protection of computer systems.", example: "Banks invest heavily in cybersecurity.", uz: "kiberxavfsizlik" },
      { word: "Encryption", meaning: "Turning data into a secret code.", example: "Encryption keeps messages private.", uz: "shifrlash" },
      { word: "Interface", meaning: "The way a user interacts with a program.", example: "The app has a simple interface.", uz: "interfeys" },
      { word: "User-friendly", meaning: "Easy to use.", example: "The website is very user-friendly.", uz: "foydalanuvchiga qulay" },
      { word: "Virtual", meaning: "Existing in the computer, not physically.", example: "We held a virtual meeting online.", uz: "virtual" },
      { word: "Wireless", meaning: "Without wires or cables.", example: "Most keyboards are now wireless.", uz: "simsiz" },
      { word: "Upgrade", meaning: "Improve to a newer version.", example: "You should upgrade your phone soon.", uz: "yangilash" },
      { word: "Bandwidth", meaning: "The amount of data a network can send.", example: "Video calls need high bandwidth.", uz: "kanal kengligi" },
      { word: "Bug", meaning: "A mistake in a computer program.", example: "The team fixed a serious security bug.", uz: "xato / dasturiy nuqson" },
      { word: "Prototype", meaning: "An early sample of a product.", example: "They built a prototype in a week.", uz: "prototip / dastlabki namuna" },
      { word: "Streaming", meaning: "Playing video/audio directly from the internet.", example: "Streaming services replaced TV for many.", uz: "onlayn eshittirish" },
      { word: "Social media", meaning: "Websites for sharing content and connecting.", example: "Social media shapes public opinion.", uz: "ijtimoiy tarmoqlar" },
      { word: "E-commerce", meaning: "Buying and selling online.", example: "E-commerce grew during the pandemic.", uz: "elektron tijorat" },
      { word: "Wearable", meaning: "Technology you wear on your body.", example: "Smartwatches are popular wearable devices.", uz: "kiyish mumkin (qurilma)" },
      { word: "Disruptive", meaning: "Changing an industry completely.", example: "Uber was a disruptive technology.", uz: "tubdan oʻzgartiruvchi" },
      { word: "Sensor", meaning: "A device that detects and measures.", example: "The car has parking sensors.", uz: "datchik / sezgich" },
    ],
  },
  {
    id: "health",
    name: "Health & Medicine",
    emoji: "🏥",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Diagnosis", meaning: "Identifying an illness.", example: "The doctor gave a clear diagnosis.", uz: "tashxis" },
      { word: "Symptom", meaning: "A sign of illness.", example: "Fever is a common symptom of flu.", uz: "kasallik belgisi" },
      { word: "Treatment", meaning: "Medical care given to a patient.", example: "Early treatment saves lives.", uz: "davolash" },
      { word: "Prescription", meaning: "A doctor's written order for medicine.", example: "You'll need a prescription for these tablets.", uz: "retsept" },
      { word: "Immune system", meaning: "The body's defence against disease.", example: "Sleep strengthens the immune system.", uz: "immunitet tizimi" },
      { word: "Vaccine", meaning: "A substance that protects against disease.", example: "The polio vaccine saved millions of lives.", uz: "emlash / vaksina" },
      { word: "Epidemic", meaning: "A widespread outbreak of disease.", example: "Officials worked to stop the epidemic.", uz: "epidemiya" },
      { word: "Pandemic", meaning: "A disease outbreak across many countries.", example: "The pandemic changed how we work.", uz: "pandemiya" },
      { word: "Chronic", meaning: "Long-lasting or recurring.", example: "Diabetes is a chronic condition.", uz: "surunkali" },
      { word: "Acute", meaning: "Severe and sudden.", example: "He was taken to hospital with acute pain.", uz: "oʻtkir / keskin" },
      { word: "Nutrition", meaning: "Food needed for health.", example: "Good nutrition supports growth.", uz: "ovqatlanish / oziqlanish" },
      { word: "Obesity", meaning: "Being seriously overweight.", example: "Obesity is a growing global problem.", uz: "semizlik" },
      { word: "Sedentary", meaning: "Involving little exercise.", example: "A sedentary lifestyle harms your heart.", uz: "harakatsiz turmush tarzi" },
      { word: "Cardiovascular", meaning: "Relating to the heart and blood vessels.", example: "Running improves cardiovascular health.", uz: "yurak-qon tomirlariga oid" },
      { word: "Longevity", meaning: "Long life.", example: "Diet plays a role in longevity.", uz: "uzoq umr koʻrish" },
      { word: "Well-being", meaning: "General state of health and happiness.", example: "Mental well-being matters as much as physical.", uz: "farovonlik / salomatlik" },
      { word: "Mental health", meaning: "Emotional and psychological well-being.", example: "Universities offer mental health support.", uz: "ruhiy salomatlik" },
      { word: "Therapy", meaning: "Treatment for a condition, often mental.", example: "She started therapy to manage anxiety.", uz: "davolash / psixoterapiya" },
      { word: "Antibiotic", meaning: "Medicine that fights bacteria.", example: "Overuse of antibiotics leads to resistance.", uz: "antibiotik" },
      { word: "Contagious", meaning: "Spreads easily from person to person.", example: "Chickenpox is highly contagious.", uz: "yuqumli" },
      { word: "Sanitation", meaning: "Systems for keeping places clean.", example: "Poor sanitation spreads disease.", uz: "sanitariya" },
      { word: "Hygiene", meaning: "Practices for staying clean and healthy.", example: "Hand hygiene reduces infection.", uz: "gigiena" },
      { word: "Nutrient", meaning: "A substance that helps the body grow.", example: "Vegetables are full of nutrients.", uz: "oziq modda" },
      { word: "Deficiency", meaning: "A lack of something needed.", example: "Vitamin D deficiency is common in winter.", uz: "yetishmovchilik" },
      { word: "Prevention", meaning: "Stopping something before it happens.", example: "Prevention is better than cure.", uz: "oldini olish" },
      { word: "Life expectancy", meaning: "How long a person is expected to live.", example: "Life expectancy has risen worldwide.", uz: "oʻrtacha umr koʻrish" },
      { word: "Rehabilitation", meaning: "Helping recover after illness or injury.", example: "The clinic offers physical rehabilitation.", uz: "reabilitatsiya" },
      { word: "Insomnia", meaning: "Difficulty in sleeping.", example: "Stress often causes insomnia.", uz: "uyqusizlik" },
      { word: "Anxiety", meaning: "A feeling of worry or fear.", example: "Exam anxiety affects many students.", uz: "xavotir / bezovtalik" },
      { word: "Immunity", meaning: "The body's ability to resist disease.", example: "The vaccine builds immunity in two weeks.", uz: "immunitet" },
    ],
  },
  {
    id: "society",
    name: "Society & Culture",
    emoji: "👥",
    band: "Band 7.0–8.5",
    cards: [
      { word: "Diverse", meaning: "Including many different types.", example: "London has a diverse population.", uz: "xilma-xil" },
      { word: "Cultural heritage", meaning: "Traditions passed down over generations.", example: "The museum preserves our cultural heritage.", uz: "madaniy meros" },
      { word: "Custom", meaning: "A traditional practice in a group.", example: "Removing shoes is a local custom.", uz: "urf-odat" },
      { word: "Norm", meaning: "A standard or expected behaviour.", example: "Politeness is a social norm.", uz: "meʼyor" },
      { word: "Values", meaning: "Beliefs about what is important.", example: "Honesty is one of my family's values.", uz: "qadriyatlar" },
      { word: "Discrimination", meaning: "Treating some people unfairly.", example: "The law bans discrimination at work.", uz: "kamsitish" },
      { word: "Equality", meaning: "Being equal in status and rights.", example: "The movement fights for gender equality.", uz: "tenglik" },
      { word: "Prejudice", meaning: "Unfair opinion without reason.", example: "Education helps reduce prejudice.", uz: "xurofot / adolatsiz fikr" },
      { word: "Stereotype", meaning: "A fixed idea about a group of people.", example: "The film challenges old stereotypes.", uz: "qolip fikr / stereotip" },
      { word: "Integrate", meaning: "To join and become part of a group.", example: "Migrants integrate faster when they learn the language.", uz: "moslashmoq" },
      { word: "Assimilate", meaning: "To adopt the ways of another culture.", example: "It can take years to fully assimilate.", uz: "singib ketmoq" },
      { word: "Community", meaning: "A group of people living together.", example: "Our community organises many events.", uz: "jamoa" },
      { word: "Generation", meaning: "People born at about the same time.", example: "Each generation faces new challenges.", uz: "avlod" },
      { word: "Tradition", meaning: "A custom passed down for years.", example: "Sharing food is an old tradition.", uz: "anʼana" },
      { word: "Multicultural", meaning: "Including several cultures.", example: "Toronto is a multicultural city.", uz: "koʻp madaniyatli" },
      { word: "Identity", meaning: "Who someone is; their sense of self.", example: "Language is part of national identity.", uz: "oʻzlik / shaxsiy tanish" },
      { word: "Urbanisation", meaning: "The growth of cities.", example: "Rapid urbanisation strains services.", uz: "shaharlashish" },
      { word: "Migration", meaning: "Moving from one place to another.", example: "Economic migration has shaped many countries.", uz: "koʻchish / migratsiya" },
      { word: "Gender", meaning: "The state of being male or female.", example: "Gender roles are changing.", uz: "jins / gender" },
      { word: "Poverty", meaning: "The state of being very poor.", example: "The charity fights poverty in rural areas.", uz: "qashshoqlik" },
      { word: "Wealth", meaning: "A large amount of money or property.", example: "Wealth is unevenly distributed.", uz: "boylik" },
      { word: "Social class", meaning: "A group with a similar economic position.", example: "The gap between social classes has widened.", uz: "ijtimoiy tabaqa" },
      { word: "Welfare", meaning: "Government help for those in need.", example: "The welfare system supports the unemployed.", uz: "ijtimoiy taʼminot" },
      { word: "Volunteer", meaning: "Someone who works without pay.", example: "Volunteers helped after the flood.", uz: "koʻngilli" },
      { word: "Charity", meaning: "An organisation that helps others.", example: "The charity provides free meals.", uz: "xayriya" },
      { word: "Civic", meaning: "Relating to a town or its citizens.", example: "Voting is a basic civic duty.", uz: "fuqaroga oid" },
      { word: "Democracy", meaning: "Government chosen by the people.", example: "Elections are the heart of democracy.", uz: "demokratiya" },
      { word: "Ethical", meaning: "Morally right or acceptable.", example: "Buying local coffee is an ethical choice.", uz: "axloqiy" },
      { word: "Controversy", meaning: "Public disagreement about something.", example: "The new law caused public controversy.", uz: "bahs-munozara" },
      { word: "Solidarity", meaning: "Support and unity within a group.", example: "The community showed solidarity with the victims.", uz: "birdamlik" },
    ],
  },
  {
    id: "business",
    name: "Business & Work",
    emoji: "💼",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Entrepreneur", meaning: "A person who starts a business.", example: "The entrepreneur launched three startups.", uz: "tadbirkor" },
      { word: "Corporate", meaning: "Relating to large companies.", example: "Corporate culture varies from firm to firm.", uz: "korporativ" },
      { word: "Revenue", meaning: "Money a business earns.", example: "Revenue rose 12% last quarter.", uz: "daromad" },
      { word: "Profit", meaning: "Money made after costs.", example: "The shop finally made a profit.", uz: "foyda" },
      { word: "Loss", meaning: "Money lost by a business.", example: "The airline reported heavy losses.", uz: "zarar" },
      { word: "Investment", meaning: "Money put in hoping for return.", example: "Foreign investment boosts the economy.", uz: "sarmoya" },
      { word: "Stakeholder", meaning: "Anyone affected by a business decision.", example: "Employees are important stakeholders.", uz: "manfaatdor tomon" },
      { word: "Shareholder", meaning: "Owner of part of a company.", example: "Shareholders voted for the merger.", uz: "aksiyador" },
      { word: "Startup", meaning: "A young, growing company.", example: "Silicon Valley is full of tech startups.", uz: "startap" },
      { word: "Merger", meaning: "When two companies combine.", example: "The bank merger created a giant.", uz: "birlashish" },
      { word: "Acquisition", meaning: "Buying another company.", example: "The acquisition cost $2 billion.", uz: "sotib olish" },
      { word: "Workforce", meaning: "All the workers in a company or country.", example: "The workforce is highly skilled.", uz: "ishchi kuchi" },
      { word: "Productivity", meaning: "How much is produced per hour.", example: "New software boosted productivity.", uz: "unumdorlik" },
      { word: "Deadline", meaning: "The final time to finish something.", example: "We must meet the Friday deadline.", uz: "muddat" },
      { word: "Client", meaning: "A person who buys services.", example: "The lawyer met his new client.", uz: "mijoz" },
      { word: "Supplier", meaning: "A company that provides goods.", example: "We changed our main supplier last year.", uz: "yetkazib beruvchi" },
      { word: "Marketing", meaning: "Promoting and selling products.", example: "Marketing shapes what we buy.", uz: "marketing" },
      { word: "Brand", meaning: "A company's name and image.", example: "Apple is one of the world's top brands.", uz: "brend" },
      { word: "Consumer", meaning: "A person who buys goods.", example: "Consumers demand better quality.", uz: "isteʼmolchi" },
      { word: "Recession", meaning: "A period of economic decline.", example: "Many people lost jobs in the recession.", uz: "iqtisodiy tanazzul" },
      { word: "Boom", meaning: "A period of rapid growth.", example: "The tech boom created many jobs.", uz: "keskin oʻsish" },
      { word: "Freelance", meaning: "Working for yourself, not one employer.", example: "She works freelance as a designer.", uz: "erkin ishlovchi" },
      { word: "Remote work", meaning: "Working from outside the office.", example: "Remote work saves commuting time.", uz: "masofadan ishlash" },
      { word: "Promotion", meaning: "A move to a higher job.", example: "He got a promotion after two years.", uz: "lavozimda koʻtarilish" },
      { word: "Salary", meaning: "Regular payment for work.", example: "The salary includes health insurance.", uz: "maosh" },
      { word: "Redundant", meaning: "No longer needed at work.", example: "Fifty workers were made redundant.", uz: "ishdan boʻshatilgan" },
      { word: "Recruit", meaning: "To hire new workers.", example: "The firm recruits engineers every summer.", uz: "ishga olmoq" },
      { word: "CV / résumé", meaning: "A summary of your work history.", example: "Send your CV by Friday.", uz: "rezyume" },
      { word: "Networking", meaning: "Building work-related contacts.", example: "Networking helped her find a job.", uz: "aloqalar tarmogʻini qurish" },
      { word: "Outsource", meaning: "To pay another firm to do work.", example: "They outsource customer support to India.", uz: "tashqi tashkilotga topshirmoq" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Tourism",
    emoji: "✈️",
    band: "Band 6.0–7.5",
    cards: [
      { word: "Itinerary", meaning: "A planned route or journey.", example: "Our itinerary included three cities.", uz: "sayohat rejasi" },
      { word: "Destination", meaning: "The place you are going to.", example: "Bali is a popular destination.", uz: "manzil" },
      { word: "Excursion", meaning: "A short trip for pleasure.", example: "We booked a day excursion to the mountains.", uz: "sayohat / ekskursiya" },
      { word: "Accommodation", meaning: "A place to stay.", example: "The hotel offers comfortable accommodation.", uz: "yashash joyi" },
      { word: "Souvenir", meaning: "An object to remember a place.", example: "She bought a souvenir from every country.", uz: "esdalik sovgʻa" },
      { word: "Voyage", meaning: "A long journey by sea.", example: "The voyage took six days.", uz: "dengiz sayohati" },
      { word: "Picturesque", meaning: "Visually attractive.", example: "The village was small and picturesque.", uz: "koʻrkam" },
      { word: "Remote", meaning: "Far from other places.", example: "They travelled to a remote island.", uz: "olis / uzoq" },
      { word: "Backpacker", meaning: "A budget traveller with a rucksack.", example: "Backpackers filled the youth hostel.", uz: "sayyoh (arzon sayohat qiluvchi)" },
      { word: "Cuisine", meaning: "A style of cooking.", example: "Thai cuisine is famous for its spices.", uz: "milliy taomlar" },
      { word: "Landmark", meaning: "A famous building or object.", example: "The Eiffel Tower is a Paris landmark.", uz: "diqqatga sazovor joy" },
      { word: "Sightseeing", meaning: "Visiting famous places as a tourist.", example: "We spent Saturday sightseeing.", uz: "sayohat qilib tomosha qilish" },
      { word: "Visa", meaning: "Official permission to enter a country.", example: "You need a visa to visit China.", uz: "viza" },
      { word: "Customs", meaning: "The place where luggage is checked.", example: "Customs officers checked our bags.", uz: "bojxona" },
      { word: "Currency", meaning: "The money used in a country.", example: "The euro is the currency of Germany.", uz: "valyuta" },
      { word: "Exchange rate", meaning: "The value of one currency vs another.", example: "The exchange rate changes daily.", uz: "valyuta kursi" },
      { word: "Departure", meaning: "The act of leaving.", example: "Our departure was delayed by fog.", uz: "jo'nab ketish" },
      { word: "Arrival", meaning: "The act of arriving.", example: "The arrival time was 10 pm.", uz: "kelish" },
      { word: "Delay", meaning: "A period of waiting.", example: "A short delay before boarding.", uz: "kechikish" },
      { word: "Cancellation", meaning: "Stopping something planned.", example: "The airline announced flight cancellations.", uz: "bekor qilish" },
      { word: "Ecotourism", meaning: "Tourism that helps the environment.", example: "Costa Rica is famous for ecotourism.", uz: "ekoturizm" },
      { word: "Peak season", meaning: "The busiest time for tourism.", example: "Hotel prices double in peak season.", uz: "mavsumning eng qizgʻin davri" },
      { word: "Off-peak", meaning: "Quieter time; cheaper prices.", example: "Off-peak flights are much cheaper.", uz: "mavsumdan tashqari" },
      { word: "Booking", meaning: "A reservation.", example: "I made a booking online.", uz: "buyurtma" },
      { word: "Passport", meaning: "Official travel document.", example: "Renew your passport before travelling.", uz: "pasport" },
      { word: "Boarding pass", meaning: "Ticket for boarding a plane.", example: "Show your boarding pass at the gate.", uz: "chipta / boarding-kartochka" },
      { word: "Layover", meaning: "A short stop between flights.", example: "We had a 2-hour layover in Dubai.", uz: "reyslar orasidagi to'xtash" },
      { word: "Jet lag", meaning: "Tiredness from crossing time zones.", example: "Jet lag lasted for three days.", uz: "vaqt farqidan charchash" },
      { word: "All-inclusive", meaning: "A holiday with food and drinks included.", example: "We chose an all-inclusive resort.", uz: "hammasi kiritilgan" },
      { word: "Overrated", meaning: "Praised more than it deserves.", example: "Some famous restaurants are overrated.", uz: "haddan tashqari maqtalgan" },
    ],
  },
  {
    id: "media",
    name: "Media & Communication",
    emoji: "📱",
    band: "Band 7.0–8.5",
    cards: [
      { word: "Broadcast", meaning: "To send out on TV or radio.", example: "The concert was broadcast live.", uz: "efirga uzatmoq" },
      { word: "Coverage", meaning: "Reporting of news.", example: "The event received wide media coverage.", uz: "yoritilishi" },
      { word: "Headline", meaning: "The title of a news article.", example: "The headline caught my attention.", uz: "sarlavha" },
      { word: "Journalist", meaning: "A person who reports news.", example: "The journalist won a prize for her article.", uz: "jurnalist" },
      { word: "Editorial", meaning: "An article giving an opinion.", example: "The editorial criticised the new law.", uz: "bosh maqola / muharrir fikri" },
      { word: "Censorship", meaning: "Removing offensive or dangerous content.", example: "Some governments impose strict censorship.", uz: "senzura / taqiq" },
      { word: "Bias", meaning: "Unfair support for one side.", example: "The report showed clear political bias.", uz: "yon bosish / xolisonalik yoʻqligi" },
      { word: "Objective", meaning: "Not influenced by personal feelings.", example: "News should be objective and factual.", uz: "xolis" },
      { word: "Sensational", meaning: "Exaggerated to shock.", example: "Tabloids often print sensational stories.", uz: "shov-shuvli" },
      { word: "Tabloid", meaning: "A small newspaper with short, dramatic stories.", example: "Tabloids focus on celebrity gossip.", uz: "sensatsion gazeta" },
      { word: "Broadsheet", meaning: "A serious, large-format newspaper.", example: "The broadsheet covered the election in depth.", uz: "jiddiy gazeta" },
      { word: "Anchor", meaning: "The main news presenter.", example: "The evening news has a new anchor.", uz: "yetakchi (yangiliklar)" },
      { word: "Correspondent", meaning: "A reporter in a specific place.", example: "Our Moscow correspondent filed the story.", uz: "muxbir" },
      { word: "Freedom of speech", meaning: "The right to express opinions.", example: "Freedom of speech is a basic right.", uz: "soʻz erkinligi" },
      { word: "Misinformation", meaning: "Wrong information, often spread by mistake.", example: "Social media spreads misinformation quickly.", uz: "notoʻgʻri maʼlumot" },
      { word: "Fake news", meaning: "Fabricated news made to look real.", example: "Fake news influenced the election.", uz: "yolgʻon xabar" },
      { word: "Propaganda", meaning: "Biased info used to promote a view.", example: "Wartime posters used propaganda.", uz: "targʻibot" },
      { word: "Influencer", meaning: "A person who shapes opinion online.", example: "Brands pay influencers to promote products.", uz: "influencer / taʼsirchan blogger" },
      { word: "Viral", meaning: "Spreading very quickly online.", example: "The video went viral overnight.", uz: "keskin ommalashgan" },
      { word: "Podcast", meaning: "An audio program on the internet.", example: "I listen to a science podcast every week.", uz: "podkast" },
      { word: "Subscriber", meaning: "A person who signs up for content.", example: "The channel has a million subscribers.", uz: "obunachi" },
      { word: "Interactive", meaning: "Allowing user input and response.", example: "The website has interactive maps.", uz: "interfaol" },
      { word: "Multimedia", meaning: "Combining text, sound, and video.", example: "The multimedia lesson was very engaging.", uz: "multimediya" },
      { word: "Advertisement", meaning: "A message promoting a product.", example: "The advertisement appeared before the video.", uz: "reklama" },
      { word: "Endorsement", meaning: "Public support for a product.", example: "The star's endorsement boosted sales.", uz: "qoʻllab-quvvatlash / reklama" },
      { word: "Column", meaning: "A regular article by the same writer.", example: "Her Sunday column is very popular.", uz: "rubrika" },
      { word: "Feature", meaning: "A special longer article.", example: "The magazine ran a feature on climate change.", uz: "maxsus maqola" },
      { word: "Trending", meaning: "Currently very popular.", example: "The song is trending on TikTok.", uz: "trendda" },
      { word: "Digital divide", meaning: "Gap between those with/without internet access.", example: "The digital divide hurts rural students.", uz: "raqamli tafovut" },
      { word: "Screen time", meaning: "Time spent looking at screens.", example: "Doctors warn against excessive screen time.", uz: "ekran vaqti" },
    ],
  },
  {
    id: "science",
    name: "Science & Research",
    emoji: "🔬",
    band: "Band 7.0–8.5",
    cards: [
      { word: "Hypothesis", meaning: "A proposed explanation to test.", example: "The scientist tested her hypothesis.", uz: "farazi / gipoteza" },
      { word: "Experiment", meaning: "A scientific test.", example: "The experiment produced surprising results.", uz: "tajriba" },
      { word: "Data", meaning: "Facts collected for analysis.", example: "The data show a clear pattern.", uz: "maʼlumotlar" },
      { word: "Sample", meaning: "A small group used in research.", example: "The sample size was too small.", uz: "namuna" },
      { word: "Variable", meaning: "A factor that can change.", example: "Temperature was the main variable.", uz: "oʻzgaruvchi" },
      { word: "Correlation", meaning: "A connection between two things.", example: "There is a correlation between diet and health.", uz: "bogʻliqlik" },
      { word: "Evidence", meaning: "Facts that support a claim.", example: "The evidence supports the theory.", uz: "dalil" },
      { word: "Theory", meaning: "A well-supported explanation.", example: "Einstein developed the theory of relativity.", uz: "nazariya" },
      { word: "Discovery", meaning: "Finding something new.", example: "The discovery changed medicine.", uz: "kashfiyot" },
      { word: "Breakthrough", meaning: "A major advance in knowledge.", example: "The team made a breakthrough in cancer research.", uz: "yirik yutuq" },
      { word: "Laboratory", meaning: "A place for scientific work.", example: "The lab has the latest equipment.", uz: "laboratoriya" },
      { word: "Analyse", meaning: "To examine carefully.", example: "The team will analyse the results next week.", uz: "tahlil qilmoq" },
      { word: "Conduct research", meaning: "To carry out a study.", example: "They conducted research over two years.", uz: "tadqiqot olib bormoq" },
      { word: "Peer-reviewed", meaning: "Checked by other scientists.", example: "The article is peer-reviewed and reliable.", uz: "mutaxassislar tomonidan koʻrib chiqilgan" },
      { word: "Publication", meaning: "A published book, article or paper.", example: "The publication received a lot of attention.", uz: "nashr" },
      { word: "Findings", meaning: "The results of research.", example: "The findings support earlier studies.", uz: "natijalar / xulosalar" },
      { word: "Conclusion", meaning: "A judgement based on evidence.", example: "The conclusion is that exercise helps.", uz: "xulosa" },
      { word: "Innovation", meaning: "A new idea or method.", example: "The innovation could save millions of lives.", uz: "yangilik" },
      { word: "Genetics", meaning: "The study of genes.", example: "Genetics explains many diseases.", uz: "genetika" },
      { word: "Genome", meaning: "All the genes of an organism.", example: "The human genome was mapped in 2003.", uz: "genom" },
      { word: "Molecule", meaning: "The smallest unit of a substance.", example: "Water molecules are made of two atoms of hydrogen.", uz: "molekula" },
      { word: "Particle", meaning: "A very small piece of matter.", example: "Physicists study subatomic particles.", uz: "zarra" },
      { word: "Gravity", meaning: "The force pulling objects together.", example: "Gravity keeps us on the ground.", uz: "tortishish kuchi" },
      { word: "Vaccine", meaning: "A treatment that prevents disease.", example: "The vaccine was developed in months.", uz: "vaksina" },
      { word: "Empirical", meaning: "Based on observation, not theory.", example: "Empirical data support the claim.", uz: "amaliy kuzatuvga asoslangan" },
      { word: "Quantitative", meaning: "Based on numbers.", example: "The study used quantitative methods.", uz: "raqamli / miqdoriy" },
      { word: "Qualitative", meaning: "Based on description, not numbers.", example: "Interviews are a qualitative method.", uz: "sifatli" },
      { word: "Replicate", meaning: "To repeat a study exactly.", example: "Other teams could not replicate the result.", uz: "takrorlab tekshirmoq" },
      { word: "Bias", meaning: "A systematic error in a study.", example: "Researchers try to reduce bias.", uz: "tarafkashlik" },
      { word: "Ethics", meaning: "Moral rules of research.", example: "All studies must follow ethics guidelines.", uz: "axloqiy qoidalar" },
    ],
  },
  {
    id: "arts",
    name: "Arts & Entertainment",
    emoji: "🎨",
    band: "Band 6.5–8.0",
    cards: [
      { word: "Masterpiece", meaning: "An outstanding work of art.", example: "The Mona Lisa is a masterpiece.", uz: "shohasar" },
      { word: "Genre", meaning: "A category of art or writing.", example: "Science fiction is a popular genre.", uz: "janr" },
      { word: "Composition", meaning: "A piece of music or artwork.", example: "The composition took two years to finish.", uz: "kompozitsiya / asar" },
      { word: "Exhibition", meaning: "A public display of art.", example: "The Picasso exhibition attracted thousands.", uz: "koʻrgazma" },
      { word: "Gallery", meaning: "A room or building for showing art.", example: "The gallery is free on Sundays.", uz: "galereya" },
      { word: "Sculpture", meaning: "Art made by shaping stone, metal, etc.", example: "Michelangelo's sculpture stands in Florence.", uz: "haykaltaroshlik / haykal" },
      { word: "Portrait", meaning: "A painting of a person.", example: "The portrait shows the queen at 40.", uz: "portret" },
      { word: "Landscape", meaning: "A painting of nature.", example: "The landscape shows a peaceful valley.", uz: "manzara" },
      { word: "Abstract", meaning: "Art that is not realistic.", example: "Abstract art can be hard to interpret.", uz: "mavhum" },
      { word: "Contemporary", meaning: "Belonging to the present time.", example: "The museum shows contemporary art.", uz: "zamonaviy" },
      { word: "Classical", meaning: "Traditional and long-established.", example: "She studied classical piano for ten years.", uz: "klassik" },
      { word: "Cinema", meaning: "The art of making films.", example: "Italian cinema is world-famous.", uz: "kinematografiya" },
      { word: "Director", meaning: "Person who leads a film.", example: "The director won an Oscar.", uz: "rejissyor" },
      { word: "Screenplay", meaning: "The written script for a film.", example: "The screenplay is based on a novel.", uz: "kinostsenariy" },
      { word: "Soundtrack", meaning: "The music of a film.", example: "The soundtrack made the film memorable.", uz: "musiqiy hamrohlik" },
      { word: "Plot", meaning: "The main events of a story.", example: "The plot was full of surprises.", uz: "syujet" },
      { word: "Character", meaning: "A person in a story.", example: "The main character is a young detective.", uz: "personaj / qahramon" },
      { word: "Novel", meaning: "A long book of fiction.", example: "Her novel became a bestseller.", uz: "roman" },
      { word: "Poetry", meaning: "Writing in verse.", example: "He reads poetry every morning.", uz: "sheʼriyat" },
      { word: "Drama", meaning: "A play for stage or TV.", example: "The drama explores family conflict.", uz: "drama" },
      { word: "Rehearsal", meaning: "A practice for a performance.", example: "The final rehearsal went smoothly.", uz: "repetitsiya" },
      { word: "Audience", meaning: "The people watching a show.", example: "The audience clapped for five minutes.", uz: "tomoshabinlar" },
      { word: "Applause", meaning: "Clapping to show approval.", example: "The band received loud applause.", uz: "qarsak" },
      { word: "Critic", meaning: "A person who reviews art.", example: "The critic praised the young singer.", uz: "tanqidchi" },
      { word: "Review", meaning: "A written opinion of a work.", example: "The film got a five-star review.", uz: "sharh / taqriz" },
      { word: "Talented", meaning: "Having natural skill.", example: "She is a talented pianist.", uz: "isteʼdodli" },
      { word: "Perform", meaning: "To act, sing, or play in public.", example: "The band will perform in Rome tonight.", uz: "sahnada chiqish qilmoq" },
      { word: "Artefact", meaning: "An old object of cultural interest.", example: "The museum houses ancient artefacts.", uz: "qadimiy topilma" },
      { word: "Heritage", meaning: "Traditions and objects passed down.", example: "The old town is a UNESCO heritage site.", uz: "meros" },
      { word: "Inspiration", meaning: "A source of creative ideas.", example: "Nature is her greatest inspiration.", uz: "ilhom manbayi" },
    ],
  },
];
