import "server-only";

/**
 * CDI practice materials (imported by scripts/cdi/import.mjs): 70 Academic
 * Reading papers, 54 Listening papers with real recordings, and Writing
 * Task 1 / Task 2 prompts. They replace the built-in Averna / legacy tests in
 * every student and teacher list (lib/ielts/catalog.ts).
 *
 * GENERATED by scripts/cdi/import.mjs from the files it wrote — don't edit by
 * hand; re-run the converter instead.
 *
 * SERVER ONLY: the JSON holds every answer key and Listening transcript, so the
 * "server-only" guard turns any client import into a build error. Students get
 * these tests through the sanitisers (lib/ielts/sanitize.ts) like any other.
 * Static imports (not fs) so the files are bundled with the server code.
 */

import type { ExamListeningTest, ExamReadingTest } from "../../types";
import type { WritingPrompt } from "@/lib/writing-data";
import { byCdiNumber } from "../../listing";
import writing from "./writing.json";
import r01 from "./reading/cdi-reading-01.json";
import r02 from "./reading/cdi-reading-02.json";
import r03 from "./reading/cdi-reading-03.json";
import r04 from "./reading/cdi-reading-04.json";
import r05 from "./reading/cdi-reading-05.json";
import r07 from "./reading/cdi-reading-07.json";
import r08 from "./reading/cdi-reading-08.json";
import r09 from "./reading/cdi-reading-09.json";
import r10 from "./reading/cdi-reading-10.json";
import r11 from "./reading/cdi-reading-11.json";
import r12 from "./reading/cdi-reading-12.json";
import r13 from "./reading/cdi-reading-13.json";
import r14 from "./reading/cdi-reading-14.json";
import r15 from "./reading/cdi-reading-15.json";
import r16 from "./reading/cdi-reading-16.json";
import r17 from "./reading/cdi-reading-17.json";
import r18 from "./reading/cdi-reading-18.json";
import r19 from "./reading/cdi-reading-19.json";
import r20 from "./reading/cdi-reading-20.json";
import r21 from "./reading/cdi-reading-21.json";
import r22 from "./reading/cdi-reading-22.json";
import r23 from "./reading/cdi-reading-23.json";
import r24 from "./reading/cdi-reading-24.json";
import r25 from "./reading/cdi-reading-25.json";
import r26 from "./reading/cdi-reading-26.json";
import r27 from "./reading/cdi-reading-27.json";
import r28 from "./reading/cdi-reading-28.json";
import r29 from "./reading/cdi-reading-29.json";
import r32 from "./reading/cdi-reading-32.json";
import r34 from "./reading/cdi-reading-34.json";
import r37 from "./reading/cdi-reading-37.json";
import r39 from "./reading/cdi-reading-39.json";
import r40 from "./reading/cdi-reading-40.json";
import r41 from "./reading/cdi-reading-41.json";
import r43 from "./reading/cdi-reading-43.json";
import r45 from "./reading/cdi-reading-45.json";
import r46 from "./reading/cdi-reading-46.json";
import r47 from "./reading/cdi-reading-47.json";
import r49 from "./reading/cdi-reading-49.json";
import r50 from "./reading/cdi-reading-50.json";
import r51 from "./reading/cdi-reading-51.json";
import r53 from "./reading/cdi-reading-53.json";
import r54 from "./reading/cdi-reading-54.json";
import r55 from "./reading/cdi-reading-55.json";
import r57 from "./reading/cdi-reading-57.json";
import r58 from "./reading/cdi-reading-58.json";
import r59 from "./reading/cdi-reading-59.json";
import r60 from "./reading/cdi-reading-60.json";
import r61 from "./reading/cdi-reading-61.json";
import r62 from "./reading/cdi-reading-62.json";
import r63 from "./reading/cdi-reading-63.json";
import r64 from "./reading/cdi-reading-64.json";
import r65 from "./reading/cdi-reading-65.json";
import r66 from "./reading/cdi-reading-66.json";
import r67 from "./reading/cdi-reading-67.json";
import r68 from "./reading/cdi-reading-68.json";
import r70 from "./reading/cdi-reading-70.json";
import r71 from "./reading/cdi-reading-71.json";
import r72 from "./reading/cdi-reading-72.json";
import r73 from "./reading/cdi-reading-73.json";
import r74 from "./reading/cdi-reading-74.json";
import r75 from "./reading/cdi-reading-75.json";
import r76 from "./reading/cdi-reading-76.json";
import r77 from "./reading/cdi-reading-77.json";
import r78 from "./reading/cdi-reading-78.json";
import r79 from "./reading/cdi-reading-79.json";
import r80 from "./reading/cdi-reading-80.json";
import r81 from "./reading/cdi-reading-81.json";
import r82 from "./reading/cdi-reading-82.json";
import r83 from "./reading/cdi-reading-83.json";
import l01 from "./listening/cdi-listening-01.json";
import l02 from "./listening/cdi-listening-02.json";
import l03 from "./listening/cdi-listening-03.json";
import l04 from "./listening/cdi-listening-04.json";
import l05 from "./listening/cdi-listening-05.json";
import l06 from "./listening/cdi-listening-06.json";
import l07 from "./listening/cdi-listening-07.json";
import l08 from "./listening/cdi-listening-08.json";
import l09 from "./listening/cdi-listening-09.json";
import l10 from "./listening/cdi-listening-10.json";
import l12 from "./listening/cdi-listening-12.json";
import l13 from "./listening/cdi-listening-13.json";
import l14 from "./listening/cdi-listening-14.json";
import l17 from "./listening/cdi-listening-17.json";
import l19 from "./listening/cdi-listening-19.json";
import l22 from "./listening/cdi-listening-22.json";
import l23 from "./listening/cdi-listening-23.json";
import l24 from "./listening/cdi-listening-24.json";
import l25 from "./listening/cdi-listening-25.json";
import l27 from "./listening/cdi-listening-27.json";
import l28 from "./listening/cdi-listening-28.json";
import l29 from "./listening/cdi-listening-29.json";
import l30 from "./listening/cdi-listening-30.json";
import l31 from "./listening/cdi-listening-31.json";
import l32 from "./listening/cdi-listening-32.json";
import l33 from "./listening/cdi-listening-33.json";
import l35 from "./listening/cdi-listening-35.json";
import l36 from "./listening/cdi-listening-36.json";
import l38 from "./listening/cdi-listening-38.json";
import l40 from "./listening/cdi-listening-40.json";
import l41 from "./listening/cdi-listening-41.json";
import l42 from "./listening/cdi-listening-42.json";
import l43 from "./listening/cdi-listening-43.json";
import l44 from "./listening/cdi-listening-44.json";
import l45 from "./listening/cdi-listening-45.json";
import l46 from "./listening/cdi-listening-46.json";
import l47 from "./listening/cdi-listening-47.json";
import l48 from "./listening/cdi-listening-48.json";
import l49 from "./listening/cdi-listening-49.json";
import l50 from "./listening/cdi-listening-50.json";
import l51 from "./listening/cdi-listening-51.json";
import l56 from "./listening/cdi-listening-56.json";
import l58 from "./listening/cdi-listening-58.json";
import l59 from "./listening/cdi-listening-59.json";
import l61 from "./listening/cdi-listening-61.json";
import l62 from "./listening/cdi-listening-62.json";
import l63 from "./listening/cdi-listening-63.json";
import l65 from "./listening/cdi-listening-65.json";
import l66 from "./listening/cdi-listening-66.json";
import l67 from "./listening/cdi-listening-67.json";
import l68 from "./listening/cdi-listening-68.json";
import l69 from "./listening/cdi-listening-69.json";
import l70 from "./listening/cdi-listening-70.json";
import l71 from "./listening/cdi-listening-71.json";

const byNumber = byCdiNumber;

export const CDI_READING: ExamReadingTest[] = byNumber([
  r01, r02, r03, r04, r05, r07, r08, r09, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19, r20, r21,
  r22, r23, r24, r25, r26, r27, r28, r29, r32, r34, r37, r39, r40, r41, r43, r45, r46, r47, r49, r50,
  r51, r53, r54, r55, r57, r58, r59, r60, r61, r62, r63, r64, r65, r66, r67, r68, r70, r71, r72, r73,
  r74, r75, r76, r77, r78, r79, r80, r81, r82, r83,
] as unknown as ExamReadingTest[]);

export const CDI_LISTENING: ExamListeningTest[] = byNumber([
  l01, l02, l03, l04, l05, l06, l07, l08, l09, l10, l12, l13, l14, l17, l19, l22, l23, l24, l25, l27,
  l28, l29, l30, l31, l32, l33, l35, l36, l38, l40, l41, l42, l43, l44, l45, l46, l47, l48, l49, l50,
  l51, l56, l58, l59, l61, l62, l63, l65, l66, l67, l68, l69, l70, l71,
] as unknown as ExamListeningTest[]);

const w = writing as unknown as { task1: WritingPrompt[]; task2: WritingPrompt[] };
export const CDI_WRITING: Record<"task1" | "task2", WritingPrompt[]> = { task1: byNumber(w.task1), task2: byNumber(w.task2) };
