"use client";
import { useRef, useState, type ReactNode } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight, Wallet, Users, ShieldCheck, Banknote, Receipt, LockKeyhole, RefreshCw, Download, Plus, Search, FileCheck2, AlertTriangle } from "lucide-react";
import type { FinanceSnapshot } from "@/lib/finance/service";
import { formatUzs, todayTashkent } from "@/lib/finance/rules";
import "./finance.css";
const channelNames:Record<string,string>={CASH:"Naqd",CARD:"Plastik",TERMINAL:"Terminal",TRANSFER:"Bank oʻtkazmasi"};
const kindNames:Record<string,string>={TUITION:"Kurs toʻlovi",OTHER_INCOME:"Boshqa tushum",EXPENSE:"Xarajat",ADVANCE:"Avans",SALARY:"Ish haqi",REFUND:"Qaytarish",REVERSAL:"Bekor qilish"};
const statusNames:Record<string,string>={ACTIVE:"Faol",PAUSED:"Toʻxtatilgan",LEFT:"Ketgan",NEW:"Yangi",SCHEDULED:"Kelishi belgilangan",TRIAL:"Sinov darsi",ENROLLED:"Qabul qilingan",LOST:"Rad etilgan"};
const tabs=[{id:"overview",label:"Umumiy",icon:Wallet},{id:"learners",label:"Oʻquvchilar",icon:Users},{id:"payroll",label:"Ish haqi",icon:Banknote},{id:"expenses",label:"Xarajatlar",icon:Receipt},{id:"leads",label:"Lidlar",icon:Plus},{id:"journal",label:"Jurnal",icon:FileCheck2},{id:"setup",label:"Sozlamalar",icon:ShieldCheck}];
function Field({label,name,type="text",required=true,children,defaultValue,...extra}:{label:string;name:string;type?:string;required?:boolean;children?:ReactNode;defaultValue?:string|number}&React.InputHTMLAttributes<HTMLInputElement>) {
 return <label className="finance-field"><span>{label}</span>{children??<input name={name} type={type} required={required} defaultValue={defaultValue} {...extra}/>}</label>;
}
function Box({title,sub,children}:{title:string;sub?:string;children:ReactNode}){return <section className="finance-box"><div className="finance-box-heading"><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{children}</section>}
function Empty({children}:{children:ReactNode}){return <p className="finance-empty">{children}</p>}
function Metric({label,value,hint,known=true}:{label:string;value:string;hint:string;known?:boolean}){return <div className="finance-metric"><p>{label}</p><strong>{known?formatUzs(value):"—"}</strong><span>UZS · {hint}</span></div>}
function get(form:HTMLFormElement,name:string){return String(new FormData(form).get(name)??"")}
 function entry(form:HTMLFormElement,kind:string,month:string){return {action:"POST_ENTRY",month,kind,amount:get(form,"amount"),channel:get(form,"channel"),date:get(form,"date"),description:get(form,"description"),...(get(form,"invoiceId")?{invoiceId:get(form,"invoiceId")}:{}) ,...(get(form,"staffId")?{staffId:get(form,"staffId")}:{}) ,...(get(form,"refundOfId")?{refundOfId:get(form,"refundOfId")}:{}) ,...(kind==="EXPENSE"?{category:get(form,"category")}:{})}}
 function EntryForm({kind,data,open,busy,mutate}:{kind:string;data:FinanceSnapshot;open:boolean;busy:boolean;mutate:(command:Record<string,unknown>)=>Promise<void>}) {
  return <form className="finance-form" onSubmit={e=>{e.preventDefault();void mutate(entry(e.currentTarget,kind,data.month))}}>
   {kind==="TUITION"&&<Field label="Oʻquvchi / oylik hisob" name="invoiceId"><select name="invoiceId" required defaultValue=""><option value="" disabled>Hisobni tanlang</option>{data.invoices.filter(i=>BigInt(i.remaining)>0n).map(i=><option key={i.id} value={i.id}>{i.name} · {i.month} · {formatUzs(i.remaining)} UZS</option>)}</select></Field>}
   {(kind==="ADVANCE"||kind==="SALARY")&&<Field label="Xodim" name="staffId"><select name="staffId" required defaultValue=""><option value="" disabled>Xodimni tanlang</option>{data.staff.map(s=><option key={s.id} value={s.id}>{s.name} · qoldiq {formatUzs(s.due)} UZS</option>)}</select></Field>}
   {kind==="REFUND"&&<Field label="Asl kurs tushumi" name="refundOfId"><select name="refundOfId" required defaultValue=""><option value="" disabled>Toʻlovni tanlang</option>{data.refundSources.map(e=><option key={e.id} value={e.id}>{e.date} · {e.learner} · {formatUzs(e.remaining)} UZS</option>)}</select></Field>}
   {kind==="EXPENSE"&&<Field label="Xarajat turi" name="category"><select name="category"><option value="RENT">Arenda</option><option value="UTILITIES">Kommunal / svet</option><option value="BOOKS">Kitob</option><option value="SUPPLIES">Qogʻoz va jihoz</option><option value="OTHER">Boshqa</option></select></Field>}
   <div className="finance-form-row"><Field label="Summa · UZS" name="amount" inputMode="numeric" pattern="[0-9]+" placeholder="500000" maxLength={13}/><Field label="Toʻlov usuli" name="channel"><select name="channel">{Object.entries(channelNames).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></Field></div>
   <Field label="Haqiqiy sana" name="date" type="date" defaultValue={data.month===todayTashkent().slice(0,7)?todayTashkent():`${data.month}-01`} min={`${data.month}-01`} max={todayTashkent()}/><Field label="Izoh / hujjat raqami" name="description" maxLength={250} placeholder="Nima uchun va qaysi hujjat asosida?"/>
   <button className="finance-button finance-button-primary" disabled={!open||busy} type="submit"><Plus size={17}/>{kindNames[kind]}ni yozish</button>
  </form>;
 }

export function FinanceCenter({initial}:{initial:FinanceSnapshot}) {
 const [data,setData]=useState(initial);const [tab,setTab]=useState("overview");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<{error:boolean;text:string}|null>(null);const [query,setQuery]=useState("");const [onlyDebt,setOnlyDebt]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [journalPage,setJournalPage]=useState(0);const [editingId,setEditingId]=useState<string|null>(null);const [importPreview,setImportPreview]=useState<{items:Record<string,unknown>[];issues:string[];count:number}|null>(null);
 const keys=useRef(new Map<string,string>());const open=data.period?.status==="OPEN";
 async function refresh(month=data.month){const response=await fetch(`/api/admin/finance?month=${encodeURIComponent(month)}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Maʼlumotni yuklab boʻlmadi.");setData(payload);setSelected([]);setJournalPage(0)}
 async function mutate(command:Record<string,unknown>){
  if(busy)return;setBusy(true);setNotice(null);
  const fingerprint=JSON.stringify(command);let storageKey="";let key=keys.current.get(fingerprint);
  try{
   const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(fingerprint));storageKey=`averna:finance:${data.actorId}:`+Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,"0")).join("");
   try{key??=sessionStorage.getItem(storageKey)??undefined}catch{}
   key??=crypto.randomUUID();keys.current.set(fingerprint,key);try{sessionStorage.setItem(storageKey,key)}catch{}
   const response=await fetch("/api/admin/finance",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":key},body:JSON.stringify(command)});
   const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Saqlanmadi.");
   await refresh(command.action==="OPEN_PERIOD"?String(command.month):data.month);
   keys.current.delete(fingerprint);try{sessionStorage.removeItem(storageKey)}catch{}
setNotice({error:false,text:"Saqlandi. Hisobot va jurnal yangilandi."});
  }catch(e){setNotice({error:true,text:e instanceof Error?e.message:"Soʻrov holati nomaʼlum. Jurnalni tekshiring."})}finally{setBusy(false)}
 }
 const invoices=data.invoices.filter(i=>i.name.toLowerCase().includes(query.toLowerCase())||i.group.toLowerCase().includes(query.toLowerCase()));
 const learners=data.learners.filter(l=>(l.fullName+" "+l.groupName+" "+(l.phone??"")).toLowerCase().includes(query.toLowerCase())&&(!onlyDebt||data.invoices.some(i=>i.learnerId===l.id&&BigInt(i.remaining)>0n)));
 const editing=data.learners.find(l=>l.id===editingId);
 const learnerCommand=(l:FinanceSnapshot["learners"][number],status:string)=>({action:"UPDATE_LEARNER",id:l.id,fullName:l.fullName,phone:l.phone??"",groupName:l.groupName,staffId:l.staffId,monthlyFee:l.monthlyFee,dueDay:l.dueDay,status,note:l.note??"",platformStudentId:l.platformStudentId??"",rosterStudentId:l.rosterStudentId??"",sourceKey:l.sourceKey??""});
 return <main className="finance-shell">
  <div className="finance-container">
   <div className="finance-topline"><Link href="/admin/dashboard" className="finance-back"><ArrowLeft size={17}/> Admin Dashboard</Link><span className="finance-badge"><ShieldCheck size={14}/> Faqat administrator</span></div>
   <header className="finance-header"><div><p className="finance-eyebrow">AVERNA · BUSINESS CONTROL</p><h1>Moliya va nazorat</h1><p>Oʻquvchilar, tushumlar, ish haqi va xarajatlar — bitta ishonchli registr.</p></div><div className="finance-toolbar"><label className="finance-field"><span>Hisobot oyi</span><input aria-label="Hisobot oyi" type="month" value={data.month} onChange={e=>{setBusy(true);refresh(e.target.value).catch(e=>setNotice({error:true,text:e.message})).finally(()=>setBusy(false))}} disabled={busy}/></label><button className="finance-icon-button" aria-label="Hisobotni yangilash" disabled={busy} onClick={()=>{setBusy(true);refresh().catch(e=>setNotice({error:true,text:e.message})).finally(()=>setBusy(false))}}><RefreshCw size={18}/></button></div></header>
   {notice&&<p role="status" className={`finance-notice ${notice.error?"finance-notice-error":""}`}>{notice.text}</p>}
   {!data.period&&<div className="finance-notice"><AlertTriangle size={18}/><span>Bu oy hali ochilmagan. Boshlangʻich qoldiqni “Sozlamalar”da tasdiqlang. Tasdiqlanmagan oy summalari “—” bilan koʻrsatiladi.</span><button className="finance-text-button" onClick={()=>setTab("setup")}>Oy ochish →</button></div>}
   {data.period?.status==="CLOSED"&&<div className="finance-notice"><LockKeyhole size={18}/><span>Oy yopilgan: pul jurnali oʻzgarmaydi. Keyingi davrda qaytarilgan pul alohida yoziladi. Eski hisob qarzi esa joriy holatda koʻrsatiladi.</span></div>}
   <nav aria-label="Moliyaviy boʻlimlar" className="finance-tabs">{tabs.map(t=><button key={t.id} aria-pressed={tab===t.id} onClick={()=>setTab(t.id)}><t.icon size={17}/>{t.label}</button>)}</nav>
   {tab==="overview"&&<div className="finance-stack">
    <div className="finance-metrics"><Metric known={!!data.period} label="Sof tushum" value={data.summary.income} hint="qaytarishlar ayirilgan"/><Metric known={!!data.period} label="Operatsion xarajat" value={data.summary.expenses} hint="ish haqidan alohida"/><Metric known={!!data.period} label="Toʻlangan ish haqi" value={data.summary.payrollPaid} hint="avans bilan birga"/><Metric known={!!data.period} label="Hisob qarzi" value={data.summary.receivables} hint="oldingi oylar ham kiradi"/></div>
    <div className="finance-grid"><Box title="Pul oqimi va natija" sub="Pul qoldigʻi foyda emas. Hisoblangan natijada haqiqiy tushumdan xarajatlar va hisoblangan ish haqi ayiriladi."><dl className="finance-ledger-lines"><div><dt>Oy oxirgi registr qoldigʻi</dt><dd>{data.period?formatUzs(data.summary.balance):"—"} UZS</dd></div><div><dt>Oy davomida sof pul oqimi</dt><dd>{data.period?formatUzs(data.summary.net):"—"} UZS</dd></div><div><dt>Hisoblangan ish haqi</dt><dd>{data.period?formatUzs(data.summary.payrollEarned):"—"} UZS</dd></div><div><dt>Hisoblangan natija · soliqdan oldin</dt><dd>{data.period?formatUzs(data.summary.result):"—"} UZS</dd></div></dl><p className="finance-help">Bu bank bilan avtomatik solishtirilgan qoldiq emas. Faqat registrga yozilgan operatsiyalar hisoblanadi.</p></Box>
    <Box title="Toʻlov kanallari" sub="Har bir kanal uchun boshlangʻich qoldiq + sof harakat."><dl className="finance-ledger-lines">{Object.entries(data.summary.channels).map(([c,v])=><div key={c}><dt>{channelNames[c]}</dt><dd>{data.period?formatUzs(v.balance):"—"} UZS <small>Harakat {data.period?formatUzs(v.flow):"—"}</small></dd></div>)}</dl></Box></div>
    <Box title="Eʼtibor kerak" sub="Nol platforma balansi qarz deb qabul qilinmaydi. Faqat chiqarilgan hisoblar tekshiriladi."><div className="finance-attention"><div><strong>{data.summary.overdueCount}</strong><span>Muddati oʻtgan hisob</span><button className="finance-text-button" onClick={()=>{setTab("learners");setOnlyDebt(true)}}>Roʻyxatni ochish <ArrowUpRight size={14}/></button></div><div><strong>{data.learners.filter(l=>l.status==="ACTIVE"&&!data.invoices.some(i=>i.learnerId===l.id&&i.month===data.month)).length}</strong><span>Bu oy hisob ochilmagan faol oʻquvchi</span><button className="finance-text-button" onClick={()=>setTab("learners")}>Hisob chiqarish <ArrowUpRight size={14}/></button></div><div><strong>{data.legacyCount}</strong><span>Eski Payment yozuvi · yangi tushum emas</span><p>Demo va real yozuvlarni alohida tekshirib, keyin ko‘chirish kerak.</p></div></div></Box>
    <div className="finance-grid"><Box title="Kurs toʻlovini qabul qilish" sub="Qisman toʻlov va bir necha kanal qoʻllab-quvvatlanadi. Har bir toʻlov alohida yoziladi."><EntryForm kind="TUITION" data={data} open={!!open} busy={busy} mutate={mutate}/></Box><Box title="Yangi registr bilan boshlash" sub="Excel qatorlari sayt foydalanuvchisi degani emas. Hisobsiz oʻquvchilar ham moliyaviy registrda boʻlishi mumkin."><ol className="finance-steps"><li>Xodim va ulushni tasdiqlang.</li><li>Oʻquvchi, guruh, tarif va toʻlov muddatini kiriting.</li><li>Tanlangan oy uchun hisob chiqaring.</li><li>Tushum, avans, ish haqi va xarajatni yozing.</li><li>Jurnalni tekshirib, oyni yoping.</li></ol><button className="finance-button" onClick={()=>setTab("setup")}>Sozlamalarni ochish</button></Box></div>
   </div>}
   {tab==="learners"&&<div className="finance-stack">
    <div className="finance-filter"><label className="finance-search"><Search size={17}/><input aria-label="Oʻquvchini qidirish" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ism, guruh yoki telefon…"/></label><label className="finance-check"><input type="checkbox" checked={onlyDebt} onChange={e=>setOnlyDebt(e.target.checked)}/>Faqat qarzi bor</label></div>
    <Box title="Oʻquvchilar registri" sub="Faollikni toʻxtatish sayt akkauntini muzlatmaydi; faqat yangi oylik hisob chiqarishga taʼsir qiladi.">
     {learners.length?<><div className="finance-mobile-cards">{learners.map(l=><article key={l.id}><h3>{l.fullName}</h3><p>{l.groupName} · {statusNames[l.status]}</p><dl><div><dt>Oylik tarif</dt><dd>{formatUzs(l.monthlyFee)} UZS</dd></div><div><dt>Jami hisob qarzi</dt><dd>{formatUzs(data.invoices.filter(i=>i.learnerId===l.id).reduce((n,i)=>n+BigInt(i.remaining),0n))} UZS</dd></div></dl><button className="finance-text-button" onClick={()=>{setEditingId(l.id);setTab("setup")}}>Tarif / maʼlumot</button></article>)}</div><p className="finance-table-hint">Hisob tanlash va batafsil jadvalni yon tomonga surish mumkin.</p><div className="finance-table-wrap"><table><thead><tr><th>Tanlash</th><th>Oʻquvchi / guruh</th><th>Oylik tarif</th><th>Toʻlov kuni</th><th>Holat</th><th>Qarz</th><th>Boshqarish</th></tr></thead><tbody>{learners.map(l=><tr key={l.id}><td><input aria-label={`${l.fullName} uchun hisob tanlash`} type="checkbox" checked={selected.includes(l.id)} disabled={l.status!=="ACTIVE"||!open||busy} onChange={e=>setSelected(e.target.checked?[...selected,l.id]:selected.filter(id=>id!==l.id))}/></td><td><strong>{l.fullName}</strong><small>{l.groupName} · {l.phone||"Telefon kiritilmagan"}</small></td><td>{formatUzs(l.monthlyFee)} UZS</td><td>{l.dueDay}-kun</td><td><span className="finance-badge">{statusNames[l.status]}</span></td><td>{formatUzs(data.invoices.filter(i=>i.learnerId===l.id).reduce((s,i)=>s+BigInt(i.remaining),0n))} UZS</td><td><select aria-label={`${l.fullName} holati`} value={l.status} disabled={busy} onChange={e=>void mutate(learnerCommand(l,e.target.value))}>{["ACTIVE","PAUSED","LEFT"].map(s=><option key={s} value={s}>{statusNames[s]}</option>)}</select><button className="finance-text-button" onClick={()=>{setEditingId(l.id);setTab("setup")}}>Tarif / maʼlumot</button></td></tr>)}</tbody></table></div><div className="finance-table-actions"><button className="finance-button" disabled={!open||busy||!learners.some(l=>l.status==="ACTIVE")} onClick={()=>setSelected(learners.filter(l=>l.status==="ACTIVE").map(l=>l.id))}>Faollarni tanlash</button><button className="finance-button finance-button-primary" disabled={!open||busy||!selected.length} onClick={()=>{if(window.confirm(`${selected.length} ta oʻquvchi uchun ${data.month} hisob chiqarilsinmi? Mavjud hisob qayta yozilmaydi.`))void mutate({action:"BILL_LEARNERS",month:data.month,learnerIds:selected})}}>{selected.length} ta hisob chiqarish</button><p className="finance-help">Bir oyga bir oʻquvchi uchun bitta hisob. Maxsus narxni oʻquvchi tarifida tasdiqlang.</p></div></>:<Empty>Roʻyxat boʻsh. “Sozlamalar”da oʻquvchi qoʻshing yoki qidiruvni oʻzgartiring.</Empty>}
    </Box>
    <Box title="Hisoblar va qarzlar" sub="Oldingi davr hisobini ham shu oydagi toʻlov bilan yopish mumkin.">{invoices.length?<div className="finance-table-wrap"><table><thead><tr><th>Oʻquvchi</th><th>Oy</th><th>Hisob</th><th>Toʻlangan</th><th>Qolgan</th><th>Muddat</th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{i.group}</small></td><td>{i.month}</td><td>{formatUzs(i.amount)}</td><td>{formatUzs(i.paid)}</td><td><span className={i.overdue?"finance-danger":""}>{formatUzs(i.remaining)}{i.overdue?" · kechikkan":""}</span></td><td>{i.dueDate}</td></tr>)}</tbody></table></div>:<Empty>Hisoblar hali chiqarilmagan. Bu qarzlar nol ekanini anglatmaydi.</Empty>}</Box><Box title="Kurs toʻlovini yozish"><EntryForm kind="TUITION" data={data} open={!!open} busy={busy} mutate={mutate}/></Box>
   </div>}
   {tab==="payroll"&&<div className="finance-stack">
    <Box title="Xodimlar va hisob-kitob" sub="Ulush hisob chiqarilgan vaqtda saqlanadi. Keyingi stavka oʻzgarishi eski toʻlovlarni qayta hisoblamaydi. Qoldiq barcha oylarni qamrab oladi.">{data.staff.length?<><div className="finance-mobile-cards">{data.staff.map(s=><article key={s.id}><h3>{s.name}</h3><dl><div><dt>Oyda kurs tushumi</dt><dd>{formatUzs(s.tuition)} UZS</dd></div><div><dt>Oyda hisoblangan</dt><dd>{formatUzs(s.earned)} UZS</dd></div><div><dt>Markaz ulushi</dt><dd>{formatUzs(s.centerShare)} UZS</dd></div><div><dt>Oyda toʻlangan</dt><dd>{formatUzs(s.paid)} UZS</dd></div><div><dt>Jami qoldiq</dt><dd>{formatUzs(s.due)} UZS</dd></div></dl></article>)}</div><p className="finance-table-hint">Batafsil jadvalni yon tomonga surish mumkin.</p><div className="finance-table-wrap"><table><thead><tr><th>Xodim</th><th>Yangi hisobga ulush</th><th>Kurs tushumi</th><th>Markaz ulushi</th><th>Oyda hisoblangan</th><th>Oyda toʻlangan</th><th>Jami qoldiq</th></tr></thead><tbody>{data.staff.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.active?"Faol":"Faol emas"}</small></td><td>{s.shareBps===null?"Tasdiqlanmagan":`${s.shareBps/100}%`}</td><td>{formatUzs(s.tuition)} UZS</td><td>{formatUzs(s.centerShare)} UZS</td><td>{formatUzs(s.earned)} UZS</td><td>{formatUzs(s.paid)} UZS</td><td>{formatUzs(s.due)} UZS{BigInt(s.due)<0n&&<small className="finance-danger">Ortiqcha avans · keyingi davrga oʻtadi</small>}</td></tr>)}</tbody></table></div></>:<Empty>Avval “Sozlamalar”da xodim qoʻshing.</Empty>}</Box>
    <div className="finance-grid"><Box title="Avans berish" sub="Avans chiqimdir, qoʻshimcha ish haqi xarajati emas."><EntryForm kind="ADVANCE" data={data} open={!!open} busy={busy} mutate={mutate}/></Box><Box title="Ish haqini toʻlash" sub="Hisoblangan qoldiqdan oshirish mumkin emas. Oldindan toʻlov uchun avansni tanlang."><EntryForm kind="SALARY" data={data} open={!!open} busy={busy} mutate={mutate}/></Box></div>
    <Box title="Belgilangan oylik / bonus / tuzatish" sub="Bu pul chiqimi emas, ish haqi majburiyatini hisoblash. Pul berilganda alohida ish haqi yoki avans yoziladi."><form className="finance-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void mutate({action:"ACCRUAL",month:data.month,staffId:get(f,"staffId"),amount:get(f,"amount"),reason:get(f,"reason")})}}><div className="finance-form-row"><Field label="Xodim" name="staffId"><select name="staffId" required defaultValue=""><option value="" disabled>Tanlang</option>{data.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Hisoblanadigan summa · UZS" name="amount" placeholder="2000000" inputMode="numeric" pattern="-?[0-9]+"/></div><Field label="Asos / bonus / tuzatish sababi" name="reason" maxLength={250}/><button type="submit" disabled={!open||busy} className="finance-button">Hisoblashni yozish</button></form>{data.accruals.length>0&&<dl className="finance-ledger-lines">{data.accruals.map(a=><div key={a.id}><dt>{data.staff.find(s=>s.id===a.staffId)?.name} · {a.reason}</dt><dd>{formatUzs(a.amount)} UZS</dd></div>)}</dl>}</Box>
   </div>}
   {tab==="expenses"&&<div className="finance-grid"><Box title="Operatsion xarajat" sub="Arenda, svet, kitob va boshqa chiqimlar. Ish haqini bu yerga takror yozmang."><EntryForm kind="EXPENSE" data={data} open={!!open} busy={busy} mutate={mutate}/></Box><Box title="Boshqa haqiqiy tushum" sub="Kurs tushumini shu yerga yozmang — aks holda oʻquvchi qarzi va ustoz ulushi hisoblanmaydi."><EntryForm kind="OTHER_INCOME" data={data} open={!!open} busy={busy} mutate={mutate}/></Box></div>}
   {tab==="leads"&&<div className="finance-stack"><Box title="Qabul va sinov darslari" sub="Lidni “Qabul qilingan” deb belgilash avtomatik sayt akkaunti yoki moliyaviy oʻquvchi yaratmaydi; ularni alohida tasdiqlang.">{data.leads.length?<div className="finance-table-wrap"><table><thead><tr><th>Ism / telefon</th><th>Guruh</th><th>Kelish sanasi</th><th>Holat</th><th>Izoh</th></tr></thead><tbody>{data.leads.map(l=><tr key={l.id}><td><strong>{l.fullName}</strong><small>{l.phone}</small></td><td>{l.groupName||"—"}</td><td>{l.appointmentAt||"—"}</td><td><select aria-label={`${l.fullName} lid holati`} value={l.status} disabled={busy} onChange={e=>void mutate({action:"UPDATE_LEAD",id:l.id,status:e.target.value,note:l.note??""})}>{["NEW","SCHEDULED","TRIAL","ENROLLED","LOST"].map(s=><option value={s} key={s}>{statusNames[s]}</option>)}</select></td><td>{l.note||"—"}</td></tr>)}</tbody></table></div>:<Empty>Lidlar hali kiritilmagan.</Empty>}{data.coverage.leadsLimited&&<p className="finance-help">Oxirgi 200 ta lid koʻrsatilgan.</p>}</Box><Box title="Yangi lid"><form className="finance-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void mutate({action:"ADD_LEAD",fullName:get(f,"fullName"),phone:get(f,"phone"),groupName:get(f,"groupName"),appointmentDate:get(f,"appointmentDate"),note:get(f,"note")})}}><div className="finance-form-row"><Field label="Ism-familiya" name="fullName" maxLength={250}/><Field label="Telefon" name="phone" maxLength={80}/></div><div className="finance-form-row"><Field label="Guruh / qiziqish" name="groupName" required={false}/><Field label="Kelish sanasi" name="appointmentDate" type="date" required={false}/></div><Field label="Izoh" name="note" required={false}/><button className="finance-button finance-button-primary" disabled={busy}>Lidni saqlash</button></form></Box></div>}
   {tab==="journal"&&<div className="finance-stack"><Box title="Oʻzgarmas pul jurnali" sub="Operatsiya oʻchirilmaydi. Ochiq oyda asos bilan teskari yozuv qoʻshiladi. Yopilgan oyga qayta yozish taqiqlangan."><a className="finance-button" href={`/api/admin/finance?month=${data.month}&export=journal`}><Download size={16}/> CSV eksport</a>{data.entries.length?<><div className="finance-table-wrap"><table><thead><tr><th>Sana / tur</th><th>Ism</th><th>Kanal</th><th>Summa · UZS</th><th>Izoh / admin</th><th>Amal</th></tr></thead><tbody>{data.entries.slice(journalPage*30,(journalPage+1)*30).map(e=><tr key={e.id}><td><strong>{e.date}</strong><small>{kindNames[e.kind]}{e.reversed?" · bekor qilingan":""}</small></td><td>{e.learner??e.staff??"—"}</td><td>{channelNames[e.channel]}</td><td className={BigInt(e.amount)<0n?"finance-danger":""}>{formatUzs(e.amount)}</td><td>{e.description}<small>{e.actor}</small></td><td>{e.kind!=="REVERSAL"&&!e.reversed&&<button className="finance-text-button" disabled={!open||busy} onClick={()=>{const reason=window.prompt("Bekor qilish sababini yozing. Yozuv oʻchirilmaydi.");if(reason?.trim())void mutate({action:"REVERSE_ENTRY",month:data.month,id:e.id,reason:reason.trim()})}}>Bekor qilish</button>}</td></tr>)}</tbody></table></div><div className="finance-table-actions"><button className="finance-button" disabled={journalPage===0} onClick={()=>setJournalPage(journalPage-1)}>Oldingi</button><span>{journalPage+1} / {Math.ceil(data.entries.length/30)} · {data.entries.length} yozuv</span><button className="finance-button" disabled={(journalPage+1)*30>=data.entries.length} onClick={()=>setJournalPage(journalPage+1)}>Keyingi</button></div></>:<Empty>Pul operatsiyalari hali yozilmagan.</Empty>}</Box><Box title="Eski Payment arxivi" sub="Faqat oʻqish uchun. Bu yozuvlar yangi registr tushumlariga avtomatik qoʻshilmaydi; demo / real holatni tasdiqlash kerak.">{data.legacyPayments.length?<div className="finance-table-wrap"><table><thead><tr><th>Sana</th><th>Oʻquvchi</th><th>Tur / holat</th><th>Summa · UZS</th><th>Izoh</th></tr></thead><tbody>{data.legacyPayments.map(p=><tr key={p.id}><td>{p.date}</td><td>{p.name}</td><td>{p.type} · {p.status}</td><td>{formatUzs(p.amount)}</td><td>{p.description}</td></tr>)}</tbody></table></div>:<Empty>Eski Payment yozuvlari yoʻq.</Empty>}<p className="finance-help">{data.legacyPayments.length} / {data.legacyCount} ta eski yozuv. Hisobotga kiritilmagan.</p></Box><Box title="Kurs toʻlovini qaytarish" sub="Avval asl tushum oyini jurnal orqali tekshiring. Qaytarish qarzni va hisoblangan ustoz ulushini tiklaydi; toʻlangan pul bekor boʻlib qolmaydi."><EntryForm kind="REFUND" data={data} open={!!open} busy={busy} mutate={mutate}/></Box></div>}
   {tab==="setup"&&<div className="finance-stack">
    <div className="finance-grid"><Box title="Oy ochish" sub="Qoldiqni kassadan va banklardan tekshirib kiriting. Avtomatik koʻchirish yoʻq; bu tushum emas."><form className="finance-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void mutate({action:"OPEN_PERIOD",month:get(f,"month"),opening:Object.fromEntries(Object.keys(channelNames).map(c=>[c,get(f,c)]))})}}><Field label="Oy" name="month" type="month" defaultValue={data.month}/>{Object.entries(channelNames).map(([c,l])=><Field key={c} label={`${l} boshlangʻich qoldiq · UZS`} name={c} defaultValue="0" inputMode="numeric" pattern="-?[0-9]+"/>)}<button className="finance-button finance-button-primary" disabled={busy}>Qoldiqni tasdiqlab oy ochish</button></form></Box><Box title="Oyni yopish" sub="Yopilgach operatsiyalar va hisoblash yozuvlari shu davrga qoʻshilmaydi. Yangi davrda tuzatish alohida yoziladi."><p className="finance-help">Yopishdan oldin toʻlov kanallari, avanslar, xarajatlar va ish haqi hisobini tekshiring. Qarzlar keyingi oyda ham saqlanadi.</p><form className="finance-form" onSubmit={e=>{e.preventDefault();void mutate({action:"CLOSE_PERIOD",month:data.month,confirmation:get(e.currentTarget,"confirmation")})}}><Field label="Tasdiqlash uchun YOPISH yozing" name="confirmation" placeholder="YOPISH"/><button className="finance-button" disabled={!open||busy}><LockKeyhole size={16}/> Oyni yopish</button></form><p className="finance-help">Pulni avtomatik yuborish yoʻq. Bu faqat registrni yopish.</p></Box></div>
    <Box title="Xodimni roʻyxatga olish" sub="Excel stavkalarini odamga taxminan biriktirmaymiz. Ulushni tasdiqlang; 0% — alohida belgilangan oylik hisoblanadigan xodim uchun."><form className="finance-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void mutate({action:"ADD_STAFF",fullName:get(f,"fullName"),sharePercent:get(f,"sharePercent"),platformTeacherId:get(f,"platformTeacherId")})}}><div className="finance-form-row"><Field label="Ism-familiya" name="fullName"/><Field label="Ulush · %" name="sharePercent" placeholder="66" inputMode="decimal"/></div><Field label="Platforma oʻqituvchisi bilan bogʻlash · ixtiyoriy" name="platformTeacherId"><select name="platformTeacherId" defaultValue=""><option value="">Bogʻlamasdan roʻyxatga olish</option>{data.teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><button className="finance-button" disabled={busy}>Xodimni saqlash</button></form>{data.staff.length>0&&<div className="finance-rate-list">{data.staff.map(s=><form key={s.id} className="finance-rate-row" onSubmit={e=>{e.preventDefault();void mutate({action:"UPDATE_STAFF",id:s.id,sharePercent:get(e.currentTarget,"rate"),active:get(e.currentTarget,"active")==="true"})}}><strong>{s.name}<small className="finance-help">ID: {s.id}</small></strong><label>Ulush %<input aria-label={`${s.name} ulushi`} name="rate" defaultValue={s.shareBps===null?"":String(s.shareBps/100)} required inputMode="decimal"/></label><select aria-label={`${s.name} faolligi`} name="active" defaultValue={String(s.active)}><option value="true">Faol</option><option value="false">Faol emas</option></select><button className="finance-button" disabled={busy}>Yangilash</button></form>)}</div>}</Box>
    <Box title={editing?"Oʻquvchi maʼlumotini yangilash":"Oʻquvchini moliyaviy registrga olish"} sub="Sayt akkaunti yaratilmaydi. Platforma yoki oddiy guruh roʻyxatiga ulash mumkin; bir oʻquvchini ikki marta yaratmang."><form key={editing?`${editing.id}:${editing.monthlyFee}:${editing.dueDay}`:"new-learner"} className="finance-form" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void mutate({action:editing?"UPDATE_LEARNER":"ADD_LEARNER",...(editing?{id:editing.id,sourceKey:editing.sourceKey??""}:{}),fullName:get(f,"fullName"),phone:get(f,"phone"),groupName:get(f,"groupName"),staffId:get(f,"staffId"),monthlyFee:get(f,"monthlyFee"),dueDay:get(f,"dueDay"),status:editing?.status??"ACTIVE",note:get(f,"note"),platformStudentId:get(f,"platformStudentId"),rosterStudentId:get(f,"rosterStudentId")})}}><div className="finance-form-row"><Field label="Ism-familiya" name="fullName" defaultValue={editing?.fullName??""}/><Field label="Telefon" name="phone" required={false} defaultValue={editing?.phone??""}/></div><div className="finance-form-row"><Field label="Guruh nomi / kodi" name="groupName" defaultValue={editing?.groupName??""}/><Field label="Xodim / oʻqituvchi" name="staffId"><select required name="staffId" defaultValue={editing?.staffId??""}><option value="" disabled>Tanlang</option>{data.staff.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field></div><div className="finance-form-row"><Field label="Oylik tarif · UZS" name="monthlyFee" defaultValue={editing?.monthlyFee??"0"} inputMode="numeric" pattern="[0-9]+"/><Field label="Toʻlov muddati · oyning kuni" name="dueDay" type="number" min="1" max="28" defaultValue={editing?.dueDay??5}/></div><div className="finance-form-row"><Field label="Sayt oʻquvchisiga ulash · ixtiyoriy" name="platformStudentId"><select name="platformStudentId" defaultValue={editing?.platformStudentId??""}><option value="">Bogʻlamaslik</option>{data.platformStudents.map(s=><option value={s.id} key={s.id}>{s.name} · {s.group}</option>)}</select></Field><Field label="Hisobsiz guruh aʼzosiga ulash · ixtiyoriy" name="rosterStudentId"><select name="rosterStudentId" defaultValue={editing?.rosterStudentId??""}><option value="">Bogʻlamaslik</option>{data.roster.map(s=><option value={s.id} key={s.id}>{s.name} · {s.group}</option>)}</select></Field></div><Field label="Izoh / maxsus tarif asosi" name="note" required={false} defaultValue={editing?.note??""}/><button className="finance-button finance-button-primary" disabled={busy}>{editing?"Yangilash":"Oʻquvchini saqlash"}</button>{editing&&<button className="finance-button" type="button" onClick={()=>setEditingId(null)}>Yangi oʻquvchi rejimi</button>}</form>{(data.coverage.platformStudentsLimited||data.coverage.rosterLimited)&&<p className="finance-help">Ulash roʻyxati 1000 ta yozuv bilan cheklangan.</p>}</Box>
    <Box title="Excel koʻchirish — avval tekshirish" sub="Bu versiya maxfiy Excel faylingizni GitHubga yoki ishchi bazaga avtomatik yuklamaydi."><p className="finance-help">Eski jadvaldagi qarzlar, checkbox va yashirin varaqlar tasdiqlanmagan. Ism, guruh, tarif, xodim va boshlangʻich qoldiqni moslashtirib, test bazasida tekshiring. Eski Payment yozuvlari alohida manba; demo bilan haqiqiy tushumni aralashtirmang.</p><p className="finance-help">XLSXni tekshirilgan CSVga aylantirish uchun scripts/convert-finance-workbook.py ishlatiladi. Har qator uchun staffId, tasdiqlangan monthlyFee va sourceKey talab qilinadi. Qarzni/toʻlovni bu import yozmaydi.</p><label className="finance-field"><span>Tekshirilgan CSV · faqat preview</span><input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];setImportPreview(null);if(!file)return;if(file.size>100000){setNotice({error:true,text:"CSV 100KB dan katta."});return}setBusy(true);try{const response=await fetch("/api/admin/finance/import",{method:"POST",headers:{"Content-Type":"text/csv"},body:await file.text()});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setImportPreview(payload)}catch(e){setNotice({error:true,text:e instanceof Error?e.message:"Import tekshiruvi bajarilmadi."})}finally{setBusy(false)}}}/></label>{importPreview&&<div className="finance-import-preview"><p>{importPreview.count} ta qator tekshirildi. Bu bosqich hali yozmaydi.</p>{importPreview.issues.map((i,n)=><p key={n} className="finance-danger">{i}</p>)}<div className="finance-table-wrap"><table><thead><tr><th>Ism</th><th>Guruh</th><th>Tarif</th><th>Xodim ID</th></tr></thead><tbody>{importPreview.items.map((i,n)=><tr key={n}><td>{String(i.fullName)}</td><td>{String(i.groupName)}</td><td>{formatUzs(String(i.monthlyFee))}</td><td>{String(i.staffId)}</td></tr>)}</tbody></table></div><button className="finance-button" disabled={busy||importPreview.issues.length>0} onClick={()=>{if(window.confirm("Faqat moliyaviy oʻquvchi registri import qilinsinmi? Pul va qarzlar import qilinmaydi."))void mutate({action:"IMPORT_LEARNERS",items:importPreview.items})}}>Tasdiqlab registrga olish</button></div>}</Box>
   </div>}
   <footer className="finance-footer"><ShieldCheck size={15}/><span>UZS · Asia/Tashkent · rollar tekshiriladi · har bir saqlash audit bilan birga</span></footer>
  </div>
 </main>;
}
