#!/usr/bin/env node
/**
 * Writes Averna's theme colour tokens (lib/theme-tokens.json) into
 * app/globals.css, between the THEME TOKENS markers.
 *
 *   node scripts/theme-tokens.mjs            # print the CSS block
 *   node scripts/theme-tokens.mjs --write    # update app/globals.css
 *
 * How the theme works: tailwind.config.ts maps Tailwind's `white`, `gray-*`,
 * the bright accent shades and the `averna-*` brand colours to CSS variables
 * (`rgb(var(--c-…) / <alpha-value>)`). Every token has a dark value (the
 * default) and a light value (html.light); exam screens (.exam-shell) always
 * use the dark values, like the real computer-delivered test. So one class —
 * `text-white`, `bg-white/5`, `border-white/10`, `text-gray-400`,
 * `bg-amber-400/10`, `ring-averna-neon/40` — is right in both themes, with no
 * per-class overrides.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { tokens, keepWhiteInk } = JSON.parse(readFileSync(join(root, "lib", "theme-tokens.json"), "utf8"));

const rgb = (h) => h.replace("#", "").match(/../g).map((x) => parseInt(x, 16)).join(" ");
const cls = (c) => c.replace(/\//g, "\\/");

const BEGIN = "/* ==== THEME TOKENS (generated by scripts/theme-tokens.mjs from lib/theme-tokens.json — do not edit by hand) ==== */";
const END = "/* ==== END THEME TOKENS ==== */";

function block() {
  const decl = (i) => tokens.map((t) => `  --c-${t[0]}: ${rgb(t[i])};`).join("\n");
  // Plain CSS on purpose (not @layer base): Tailwind never drops it, and only
  // custom properties are declared, so its position in the cascade is irrelevant.
  return `${BEGIN}
/* Dark values: the default, and always inside exam screens. */
:root,
html.light .exam-shell {
${decl(1)}
}
html.light {
${decl(2)}
}
/* Solid white and saturated fills keep white ink (button labels, switch knobs …). */
${keepWhiteInk.map((c) => `html.light .${cls(c)}`).join(",\n")} {
  --c-white: ${rgb("#ffffff")};
}
${END}`;
}

const css = block();
if (process.argv.includes("--write")) {
  const file = join(root, "app", "globals.css");
  const src = readFileSync(file, "utf8");
  const a = src.indexOf("/* ==== THEME TOKENS");
  const b = src.indexOf(END);
  if (a === -1 || b === -1) throw new Error("THEME TOKENS markers not found in app/globals.css");
  writeFileSync(file, src.slice(0, a) + css + src.slice(b + END.length));
  console.log(`Wrote ${tokens.length} tokens to app/globals.css`);
} else {
  console.log(css);
}
