/**
 * Writes Averna's theme colour tokens (lib/theme-tokens.json) into
 * app/globals.css, between the THEME TOKENS markers.
 *
 *   node scripts/theme-tokens.mjs            # print the CSS block
 *   node scripts/theme-tokens.mjs --write    # update app/globals.css
 *
 * How the theme works: tailwind.config.ts maps Tailwind's `white`, `gray-*`,
 * the bright accent shades, the `averna-*` brand colours and the `exam-*` /
 * `surface-*` surfaces to CSS variables (`rgb(var(--c-…) / <alpha-value>)`).
 * Every token has a dark value (the default, :root) and a light value
 * (html.light). Exam screens follow the selected theme like every other page.
 * So one class — `text-white`, `bg-white/5`, `border-white/10`,
 * `text-gray-400`, `bg-amber-400/10`, `bg-exam-bar/95` — is right in both
 * themes, with no per-class overrides.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const rgb = (h) => h.replace("#", "").match(/../g).map((x) => parseInt(x, 16)).join(" ");
const cls = (c) => c.replace(/\//g, "\\/");

export const BEGIN =
  "/* ==== THEME TOKENS (generated by scripts/theme-tokens.mjs from lib/theme-tokens.json — do not edit by hand) ==== */";
export const END = "/* ==== END THEME TOKENS ==== */";

/**
 * Pure: builds the CSS block (markers included) from the token list.
 * @param {{ tokens: [string, string, string][], keepWhiteInk: string[] }} config
 * @returns {string}
 */
export function buildThemeBlock({ tokens, keepWhiteInk }) {
  const decl = (i) => tokens.map((t) => `  --c-${t[0]}: ${rgb(t[i])};`).join("\n");
  // Plain CSS on purpose (not @layer base): Tailwind never drops it, and only
  // custom properties are declared, so its position in the cascade is irrelevant.
  return `${BEGIN}
/* Dark values: the default. Exam screens follow the selected theme too. */
:root {
${decl(1)}
}
html.light {
${decl(2)}
}
/* Solid white and saturated fills keep white ink (button labels, switch knobs …). */
${keepWhiteInk.map((c) => `html.light .${cls(c)}`).join(",\n")} {
  --c-white: ${rgb("#ffffff")};
}
${END}`;
}

function main() {
  const config = JSON.parse(readFileSync(join(root, "lib", "theme-tokens.json"), "utf8"));
  const css = buildThemeBlock(config);
  if (!process.argv.includes("--write")) {
    console.log(css);
    return;
  }
  const file = join(root, "app", "globals.css");
  const src = readFileSync(file, "utf8");
  const a = src.indexOf("/* ==== THEME TOKENS");
  const b = src.indexOf(END);
  if (a === -1 || b === -1) throw new Error("THEME TOKENS markers not found in app/globals.css");
  const next = src.slice(0, a) + css + src.slice(b + END.length);
  if (next === src) {
    console.log("app/globals.css is up to date");
    return;
  }
  writeFileSync(file, next);
  console.log(`Wrote ${config.tokens.length} tokens to app/globals.css`);
}

// Only touch files when run from the CLI, so buildThemeBlock can be imported in tests.
const norm = (p) => (process.platform === "win32" ? p.toLowerCase() : p);
const invokedPath = process.argv[1] ? norm(resolve(process.argv[1])) : "";
if (invokedPath === norm(fileURLToPath(import.meta.url))) main();
