/** Actual mock service + existing table on isolated PGlite. No env, real users, paid providers or migrations. */
const fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),assert=require('node:assert/strict');const {randomUUID}=require('node:crypto');const {PGlite}=require('@electric-sql/pglite');const esbuild=require('esbuild');const root=path.resolve(__dirname,'..');
(async()=>{const pg=new PGlite();try{
await pg.exec('CREATE TABLE students (id TEXT PRIMARY KEY); INSERT INTO students VALUES (\'s1\'),(\'s2\');');const sql=fs.readFileSync(path.join(root,'prisma/sql/deploy.sql'),'utf8');const begin=sql.indexOf('CREATE TABLE IF NOT EXISTS "mock_attempts"');const end=sql.indexOf(';',sql.indexOf('WHERE "status" = \'active\'',begin))+1;await pg.exec(sql.slice(begin,end));
const papers={mode:'cd-v1',listening:'averna-listening-01',reading:'averna-reading-01',task1:'w1',task2:'w2',speaking:''};
await pg.query('INSERT INTO mock_attempts (id,"studentId",papers,"sectionStartedAt","sectionDeadline") VALUES ($1,$2,$3,now(),now()+interval \'1 hour\')',['a','s1',JSON.stringify(papers)]);
await assert.rejects(pg.query('INSERT INTO mock_attempts (id,"studentId",papers) VALUES ($1,$2,$3)',['duplicate','s1',JSON.stringify(papers)]));
function dates(row){if(!row)return null;for(const k of ['sectionStartedAt','sectionDeadline','startedAt','finishedAt','updatedAt'])if(row[k])row[k]=new Date(row[k]);return row;}
const mockAttempt={findFirst:async({where})=>dates((await pg.query('SELECT * FROM mock_attempts WHERE id=$1 AND "studentId"=$2',[where.id,where.studentId])).rows[0]),findMany:async()=>[],updateMany:async({where,data})=>{const values=[],sets=[],filters=[];const put=v=>{values.push(v instanceof Date?v.toISOString():v);return '$'+values.length;};for(const [k,v]of Object.entries(data)){const json=['papers','draft','results'].includes(k);const dbNull=v?.constructor?.name==='DbNull';sets.push('"'+k+'"='+put(json?dbNull?null:JSON.stringify(v):v)+(json?'::jsonb':''));}sets.push('"updatedAt"=clock_timestamp()');for(const [k,v]of Object.entries(where)){if(k==='draft'){const expected=v.equals;if(expected?.constructor?.name==='AnyNull')filters.push("(draft IS NULL OR draft='null'::jsonb)");else filters.push('draft='+put(JSON.stringify(expected))+'::jsonb');continue;}if(k==='sectionDeadline'){filters.push('"sectionDeadline">='+put(v.gte));continue;}filters.push('"'+k+'"='+put(v));}const r=await pg.query('UPDATE mock_attempts SET '+sets.join(',')+' WHERE '+filters.join(' AND ')+' RETURNING id',values);return {count:r.rows.length};}};
global.__mockDb={mockAttempt,iELTSTest:{findMany:async()=>[]}};
const stubs={db:'export const db=globalThis.__mockDb;',catalog:`import { READING_SEED,LISTENING_SEED } from '${path.join(root,'lib/ielts/content/index.ts')}'; export const getReadingExam=async()=>READING_SEED[0];export const getListeningExam=async()=>LISTENING_SEED[0];export const getSpeakingSet=async()=>null;export const getWritingTask=async()=>null;export const listListeningExams=async()=>[];export const listReadingExams=async()=>[];export const listSpeakingSets=async()=>[];export const listWritingTasks=async()=>[];`,submit:'export const examPrompt=x=>x;export const submitObjectiveExam=()=>{throw new Error("No provider or grader expected for blank answers")};export const submitWritingExam=submitObjectiveExam;export const submitSpeakingTest=submitObjectiveExam;',recording:'export const hasRecordedSpeech=async()=>false;'};
const b=await esbuild.build({entryPoints:[path.join(root,'lib/ielts/mock.ts')],bundle:true,platform:'node',format:'cjs',write:false,packages:'external',tsconfig:path.join(root,'tsconfig.json'),plugins:[{name:'isolated-mock',setup(b){b.onResolve({filter:/^(?:@\/lib\/db|\.\/catalog|\.\/submit|@\/lib\/speaking\/recording)$/},a=>({path:a.path==='@/lib/db'?'db':a.path==='./catalog'?'catalog':a.path==='./submit'?'submit':'recording',namespace:'qa'}));b.onLoad({filter:/.*/,namespace:'qa'},a=>({contents:stubs[a.path],loader:'ts',resolveDir:root}));}}]});const compiled=new Module(path.join(root,'scripts/__isolated-mock.cjs'),module);compiled.filename=path.join(root,'scripts/__isolated-mock.cjs');compiled.paths=Module._nodeModulePaths(path.join(root,'scripts'));compiled._compile(b.outputFiles[0].text,compiled.filename);const {saveMockDraft,submitMockSection}=compiled.exports;
assert.equal((await saveMockDraft('s2','a',0,{answers:{}},0)).ok,false);
const writes=await Promise.all([saveMockDraft('s1','a',0,{answers:{'1':'A'}},0),saveMockDraft('s1','a',0,{answers:{'1':'B'}},0)]);assert.equal(writes.filter(r=>r.ok).length,1);assert.equal(writes.filter(r=>r.conflict).length,1);
const saved=await mockAttempt.findFirst({where:{id:'a',studentId:'s1'}});assert.equal(saved.draft.__mock.revision,1);
assert.equal((await saveMockDraft('s1','a',0,{answers:saved.draft.answers},0)).ok,true);
const before=await mockAttempt.findFirst({where:{id:'a',studentId:'s1'}});await pg.query('UPDATE mock_attempts SET "updatedAt"="updatedAt"+interval \'1 second\' WHERE id=$1',['a']);assert.equal((await mockAttempt.updateMany({where:{id:'a',studentId:'s1',updatedAt:before.updatedAt},data:{draft:{answers:{'1':'stale'}}}})).count,0);
await pg.query('UPDATE mock_attempts SET draft=NULL,"sectionDeadline"=now()-interval \'10 seconds\' WHERE id=$1',['a']);const expired=await mockAttempt.findFirst({where:{id:'a',studentId:'s1'}});const input={studentId:'s1',userId:'u1',attemptId:'a',section:0,payload:{answers:{'1':'too late'}},revision:0};assert.equal((await submitMockSection(input)).ok,true);let row=await mockAttempt.findFirst({where:{id:'a',studentId:'s1'}});assert.equal(row.current,1);assert.equal(row.results.LISTENING.band,0);assert.equal(row.sectionStartedAt.getTime(),expired.sectionDeadline.getTime());assert.equal(row.sectionDeadline-row.sectionStartedAt,3600000);assert.equal((await submitMockSection(input)).ok,true);
await pg.query('UPDATE mock_attempts SET "current"=2,draft=NULL,"sectionStartedAt"=now(),"sectionDeadline"=now()+interval \'1 hour\' WHERE id=$1',['a']);assert.equal((await submitMockSection({...input,section:2,payload:{essays:{task1:'',task2:''}},revision:0})).done,true);row=await mockAttempt.findFirst({where:{id:'a',studentId:'s1'}});assert.equal(row.status,'finished');assert.equal(row.overall,null);await pg.query('INSERT INTO mock_attempts (id,"studentId",papers) VALUES ($1,$2,$3)',['next','s1',JSON.stringify(papers)]);await pg.exec("DELETE FROM students WHERE id='s1'");assert.equal((await pg.query('SELECT * FROM mock_attempts')).rows.length,0);
console.log('PASS: actual mock service + existing SQL table: owner isolation, single-active index, competing revision CAS, stale timestamp guard, replay, deadline draft, uninterrupted next clock, three-section completion, null overall, FK cascade. Isolated PGlite is not production multi-connection certification.');
}finally{delete global.__mockDb;await pg.close();}})().catch(e=>{console.error(e);process.exit(1);});
